### ISSUE TITLE
rate the rice

### ISSUE THREAD

**Issue by 3hree6ix0** [catppuccin/catppuccin#10]
hey, this is u/Mlgkilluminati here, as i said i was working on a rice with this theme lmk what you think about it!
![image](https://user-images.githubusercontent.com/77652388/145557544-233ba147-abbb-4c69-87d6-ce5ba01b36ff.png)
the wallpaper is selfmade, ill make a pr to the wallpapers repo soon!
im open to suggestions @Pocco81 :smile:

**Comment by Pocco81** [comment]
8/10 🥳

I'm not a ricer myself, but some recommendations:
+ Maybe a thicker font?
+ My personal favorite sys info fetching tool is [rxfetch](https://github.com/Mangeshrex/rxfetch), really sassy if you ask me 👀:

![image](https://user-images.githubusercontent.com/58336662/145579420-4c9c2ad0-a49d-4c0c-8523-476c192e1571.png)

**Comment by 3hree6ix0** [comment]
where did those two points go XD? also thats a nice fetch, imma use that in the next screenshot, thicker font? okay!

**Comment by Pocco81** [comment]
@3hree6ix0 [Catppuccin v0.1.1](https://github.com/catppuccin/catppuccin/releases/tag/v0.1.1) was released a while ago and with it came better syntax highlighting for code editor ports, better luminance balance, and more!

We are also working on a GTK theme (not done yet tho). So now you have a bunch of new material:

![Screenshot from 2021-12-21 11-57-47](https://user-images.githubusercontent.com/58336662/146969507-4ec0937f-2cfb-4274-8fea-212dc47bc3e5.png)

**Comment by Pocco81** [comment]
And btw, could we move this conversation to the `#rices` channel on Discord? That way more people will get so your rice and provide feedback :+1:
