### ISSUE TITLE
GDM (login screen theme)

### ISSUE THREAD

**Issue by DewenHona** [catppuccin/catppuccin#101]
**Are you available to help in the creation of this port? 😄 (optional)**
NO

**Additional context 📷 (optional)**
GDM theme or the login screen theme for linux based distros

**Comment by elkrien** [comment]
I'm not sure if it is possible. 
I have seen an app to do it but it is in early development stage:

https://github.com/realmazharhussain/gdm-settings

I haven't use it but looking on the screens it uses GTK themes and Catppuccin one is already done.

**Comment by nekowinston** [comment]
Since this is tracked on https://github.com/catppuccin/gtk/issues/21, I'll close the issue here.
