### ISSUE TITLE
Taskwarrior

### ISSUE THREAD

**Issue by davidbgonz** [catppuccin/catppuccin#106]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Taskwarrior is a CLI based task manager.
Example of one of the included themes for taskwarrior:
![image](https://user-images.githubusercontent.com/10837237/159961440-a4ed58ef-c613-44df-a9ea-cfdfe626c9b5.png)

**Comment by ghostx31** [comment]
Since this is being tracked elsewhere, I'll go ahead and close this.
