### ISSUE TITLE
Anki

### ISSUE THREAD

**Issue by ErikBolumburu** [catppuccin/catppuccin#107]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
[Anki Recolor Addon](https://ankiweb.net/shared/info/688199788)

**Comment by AnubisNekhet** [comment]
I've taken a glance at the repo of the addon and it should come bundled with the next release. The theme is available in [this page](https://github.com/AnKingMed/AnkiRecolor/wiki/Catppuccin) if you want to use it right now.

**Comment by nekowinston** [comment]
Closed with 00395286d26734c45ba71272966bd9aba55ce645
