### ISSUE TITLE
tym

### ISSUE THREAD

**Issue by justleoo** [catppuccin/catppuccin#109]
**Are you available to help in the creation of this port? 😄**
yes, i've done this

**Additional context**
<img src="https://raw.githubusercontent.com/justleoo/tym/main/assets/showcase.png"/>

see the repo in https://github.com/justleoo/tym/

**Comment by Spaxly** [comment]
Hi, please join the catppuccin discord server(https://discord.gg/PrCRSWftUa) and we will help you transfer your repository to the catppuccin organization.

**Comment by nekowinston** [comment]
Closing this since it's been transferred for some time.

Added in 6b9a41b243ac6964bcc18f4e363ae26c7a0daead
