### ISSUE TITLE
Ulauncher

### ISSUE THREAD

**Issue by lighttigerXIV** [catppuccin/catppuccin#112]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

This time i made a theme for ulauncher, another keyboard launcher and i would like you to see if it's good enough for this community :P
And add it here of course.

The repo i made: https://github.com/lighttigerXIV/Catppuccin-Ulauncher

**Comment by Xurdejl** [comment]
@lighttigerXIV 
I've opened a pull request with some changes and the remaining flavours.

Also, in order to ensure consistency, you should rename the repository to "ulauncher" in lowercase, change the description to something like "🇺 Soothing pastel theme for Ulauncher" and add "catppuccin" to the topics.

**Comment by lighttigerXIV** [comment]
> @lighttigerXIV I've opened a pull request with some changes and the remaining flavours.
> 
> Also, in order to ensure consistency, you should rename the repository to "ulauncher" in lowercase, change the description to something like "🇺 Soothing pastel theme for Ulauncher" and add "catppuccin" to the topics.

It should be okay now.

**Comment by lighttigerXIV** [comment]
@Xurdejl I merged your request and changed the read me command. Nice job for the other ports 😁.

**Comment by Xurdejl** [comment]
Nice! This should be now ready for review.

**Comment by lighttigerXIV** [comment]
I noticed that frappe round wasn't with the correct colors so i changed it

**Comment by Xurdejl** [comment]
Hey @nekowinston, could you label this as ready for review, please? ^^

**Comment by nekowinston** [comment]
Thanks for the ping @Xurdejl! Labeled it.

The repo looks good, but I noticed that the emoji in the description doesn't render at all on my Linux machine, and looks broken on my macOS. :thinking:

Those links are currently mixed and will have to be fixed as well:
https://github.com/lighttigerXIV/ulauncher/blob/79f7e21e5918058860040f30283a5447a81396f1/README.md?plain=1#L8-L12

I'll invite @lighttigerXIV to the org, feel free to transfer it once the README is adapted :slightly_smiling_face:

**Comment by nekowinston** [comment]
Oh and I just saw that Ulauncher is on GitHub as well, we usually prefer links to the GitHub repos (for the app name header) instead when available: https://github.com/Ulauncher/Ulauncher/

**Comment by lighttigerXIV** [comment]
> 

Do you have noto font emoji? On my pc it looks ok.

**Comment by lighttigerXIV** [comment]
> Thanks for the ping @Xurdejl! Labeled it.
> 
> The repo looks good, but I noticed that the emoji in the description doesn't render at all on my Linux machine, and looks broken on my macOS. thinking
> 
> Those links are currently mixed and will have to be fixed as well: https://github.com/lighttigerXIV/ulauncher/blob/79f7e21e5918058860040f30283a5447a81396f1/README.md?plain=1#L8-L12
> 
> I'll invite @lighttigerXIV to the org, feel free to transfer it once the README is adapted slightly_smiling_face

Do you have noto font emoji installed? On my machine it shows up fine

**Comment by nekowinston** [comment]
Yes, `noto-fonts-emoji` makes it work, but it's still broken on macOS for me - seems that regional indicator emojis don't show on GitHub when on macOS.

Anyways, don't let the description emoji hinder you, just the README fixes are good enough :+1:

**Comment by lighttigerXIV** [comment]
> Yes, `noto-fonts-emoji` makes it work, but it's still broken on macOS for me - seems that regional indicator emojis don't show on GitHub when on macOS.
> 
> Anyways, don't let the description emoji hinder you, just the README fixes are good enough :+1: 

I think i fixed them. You can check them now

**Comment by nekowinston** [comment]
After merging that PR, you can transfer the repository @lighttigerXIV

**Comment by lighttigerXIV** [comment]
> @lighttigerXIV sorry for another ping, but could you please accept the invite and transfer the repository to `catppuccin/ulauncher`? 🙂 

Where do i need to go? I can't find anything about that transfer. Not even a notification

**Comment by lighttigerXIV** [comment]
> @lighttigerXIV sorry for another ping, but could you please accept the invite and transfer the repository to `catppuccin/ulauncher`? 🙂 

Where do i need to go? I can't find anything about that transfer. Not even a notification

**Comment by nekowinston** [comment]
You should've got an invitation email, at least an open invitation here: https://github.com/settings/organizations

**Comment by lighttigerXIV** [comment]
> You should've got an invitation email, at least an open invitation here: https://github.com/settings/organizations

Do i need to create a repository and fork now?

**Comment by nekowinston** [comment]
Neither. Please go to https://github.com/lighttigerXIV/ulauncher/settings, scroll all the way down, and use "Transfer Ownership" -> to "catppuccin"

**Comment by lighttigerXIV** [comment]
> Neither. Please go to https://github.com/lighttigerXIV/ulauncher/settings, scroll all the way down, and use "Transfer Ownership" -> to "catppuccin"

Just delete the one i crated before XD. I can't transfer now because it says it already exists XD

**Comment by lighttigerXIV** [comment]
Sorry for this mess XD

**Comment by nekowinston** [comment]
Alright, it's deleted.

> Sorry for this mess XD

No worries.
