### ISSUE TITLE
Spyder

### ISSUE THREAD

**Issue by martimdfreitasg** [catppuccin/catppuccin#113]

**Comment by Pocco81** [comment]
Just to be sure, you mean [this](https://github.com/spyder-ide/spyder) Spyder, right?

**Comment by meme8383** [comment]
Currently in development: https://github.com/meme8383/spyder

**Comment by nekowinston** [comment]
Hey @meme8383, thanks for your work on this! 😄 

I've sent you an invite to the org, feel free to transfer the repo.
