### ISSUE TITLE
Thunderbird

### ISSUE THREAD

**Issue by ncaycedo** [catppuccin/catppuccin#115]
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Additional context 📷 (optional)**
I'm catppuccining everything, really love the color scheme! However, I'm missing a theme for Thunderbird. Thanks a lot for your hard work ^^

**Comment by bwbuhse** [comment]
Big +1 on this. I may try get around to it if I have some time.

**Comment by etrigan63** [comment]
+1

**Comment by elkrien** [comment]
I made a theme and uploaded it to organization: https://github.com/catppuccin/thunderbird
PR to dev branch submitted.
![image](https://user-images.githubusercontent.com/78103450/173252703-6e3329f8-31c1-4c01-8eeb-2f1cfeb289bc.png)

**Comment by ncaycedo** [comment]
Wonderful! Thank you so much, it's working great :smile:
