### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by Suyashtnt** [catppuccin/catppuccin#118]
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Additional context 📷 (optional)**
All my apps are catppuccin-ified except for steam and it makes me sad

**Comment by Sekki21956** [comment]
If anyone has experience I am willing to help with this. Sadly I'm not that experienced yet with themeing.

**Comment by Spaxly** [comment]
This would be a nice port. I will look more into theming Steam.

**Comment by Spaxly** [comment]
Looks like Steam theming is done through Steam Skins. Websites like steamcustomizer.com only theme the outer areas of the Steam client as far as I know.

**Comment by Spaxly** [comment]
I'd recommend actually finish the theme and then make the repository. Then, you can join the catppuccin discord server(link is found on the catppuccin main page) and we would help you transfer the repository to the catppuccin organization.

**Comment by Sekki21956** [comment]
Ok I have just tried using the Steamcustomizer but that tool seems like it wont work on linux at all. You can use it in the web to make a theme but to install it you would need the tool (which only runs as an .exe).
I've now taken a look at the Dracula theme for steam and it seems they just copy the whole repo with some .css into the steam/skins folder and it will work. I will look further into how this works.

**Comment by skinatro** [comment]
I am trying to do the steam skin with steam for metro + linux patch

**Comment by Dukeatron** [comment]
Repoup at https://github.com/Dukeatron/steam

**Comment by nekowinston** [comment]
Transferred to the org and added to the README in 5b0548ce51192da7c813e8b64caa573518abb453
