### ISSUE TITLE
PhpStorm

### ISSUE THREAD

**Issue by jose-sampedro** [catppuccin/catppuccin#12]
I would love to use this as a theme for PhpStorm

❤️ ❤️ 

Thx!!!

**Comment by asjur** [comment]
Yes please

**Comment by tiepp** [comment]
There's a [JetBrains port](https://github.com/catppuccin/jetbrains). I assume this should work with PhpStorm as well, but I didn't test.

Would be awesome if someone could actually check and give feedback

**Comment by jolheiser** [comment]
Just as an FYI, the JB theme looks good in GoLand, PyCharm, and IntelliJ. 
I don't have any PHP projects (currently), but it should work there if it works among the other IDEs (all being based on the same core).

If nothing else, I can report back in a month or two when a PHP project comes up at work. 🙂

**Comment by tiepp** [comment]
Thx a lot for Testung 👍

**Comment by nekowinston** [comment]
Closing this for 0.1.0, since I've worked with Catppuccin + PhpStorm quite a bit.

If we're moving forward with the 0.2.0 conversion, and issues arise regarding the PHP syntax, we'll keep track of those issues on https://github.com/catppuccin/jetbrains.
