### ISSUE TITLE
[Other Request] Linux dotfiles with Catppuccin EVERYTHING installed.

### ISSUE THREAD

**Issue by BlueFalconHD** [catppuccin/catppuccin#123]
I would love to see the entire Catppuccin configs become a huge collection of dotfiles. I believe that if you share your dots, everyone would love it!!

**Comment by Pocco81** [comment]
Lovely idea! in the mean time you can check out my own dots: https://github.com/Pocco81/.dots

**Comment by andreasgrafen** [comment]
This is a tough one tho.. no? Because dotfiles are usually something highly tailored to the individual user? I can't speak for others, but I personally have altered at lesat 90% of all the configs that Catppuccin provided to make it fit even more to my liking. o:

**Comment by BlueFalconHD** [comment]
> This is a tough one tho.. no? Because dotfiles are usually something highly tailored to the individual user? I can't speak for others, but I personally have altered at lesat 90% of all the configs that Catppuccin provided to make it fit even more to my liking. o:

I know, but it would be a starting place for users like me who suck at linux. And if I didnt like something, I could tweak it, but half the time I have no idea what file to make or where to put things.

**Comment by sioodmy** [comment]
https://github.com/sioodmy/nixdots

**Comment by sioodmy** [comment]
> The problem with this is that many supported applications don't rely on the .config folder at all. For instance Discord, Telegram, Your browser (GitHub, Dark reader), and many other officially supported programs and frameworks
> 
> Thus, you'd need to do MORE than just publishing a catppuccin dotfiles repo. not to mention that **you'd have to remove half of the dotfiles after cloning** as someone isn't gonna be using 2 different programs which do the same thing at the same time
> 
> if anything, I'd suggest an automated installation script for officially supported programs and such

what about home-manager module?

- you can install it on every distro
- autoupdates
- dependency control

**Comment by TGRush** [comment]
> > The problem with this is that many supported applications don't rely on the .config folder at all. For instance Discord, Telegram, Your browser (GitHub, Dark reader), and many other officially supported programs and frameworks
> > 
> > Thus, you'd need to do MORE than just publishing a catppuccin dotfiles repo. not to mention that **you'd have to remove half of the dotfiles after cloning** as someone isn't gonna be using 2 different programs which do the same thing at the same time
> > 
> > if anything, I'd suggest an automated installation script for officially supported programs and such
> 
> what about home-manager module?
> 
> - you can install it on every distro
> - autoupdates
> - dependency control 

what is this in the first place?
and what exactly is it a module to?

**Comment by sioodmy** [comment]
> > > The problem with this is that many supported applications don't rely on the .config folder at all. For instance Discord, Telegram, Your browser (GitHub, Dark reader), and many other officially supported programs and frameworks
> > > Thus, you'd need to do MORE than just publishing a catppuccin dotfiles repo. not to mention that **you'd have to remove half of the dotfiles after cloning** as someone isn't gonna be using 2 different programs which do the same thing at the same time
> > > if anything, I'd suggest an automated installation script for officially supported programs and such
> > 
> > 
> > what about home-manager module?
> > 
> > * you can install it on every distro
> > * autoupdates
> > * dependency control
> 
> what is this in the first place? and what exactly is it a module to?

nix based dotfiles managment

**Comment by Pocco81** [comment]
Due to the complexity of implementing something like this (as stated by @TGRush) I'm going to be closing the issue.
