### ISSUE TITLE
Helix

### ISSUE THREAD

**Issue by elkrien** [catppuccin/catppuccin#124]
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Additional context 📷 (optional)**
Anyone can make theme for Helix Editor?

**Comment by Spaxly** [comment]
I have made the port, just changing some colors around. Will most likely be in packaged in a repository today, if not, tomorrow.

**Comment by Spaxly** [comment]
https://github.com/catppuccin/helix

Here's the port for the Helix editor! Hope you like it and feel free to make any pull requests or issues.
