### ISSUE TITLE
Kakoune

### ISSUE THREAD

**Issue by uncomfyhalomacro** [catppuccin/catppuccin#126]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes. I have made a repo for it https://github.com/uncomfyhalomacro/kakoune/

**Additional context 📷 (optional)**
![image](https://user-images.githubusercontent.com/66054069/162562112-47bea252-a14e-4661-a690-1ac18b9e4932.png)

**Comment by tuhanayim** [comment]
Repo link is broken currently.

**Comment by uncomfyhalomacro** [comment]
> Repo link is broken currently.

It is now part of catppuccin org. https://github.com/catppuccin/kakoune
