### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by Pocco81** [catppuccin/catppuccin#13]
Originally requested on the Discord server

**Comment by BrunDerSchwarzmagier** [comment]
I made a sublime theme (and a slack theme) but there's no repo. How should I proceed?

**Comment by Pocco81** [comment]
So, people usually [create the repo](https://github.com/catppuccin/style-guide#creation) on their accounts and once that's there it can later be moved into the org. However, it's likely that you are not the only one working on the port/some other users might want to contribute directly or via feedback **before** it gets moved into the org. That's why we have the [Discord server](https://discord.gg/r6Mdz5dpFc).

**Comment by Pocco81** [comment]
Done: https://github.com/catppuccin/sublime-text

At the time of writing a couple of things are still `WIP`, however the theme should be stable enough for daily usage.

**Comment by bwhitehead0** [comment]
> I made a sublime theme (and a slack theme) but there's no repo. How should I proceed?

hey, curious about the slack theme, is that anywhere?
