### ISSUE TITLE
Kate

### ISSUE THREAD

**Issue by tsbarnes** [catppuccin/catppuccin#134]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Kate is the default text editor for KDE, so maybe this could be part of the KDE theme?

**Comment by TGRush** [comment]
it IS part of the KDE theme, the colorscheme should be automatically applied if you have it set system-wide

if not, then I advise you to look up how to install KDE Color schemes per-app

**Comment by tsbarnes** [comment]
I don't mean the app colorscheme, I mean the editor colorscheme, which is separate and currently there isn't a Catppuccin one.

**Comment by TGRush** [comment]
ah, pardon me

shouldn't be too hard to do really

**Comment by Sourcastic** [comment]
I've made one, though we'll have to wait for a proper org-wide style guide for code editors before I can make it consistent maybe add syntax for more languages and transfer it: https://github.com/Sourcastic/ctp-KSyntaxHighlighting.

It should work with any of the KDE text editors/IDEs like Kate, Kwrite, Kdevelop etc.

**Comment by backwardspy** [comment]
port looks great, feel free to transfer it when you're ready. thanks for the contribution! :)

**Comment by Sourcastic** [comment]
Thanks, I've transferred the repo over!
