### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by OlaoluwaM** [catppuccin/catppuccin#135]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
It is done. [Link to repo](https://github.com/OlaoluwaM/notion-catppuccin)
![image](https://user-images.githubusercontent.com/37044906/162936122-4f7f326d-1a0c-485d-8840-3aa8756a0a38.png)

**Comment by Vincent-vst** [comment]
Thanks ! i was looking for a notion theme and this is perfect
