### ISSUE TITLE
RemNote App

### ISSUE THREAD

**Issue by Farhaduneci** [catppuccin/catppuccin#136]
**Are you available to help in the creation of this port?**
**Yes**, I would be glad to be a part of _catppuccin_ project.

**Additional context 📷**
RemNote is a note-taking/knowledge base application which is gaining popularity in recent days! RemNote combines recent research in neuroscience and psychology with cutting-edge web technology to build this knowledge management platform.

![image](https://user-images.githubusercontent.com/53964770/162968708-7be632ec-8820-423f-a174-7de27aa6ce01.png)
I use this platform and have found it super useful for me, I really like to have the nice-looking :star_struck: theme of _catppuccin_ on for this application.

:link: https://www.remnote.com/about

**Comment by justTOBBI** [comment]
So I just looked into this. They allow custom CSS styles which I will look into and create a port when finished :)
Also they forgot the documentation for custom css :/

**Comment by colderinit** [comment]
@justTOBBI I found this page for Custom CSS documentation if this issue is still relevant! 
https://plugins.remnote.com/custom-css

**Comment by justTOBBI** [comment]
Hey, thank you so much for pointing this out @colderinit. If you want to, I can upload my source code to a dev branch too, and you can continue my work on remnote. It shouldn't be much more to do, but a few tweaks here and there. But you decide. :D

**Comment by colderinit** [comment]
I'd be more than happy to give it my best effort, @justTOBBI !
I'm new to the catppuccin org, so I'll need to read up on the css from the repo. 
If this can etch something off your todo list, I'd be happy to make time for it! Happy Hacktoberfest too! :)

**Comment by andreasgrafen** [comment]
closed in favour of #1689
