### ISSUE TITLE
Wofi

### ISSUE THREAD

**Issue by RedsonBr140** [catppuccin/catppuccin#138]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
It's already done. https://github.com/RedsonBr140/wofi

**Comment by RedsonBr140** [comment]
...

**Comment by Pocco81** [comment]
Hello @RedsonBr140! pardon our delay. Your ports looks great overall. Might have to fix some things here and there but apart from that everything looks fine. Before your port gets moved into the org, would it be possible for you to update it to [current palettes](https://github.com/catppuccin/catppuccin/releases/tag/v0.2.0)?
