### ISSUE TITLE
Sumatra PDF

### ISSUE THREAD

**Issue by asrvd** [catppuccin/catppuccin#139]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Already done: https://github.com/asrvd/sumatra-pdf

**Comment by Pocco81** [comment]
Hello @RedsonBr140! pardon our delay. Your port looks great overall. Might have to fix some things here and there but apart from that everything looks fine. Before your port gets moved into the org, would it be possible for you to update it to [current palettes](https://github.com/catppuccin/catppuccin/releases/tag/v0.2.0)?

Thanks in advance!

**Comment by asheeeshh** [comment]
@Pocco81 i have updated the repo with new palettes, you can review it now.
