### ISSUE TITLE
Terminator terminal

### ISSUE THREAD

**Issue by ngowuys** [catppuccin/catppuccin#14]
I would like to use this beautiful color scheme on Terminator terminal.

**Comment by Rompicapo** [comment]
Later I will try to port it, but im a terminator nooby

**Comment by Rompicapo** [comment]
I did the port @Pocco81 
```
[[Catppuccin]]
    background_color = "#1E1E28"
    cursor_color = "#B3E1A3"
    foreground_color = "#d7dae0"
    palette = "#6e6c7c:#e28c8c:#b3e1a3:#eadda0:#a4b9ef:#c6aae8:#f0afe1:#d7dae0:#6e6c7c:#e28c8c:#b3e1a3:#eadda0:#a4b9ef:#c6aae8:#f0afe1:#d7dae0"
    background_image = None
```
1. add this to the "config" file located in "~/.config/terminator/config", under the word "[profiles]"
2. open terminator and right click on the screen and select the catppuccin profile
