### ISSUE TITLE
BetterDiscord

### ISSUE THREAD

**Issue by asheeeshh** [catppuccin/catppuccin#140]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Already done: https://github.com/asheeeshh/betterdiscord/

![image](https://user-images.githubusercontent.com/68690233/164371224-369f5431-4fa5-4707-a185-e3638617fd23.png)

**Comment by elkrien** [comment]
Isn't it done already?

https://github.com/catppuccin/discord

**Comment by asheeeshh** [comment]
oh, missed it, closing the issue
