### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by Aceticia** [catppuccin/catppuccin#141]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
It should be straight forward to create this port, as not much choices are involved.

**Comment by Pocco81** [comment]
Hey @Aceticia! I'm going to be closing this issue in favor of https://github.com/catppuccin/catppuccin/issues/166, because that one has had more conversations and some progress has been done.
