### ISSUE TITLE
Newsboat

### ISSUE THREAD

**Issue by ghost** [catppuccin/catppuccin#143]
Hi, I have started a newsboat theme, if anyone would like to check it out and possibly upstream it for inclusion once everyone is happy with it?

https://github.com/gregf/catppuccin-newsboat

![image](https://user-images.githubusercontent.com/980/164674640-fa1c248f-9d41-4644-9310-b5991c93cb1a.png)

![image](https://user-images.githubusercontent.com/980/164674731-736cc41f-f9eb-4e86-bb39-6b72cb263fb4.png)

**Comment by ignamartinoli** [comment]
Do you still have it? It looks lovely

**Comment by Pocco81** [comment]
Closing since OP deleted their account.

**Comment by ignamartinoli** [comment]
Oh so sad :'(
