### ISSUE TITLE
Oh My Zsh

### ISSUE THREAD

**Issue by Xenfo** [catppuccin/catppuccin#145]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Comment by Deathemonic** [comment]
You mean the powerlevel10k or the default omz promts

**Comment by Xenfo** [comment]
Powerlevel10k

**Comment by Deathemonic** [comment]
ahh 

> Powerlevel10k

ahh ok I'll try making one tomorrow

**Comment by Deathemonic** [comment]
also I don't think you need to change powerline10k all you need is xresources or a catppuccin themed terminal

**Comment by Xenfo** [comment]
Yeah I've done that but when I ssh into a machine with Termius then it's not themed anymore. Eg. phone to laptop

**Comment by Pocco81** [comment]
Closing because the port already exists: https://github.com/catppuccin/zsh-syntax-highlighting
