### ISSUE TITLE
spt

### ISSUE THREAD

**Issue by Sekki21956** [catppuccin/catppuccin#148]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Theme for Spotify-TUI.
Its done: https://github.com/Sekki21956/spt

**Comment by asheeeshh** [comment]
looks great :)

![image](https://user-images.githubusercontent.com/68690233/165687631-7877cc3d-3a1b-44ca-a55b-ed594c6af7fe.png)

**Comment by Sekki21956** [comment]
Updated the port to the new flavours :)

**Comment by Pocco81** [comment]
Hey @Sekki21956! I just sent you an invitation to join the org :) after accepting it you should be able to transfer the port you made at anytime. Thanks for contributing! :tada:
