### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by mryodo** [catppuccin/catppuccin#15]
Hi, guys! 

Thanks for all the work!
Wanted to share a quick Telegram MacOS port I've done (should work fine for bubble and minimal): https://t.me/addtheme/catppuccin_tmp
It is ugly, and off-putting, and this is the first theme I've ever done, sorry, please make it better if you know how
Maybe it will save somebody a couple of minutes of porting it...

**Comment by Pocco81** [comment]
Hey! thanks for helping out :)

For which Telegram version is this theme available? I got an error trying to install it on Desktop. Is it mobile only?

**Comment by mryodo** [comment]
Oops, sorry!
Right now the only naive macos client version is working on okay. I'll try to do the desktop today, sorry!

**Comment by mryodo** [comment]
> Oops, sorry!
> Right now the only naive macos client version is working on okay. I'll try to do the desktop today, sorry!

yeah, I hate this
Some kind of progress was maid, but I feel like `theme` documentation for telegram is (impressively) outdated in GitHub and I struggle to find the complete one

I'll update you when it is usable, right now it is meh

**Comment by Pocco81** [comment]
I'll try to help as well :)

**Comment by mryodo** [comment]
> I'll try to help as well :)

https://github.com/mryodo/tdesktop-catppuccin-esque-theme

Have a go!
Still needs profile colors debug (and probably some media related captions)

**Comment by andreasgrafen** [comment]
I'll also just leave this here: [https://github.com/andreasgrafen/Telegram](https://github.com/andreasgrafen/Telegram) c:

**Comment by andreasgrafen** [comment]
Update: The Desktop and Android themes are pretty much live at this point. If you wanna use them and maybe even give some Feedback feel free to do so! They are available through Telegram itself; more info can be found on the [Repo](https://github.com/catppuccin/telegram) ^—^

**Comment by Pocco81** [comment]
#43 resolved this.
