### ISSUE TITLE
Cider Music

### ISSUE THREAD

**Issue by d6stiny** [catppuccin/catppuccin#152]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

By the way, I've already created an **unofficial** port to it.
https://github.com/luvKxylah/CiderCatppuccin

**Comment by nekowinston** [comment]
I have a v0.2.0 port available here, looking to make it official this week: https://github.com/nekowinston/catppuccin-cider
I'd appreciate if people could give it a try!

**Comment by d6stiny** [comment]
Great! Closing this.

**Comment by rubyowo** [comment]
~~are you okay~~
you weren't supposed to close it yet btw, only when it gets added into the org.

**Comment by d6stiny** [comment]
Oops! My bad
