### ISSUE TITLE
Midnight Commander

### ISSUE THREAD

**Issue by BLucky-gh** [catppuccin/catppuccin#153]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
Add any other context or screenshots about the port request here.

By default Midnight Commander just uses terminal's colors, but with catpuccin for kitty `mc` is an unreadable bright blue mess with a lot of blue on blue text. Would be nice to have a theme ported for mc that colors it properly

**Comment by AdalZanabria** [comment]
Repo is up in [catppuccin/mc](https://github.com/catppuccin/mc)

**Comment by BLucky-gh** [comment]
Thanks, works great
