### ISSUE TITLE
OBS Studio

### ISSUE THREAD

**Issue by radstevee** [catppuccin/catppuccin#154]
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Comment by ignamartinoli** [comment]
Would be really nice

**Comment by Xurdejl** [comment]
I've created a port for this program using as a base one of the default themes called Acri.
https://github.com/Xurdejl/obs

**Comment by ignamartinoli** [comment]
Would you consider adding it as an official port? A guy recently helped me do it with **Newsboat**

(PS: as your profile picture a mix of Ib and Lein?)

**Comment by andreasgrafen** [comment]
Meanwhile I didn't even know OBS is themeable.. but **damn** I'm on love!
The port looks good on paper tho; one tiny question: Are the levels on the audiometer themed as well? I can't seem to see a difference between Mocha and Macchiato – but I might just be blind.

I'd take this for a test-drive later, but would love to make this an official Port asap. It really would be a great addition to the ever-growing list of awesomeness.

**Comment by Xurdejl** [comment]
> @Xurdejl Would you consider adding it as an official port? A guy recently helped me do it with **Newsboat**
> 
> (PS: as your profile picture a mix of Ib and Lein?)

Yes, I will.
IDK. It's some Lain art I found, and I liked.

---
@andreasgrafen 
> Are the levels on the audiometer themed as well?

Yes, they are. 
- [Mocha volume meter colours](https://github.com/Xurdejl/obs/blob/dec52e5b29d72861fdfd8eac09499a0aa460416d/themes/Catppuccin%20Mocha.qss#L924-L926) 
- [Macchiato volume meter colours](https://github.com/Xurdejl/obs/blob/dec52e5b29d72861fdfd8eac09499a0aa460416d/themes/Catppuccin%20Macchiato.qss#L924-L926)

Should I transfer it now?

**Comment by andreasgrafen** [comment]
I can't see any reason against this; feel free to go ahead. ^—^

**Comment by Xurdejl** [comment]
Moved to https://github.com/catppuccin/obs.

**Comment by ignamartinoli** [comment]
@Xurdejl thanks man, love this
