### ISSUE TITLE
Dunst

### ISSUE THREAD

**Issue by WooxHimself** [catppuccin/catppuccin#156]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
I already made this :D 
https://github.com/WooxHimself/dunstppuccin

![image](https://user-images.githubusercontent.com/76164598/169685030-43b89c09-61ae-4018-b3fa-2cc08736685f.png)
![image](https://user-images.githubusercontent.com/76164598/169685041-6f8bb581-b1eb-4592-b68f-17cf95f01b67.png)

**Comment by elkrien** [comment]
https://github.com/catppuccin/dunst ??

**Comment by WooxHimself** [comment]
> https://github.com/catppuccin/dunst ??

oh god. i didn't noticed lmao
