### ISSUE TITLE
Offer an "OG" Variant

### ISSUE THREAD

**Issue by ZenithDS** [catppuccin/catppuccin#157]
The new color variants are lovely and I appreciate all the work and effort that went into making them a reality. I've been using catppuccin for a very long time and I've absolutely fallen in love with how at home the theme feels. 

With that said, I don't think the new variants capture the same feeling and I think it would be nice to have "OG" variant with all the colors from a month or so ago. 

I'd be more than happy to contribute if need be!!

**Comment by antekmeco** [comment]
i have the same issue i just want the normal colors from yesterday

**Comment by Pocco81** [comment]
The normal colors from "yesterday" are still here, but they are now called Mocha:

![image](https://user-images.githubusercontent.com/58336662/170525130-6fe20010-a865-41b5-a6a6-f65b616c12d4.png)

It literally (almost the same). They just slightly changed, that's all :) (I can provide a side by side comparison if needed)

**Comment by Pocco81** [comment]
@ZenithDS 

![image](https://user-images.githubusercontent.com/58336662/170528618-83f090c5-4385-4848-9074-9ace7f1c9cd1.png)

Just to clarify, I didn't edit the monochromatic colors since the same background color was kept (`#1E1E2E`). I thought it was just to iconic to be changed :)

**Comment by ZenithDS** [comment]
Agreed on the background color being too iconic to be changed :) More pigment is probably a better description than anything I was trying to come up with to describe the changes lol. I can appreciate accommodating visually impaired individuals, I can get used to new colors if it means my favorite color scheme is now more accessible!! 

With that said, I do still think the new text color leans a little too heavily towards gray/silver than it does towards "white". My knowledge on colors is very limited but the older "white" for text looks better in most cases and I think there's merit in sticking to that color for text.

Regardless, I appreciate the sanity check and thank you for continuing to improve our beloved color scheme :)

**Comment by Pocco81** [comment]
To be honest the choice for the text was influenced by the idea of having something more "pastel". What's more pastel than lavender? I simply mixed lavender with the old text color and got the current one. Yes, the original text color is more visible, but that's because it's literally white, however the contrast ratio is very similar:

New text color:
![image](https://user-images.githubusercontent.com/58336662/170536395-9d35df70-9916-4cc7-be97-b242c813ab6f.png)

Old text color:
![image](https://user-images.githubusercontent.com/58336662/170536494-48f45f95-5fb3-4837-a127-069d99456a05.png)

**Comment by ZenithDS** [comment]
Do you think it's reasonable to aim for a balance between the two? I like the idea of making it more pastel but I do think it strays away a little too much from what text has traditionally looked like. Shifting the current text color towards more of a white and less of a lavender might be something to consider.

**Comment by Pocco81** [comment]
So, this?

![image](https://user-images.githubusercontent.com/58336662/170602900-f3204db3-67ed-4ddf-b8d7-84ca050c209e.png)

Looks good:

![image](https://user-images.githubusercontent.com/58336662/170603284-f8722b72-fe07-4f09-a188-93639310e649.png)

**Comment by ZenithDS** [comment]
Just tried it out in my config and it feels much more at home with the rest of the catppuccin colors!! The current text color almost takes away from the rest of the colors, whereas this proposed change lets all of the other beautiful colors come through really nicely as well! 

Again, your knowledge on colors far exceeds mine so use your best judgement! but I think the proposed text color would look great!

**Comment by elkrien** [comment]
My feeling about the WHITE color was similar at the beginning but after few days I don't want to change it. It looks and feels great when You get used to it. I'm using new palettes for a while thx to dev branch of NeoVim plug-in. Give it a try ...

**Comment by Pocco81** [comment]
**Alakazam**! @ZenithDS your wish has been granted:

![image](https://user-images.githubusercontent.com/58336662/170848207-bf505531-2d98-4543-9dc5-4f11d7cf9cec.png)

> Screenshot from the `#announcements` channel at our Discord server.

**Comment by ZenithDS** [comment]
Thank you for all the work!! Truly love to see it :)
