### ISSUE TITLE
Vim

### ISSUE THREAD

**Issue by VentGrey** [catppuccin/catppuccin#16]
I'm aware that a neovim theme exists and it is written in Lua. Sadly it doesn't work well with vim8 or older neovim versions (like the one in Debian) . It would be awesome to enjoy this beautiful palette in oldie editors :smile: 

I'm no expert on vimscript but if I can help maintainers in any way, please let me know! Id be glad to :)

**Comment by Rompicapo** [comment]
I also had this port in mind, I can do it, if you want to help you can join the discord group

**Comment by andreasgrafen** [comment]
https://github.com/catppuccin/vim
