### ISSUE TITLE
Blink Shell

### ISSUE THREAD

**Issue by rithikasilva** [catppuccin/catppuccin#163]
**Are you available to help in the creation of this port? 😄 (optional)**
I have already made the .js file for the theme. It follows the same styling as the windows terminal theme. 

**Additional context 📷 (optional)**
Add any other context or screenshots about the port request here.

**Comment by rithikasilva** [comment]
A version for each palette has been made and can be currently found here: https://github.com/rithikasilva/blink. The main image still needs to be updated with images of what the themes look like.

**Comment by rithikasilva** [comment]
Image has been added!

https://github.com/rithikasilva/blink

I think everything that needs to be added is done. The stars, issues, and contributors are linked to the current repo. I am unsure what happens if ownership is transferred. If the changes to the location aren't made on their own, the links in the README.md would need to be updated to reflect the updated repo location.

Any feedback is appreciated :)

**Comment by andreasgrafen** [comment]
Looking good! The Readme doesn't get updated automatically, but that's an easy fix once the repo is transfered. c:

I don't think you're part of the org yet, right? So @Pocco81 would need to invite you first. Once done everything should be rather easy to do. ^—^

**Comment by Pocco81** [comment]
Hey @rithikasilva! I just sent you an invitation to join the org :) after accepting it you should be able to transfer the port you made at anytime. Thanks for contributing! :tada:
