### ISSUE TITLE
Delaying the addition of old port requests after the release of v0.2.0

### ISSUE THREAD

**Issue by Pocco81** [catppuccin/catppuccin#164]
Given the release of Ctp v0.2.0, old port requests won't be added to the org until they get converted to at least one of the new flavours (because the rest can be generated using the utilities in our [toolbox](https://github.com/catppuccin/toolbox)).

Currently all ports that are already inside of the org are being converted: https://github.com/orgs/catppuccin/projects/2#column-18800455

**Comment by sgoudham** [comment]
All existing ports are ported to v0.2.0 :tada: :tada: and we can now focus on existing issues/port requests.
