### ISSUE TITLE
Zutty

### ISSUE THREAD

**Issue by sakkke** [catppuccin/catppuccin#165]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
It is done: https://github.com/sakkke/catppuccin-zutty
![screenshot](https://user-images.githubusercontent.com/84666033/172053895-9eedba24-1ca1-4957-82bd-05849d5e8bc3.png)

Zutty (_Zero-cost Unicode Teletype_) is a terminal emulator for the X Window System.
Repo: https://github.com/tomszilagyi/zutty

**Comment by Pocco81** [comment]
Hey @sakkke ! I just sent you an invitation to join the org :) after accepting it you should be able to transfer the port you made at anytime. Thanks for contributing! :tada:

**Comment by sakkke** [comment]
Thank you for inviting me! Sorry, I just came in, may I ask you to change the name of the repo from `catppuccin-zutty` to `zutty`? I join org for the first time, I thought that I can rename the repo 😂

**Comment by Pocco81** [comment]
Don't worry! I just changed it for you :)
