### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by uShldGetCeleste** [catppuccin/catppuccin#166]
**Are you available to help in the creation of this port? 😄**
Yes. I have already completed them

**Additional context 📷**
Slack sadly doesn't allow coloring the main window with all the text and you can only choose between a light and dark mode. It's probably possible to do something with stylus, but you wouldn't be able to apply it on the desktop app :(

The second colour in every theme I've made is always #F8F8FA, and I'm not sure why. As far as I can tell, it isn't used in themes, though I may be wrong.

**Themes 🎨**
### latte
```
#EFF1F5,#F8F8FA,#40A02B,#EFF1F5,#DCE0E8,#4C4F69,#40A02B,#E64553,#EFF1F5,#4C4F69
```
![image](https://user-images.githubusercontent.com/68669265/172416152-fb1bcad7-cd2a-4c9f-adc9-8c586d2f8c8a.png)

### frappe
```
#303446,#F8F8FA,#A6D189,#303446,#232634,#C6D0F5,#A6D189,#EA999C,#303446,#C6D0F5
```
![image](https://user-images.githubusercontent.com/68669265/172416598-ba180147-5df8-42ea-b665-d4f7f56a8924.png)

### macchiato
```
#24273A,#F8F8FA,#A6DA95,#24273A,#181926,#CAD3F5,#A6DA95,#EE99A0,#24273A,#CAD3F5
```
![image](https://user-images.githubusercontent.com/68669265/172416748-817aae96-53ab-4c3f-a69f-b4b5912cbff5.png)

### mocha
```
#1E1E2E,#F8F8FA,#A6E3A1,#1E1E2E,#11111B,#CDD6F4,#A6E3A1,#EBA0AC,#1E1E2E,#CDD6F4
```
![image](https://user-images.githubusercontent.com/68669265/172416908-3542a098-f5bd-4f5a-9be1-7bbf1cdca3e5.png)

**Comment by TGRush** [comment]
check [this](https://slack.com/help/articles/205166337-Change-your-Slack-theme) out

**Comment by uShldGetCeleste** [comment]
why?

**Comment by uShldGetCeleste** [comment]
yeah but what's there? I don't understand what you want me to get from that page..

**Comment by sph3** [comment]
I think it's for people who don't know how to apply themes to slack :)

**Comment by TGRush** [comment]
> yeah but what's there? I don't understand what you want me to get from that page..

we can theme slack natively, on the web we'd also be able to use Stylus, and extensions can be loaded into Electron too (with some work), so technically we can make it work on the Desktop app

**Comment by nekowinston** [comment]
@uShldGetCeleste, is it alright with you if I take your themes and prepare a separate repository with them?

It would be easier to discover as a port, and we can add setup instructions there. I'll credit you appropriately, of course.

**Comment by guivazcabral** [comment]
just found this and gave mocha try since it's what i use everywhere. ended up customising to 
`#11111B,#F8F8FA,#6C7086,#CDD6F4,#181825,#CDD6F4,#6C7086,#EBA0AC,#11111B,#CDD6F4`

**Comment by kaiserbrito** [comment]
> just found this and gave mocha try since it's what i use everywhere. ended up customising to `#11111B,#F8F8FA,#6C7086,#CDD6F4,#181825,#CDD6F4,#6C7086,#EBA0AC,#11111B,#CDD6F4`

Wow!! Thank you so much for that, I'm using, and it's amazing!!!

**Comment by nekowinston** [comment]
> @uShldGetCeleste, is it alright with you if I take your themes and prepare a separate repository with them?
> 
> It would be easier to discover as a port, and we can add setup instructions there. I'll credit you appropriately, of course.

I didn't get notified about the thumbs-up reaction on this comment, I'll create a Repo soon, thank you!

I'll also make a repository for Mattermost, since this is the Software I'm using at work.

**Comment by nekowinston** [comment]
Repository is up at https://github.com/catppuccin/slack

I went with the values in @uShldGetCeleste's original post, please let me know if you'd like to change how you're credited!
