### ISSUE TITLE
Minecraft

### ISSUE THREAD

**Issue by Aurn1ox** [catppuccin/catppuccin#1682]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
A Minecraft resource pack based on the catppuccin colors for 1.13+. 
Repository: https://github.com/Aurn1ox/minecraft

**Comment by andreasgrafen** [comment]
As mentioned over on Discord; I love this and I'm all for moving it to the org to make sure as many people as possible can see it. <3
