### ISSUE TITLE
Documentation: Improve the listing of ports on the readme

### ISSUE THREAD

**Issue by andreasgrafen** [catppuccin/catppuccin#1685]
Our list of ports got *quite extensive*. This is great news, but it comes with a slight caveat: Listing all the ports within the [main repositories readme](https://github.com/catppuccin/catppuccin#-ports-and-more) turned into a somewhat ugly list.

We'd love to style the port listing in a way that is visually more inviting, without sacrificing usability – i.e. searchability. This prevents us from using something like Github Reade Stats, because while it looks great, it's preventing the ports name from being searchable.

![Catppuccin](https://github-readme-stats.vercel.app/api/pin/?username=catppuccin&repo=catppuccin&title_color=C9CBFF&text_color=cad3f5&icon_color=cad3f5&bg_color=181926&hide_border=true)

Another idea we've explored are tables. While they are great for desktop users, they cause trouble on mobile devices.. 

<img src="https://cdn.discordapp.com/attachments/1000466646990860390/1024342729033011210/unknown.png" width="400px">

We're calling on all creative minds out there to come up with something beautiful. We're sure that it can be done, we can't think of it. Any help is highly appreciated. <3

**Comment by nekowinston** [comment]
@andreasgrafen can we consider this issue closed, after having merged #1695?

**Comment by andreasgrafen** [comment]
@nekowinston I've left it open because I'm still hoping that some super smart person comes around that knows some table magic or another solution that would result in a cleaner list. The changes made are great, but they only barely tackle the main issue of the list being insanely long, no? o:

**Comment by nekowinston** [comment]
Sure thing! Just checked because the PR linked here.

**Comment by EphemeralDev** [comment]
A bit of a workaround but has a static site generator been considered? Instead of listing all the ports, maybe list the more notable ones and point people to the site. It can be built using github actions and deployed using github pages. This would probably be more mobile friendly. You can see some  [themes for hugo here](https://themes.gohugo.io/) or [themes for zola here](https://www.getzola.org/themes/). I think it would make browsing wallpapers better as well.

**Comment by nekowinston** [comment]
> A bit of a workaround but has a static site generator been considered?

A website is in the works doing exactly that, plus allowing filtering for operating system, sorting by stars, etc.
This issue really only concerns the GitHub README itself - we want the theme/org to be browsable on GitHub as well :)

**Comment by nekowinston** [comment]
Since the end goal is having the content of the README in a more easily parsable format, I think it'd be better to close this issue and track it in https://github.com/catppuccin/website/issues/18.
