### ISSUE TITLE
DrRacket

### ISSUE THREAD

**Issue by PanAeon** [catppuccin/catppuccin#1686]
My attempt: [PanAeon/drracket-catppuccin](https://github.com/PanAeon/drracket-catppuccin)

**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Comment by nekowinston** [comment]
Hi there 👋 

Thanks for your work - sorry for the slow response, I'll check it out in the coming days.

The repository itself seems on point, everything's there: licence, description, etc. I'll just have to give it a try, then we can happily transfer it 🙂

**Comment by nekowinston** [comment]
@PanAeon 
Sorry for taking a while to get to this, finally had a chance to check it out for myself.

Listing a few issues I found here:

![image](https://user-images.githubusercontent.com/79978224/200683319-661094a7-e932-47d0-baa6-b656f5d35f2e.png)

The current line doesn't have good contrast, it's hard to read. The green also doesn't really fit catppuccin, at least here in Mocha.

![image](https://user-images.githubusercontent.com/79978224/200683600-7d1d1932-ce93-4fce-b3f1-683c1cbfe590.png)
Current bracket pair highlights make the whole selection unreadable, it would be great if we could use transparency here, preferably with `surface2`, with about 15-20% opacity.

Those were just two issues that instantly jumped out to me, would appreciate if we could get those fixed before moving it over to the org.

Thanks for your work so far, installation was smooth, base looks solid!

**Comment by PanAeon** [comment]
@nekowinston 
Hi, sorry for a such long delay. I've attempted to fix above issues:
- current line number clashes with the platform (GTK) theme highlight, can't do much about it.
- Replaced green identifier highlight with proper ones. Still looks a bit off, but not as annoying
- Fixed current bracket highlight
![swappy-20230205-121122](https://user-images.githubusercontent.com/686076/216813270-69b04eaf-5a20-4623-8854-cde45ffcb3e2.png)
![swappy-20230205-121209](https://user-images.githubusercontent.com/686076/216813274-a1e96c2c-89b8-48bf-a28e-70093be5b4b4.png)

**Comment by nekowinston** [comment]
Hey @PanAeon, no worries for taking a while, I took some time to review it as well, after all. 😄 

Glad that the issues impacting readability got fixed, that improves it enough that we can move it over to the org.
I've sent you an invite, feel free to transfer it whenever you have the time. Thanks for your work again 🙂
