### ISSUE TITLE
Nova

### ISSUE THREAD

**Issue by daveyholler** [catppuccin/catppuccin#1691]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes https://github.com/daveyholler/Catppuccin-Nova

Port for Panic's [Nova editor](https://nova.app)

**Comment by nekowinston** [comment]
Hey there, thanks for wanting to help out with Nova! It's actually our 2nd oldest open issue: https://github.com/catppuccin/catppuccin/issues/48

Would you mind tracking it there?

**Comment by daveyholler** [comment]
For sure. I'll comment over there. I created an unofficial port that's in the [Nova extension library](https://extensions.panic.com/extensions/holler/holler.CatppuccinTheme/)
