### ISSUE TITLE
Glamour

### ISSUE THREAD

**Issue by Dukeatron** [catppuccin/catppuccin#1694]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
https://github.com/Dukeatron/glamour/
Repo link

**Comment by andreasgrafen** [comment]
Looking good! The screenshot is a bit empty … maybe it could be an example with a little bit more going on? Currently almost everything is just happening within the latte part of the image wich is a little sad. :c

**Comment by Dukeatron** [comment]
Will be working on that

**Comment by jolheiser** [comment]
This issue can probably be closed https://github.com/catppuccin/glamour 🥳

**Comment by Dukeatron** [comment]
Still a WIP
