### ISSUE TITLE
Signal Desktop

### ISSUE THREAD

**Issue by Kettukaa** [catppuccin/catppuccin#1703]
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Additional context 📷 (optional)**
Here is the relevant repo https://github.com/signalapp/Signal-Desktop
I'm not 100%  if there will ever be any custom theme support, but maybe someone knows a work around? It is a desktop wrapper of a web app, so perhaps there is a way to inject a stylesheet? 

I found two relevant issues ( [1](https://github.com/signalapp/Signal-Desktop/issues/2213#issuecomment-378707597) [2](https://github.com/signalapp/Signal-Desktop/issues/4296) ) on the topic that suggests there may not be ever explicit support for custom themes, but neither does discord and [people figured that one out](https://github.com/mlvzk/discocss) ¯\\_ (ツ)_/¯

**Comment by ghostx31** [comment]
This is definitely going to be a difficult task. 
The Signal desktop app is an electron app. I did find one repository [here](https://github.com/CapnSparrow/signal-desktop-themes) but when you go through the README, you would realise its a complicated process and not really a great experience for the end user. Additionally, updates to the desktop app would surely break stuff and we'd need to re-apply a theme after every update.

**Comment by nekowinston** [comment]
Closing this as not planned. Happy to reconsider, should upstream become more theme-friendly.
