### ISSUE TITLE
Prism Launcher Port (https://prismlauncher.org/)

### ISSUE THREAD

**Issue by Mqisty** [catppuccin/catppuccin#1704]
**Are you available to help in the creation of this port?**
Theme already done.

**Additional context**
I can transfer it to Catppuccin/Minecraft or make a new repo whichever would be preferable 
https://github.com/mqisty/prismlauncher

**Comment by sgoudham** [comment]
Hey there!

Could you please update the issue to be in line with the following issue template? Thanks!

```markdown
**Are you available to help in the creation of this port? 😄 (optional)**
Yes/No/Maybe

**Additional context 📷 (optional)**
Add any other context or screenshots about the port request here.
```

**Comment by nekowinston** [comment]
Sorry for taking a while to get to this.

I'd like to transfer this now as a separate repository, no need to integrate this into the Minecraft port.

I've sent you an invitation, feel free to transfer it anytime.

**Comment by nekowinston** [comment]
apparently deleted and re-created at https://github.com/catppuccin/prismlauncher
