### ISSUE TITLE
Dmenu

### ISSUE THREAD

**Issue by GoodBoyNeon** [catppuccin/catppuccin#1710]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes!

**Additional context 📷 (optional)**
It won't be a lot of work as we dmenu being just a bar, changing 3-4 colors should be enough!

**Comment by tsjazil** [comment]
Yes
I would like to contribute in the dmenu port

**Comment by Spaxly** [comment]
I shall take a look into this asap.

**Comment by Spaxly** [comment]
https://github.com/Spaxly/Catppuccin-dmenu

Alpha port
