### ISSUE TITLE
VHS

### ISSUE THREAD

**Issue by jolheiser** [catppuccin/catppuccin#1711]
**Are you available to help in the creation of this port?**
Yes
https://gist.github.com/jolheiser/2721bac5a1452cc5724b924346bdc5aa

**Additional context 📷**
Will need to wait for a PR and subsequent merge that resolves https://github.com/charmbracelet/vhs/issues/78

**Comment by caarlos0** [comment]
PSA: I'll work on the theme feature on VHS

**Comment by caarlos0** [comment]
merged!
