### ISSUE TITLE
Gitui

### ISSUE THREAD

**Issue by BlueFalconHD** [catppuccin/catppuccin#1714]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
hehe :shipit: another commit streak starting right now. my master plan is finally coming to light. First this, then typora then...

anyways, https://github.com/bluefalconhd/gitui

**Comment by isabelincorp** [comment]
Testing it out, it seems the README needs to some work in the instructions, as the theme directory being copied is plural in the command you listed.

**Comment by BlueFalconHD** [comment]
ah ok
