### ISSUE TITLE
qt5ct

### ISSUE THREAD

**Issue by Syndrizzle** [catppuccin/catppuccin#1716]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
https://github.com/Syndrizzle/qt5ct

![res 1](https://user-images.githubusercontent.com/96112833/199716643-c31274df-d5b6-47e0-8532-a0d8fe16d231.png)
![rick_astley](https://media4.giphy.com/media/3owzW56w5vKVom0I2Q/giphy.gif)

**Comment by nekowinston** [comment]
Thanks for your work. 😀

I've sent you an invitation to the org, feel free to transfer it.
