### ISSUE TITLE
Startpage

### ISSUE THREAD

**Issue by bartlibert** [catppuccin/catppuccin#1717]
Port for [startpage](https://startpage.com)

**Are you available to help in the creation of this port? **
Yes

**Additional context 📷 **
I have already created a port in my own namespace: [https://github.com/bartlibert/startpage](https://github.com/bartlibert/startpage).
I don't know exactly how to get it under the `catpuccin` organization, any help would be appreciated.

**Comment by nekowinston** [comment]
Hi there :wave:

Thanks for your work, the repo looks good!

>  don't know exactly how to get it under the catpuccin organization, any help would be appreciated.

I've sent you an invite to the org, once you're a member, you can go to your Repository > Settings > Transfer Ownership > `catppuccin`.
