### ISSUE TITLE
Binary Ninja

### ISSUE THREAD

**Issue by kkrypt0nn** [catppuccin/catppuccin#1722]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Comment by kkrypt0nn** [comment]
These are the results I got for the first test:

<details>
<summary>🌻 Latte</summary>
<img src="https://user-images.githubusercontent.com/43011723/200046309-eeeb60fb-e6e5-4635-a794-914b3cb8b228.png" />
</details>

<details>
<summary>🪴 Frappé</summary>
<img src="https://user-images.githubusercontent.com/43011723/200046476-ac84195b-f556-4f6e-af35-3fde812572e6.png" />
</details>

<details>
<summary>🌺 Macchiato</summary>
<img src="https://user-images.githubusercontent.com/43011723/200046589-d529d6fd-b13e-40d7-880a-3f898c4d9b8d.png" />
</details>

<details>
<summary>🌿 Mocha</summary>
<img src="https://user-images.githubusercontent.com/43011723/200046706-a9f5d71f-2dc6-461e-88cb-fda1a3e33ffe.png" />
</details>

**Comment by kkrypt0nn** [comment]
Made some changes and published the repository at https://github.com/kkrypt0nn/binja

**Comment by nekowinston** [comment]
Hi there!

Thanks for both your ports, this one and #1724 – I'd like to respond to both here if that's alright.

I checked both of them out yesterday, they're great! I'm a bit unsure how our style guide would apply to both programs, since they're a bit niche, but the ports seem to be well thought through. 🙂 

Only a minor issue: How common is the repo name abbreviation (`binja`)? I simply know too little about this space.

**Comment by kkrypt0nn** [comment]
Hoi hoi,

Thanks for the reply for both of the ports!

Regarding the `binja` shortcut, looking at some Discord servers, Slack workspaces and online we sort of use `binja` more than the longer `binary ninja`, probably out of laziness.

Some examples are Google's plugin to support [Hexagon CPUs](https://github.com/google/binja-hexagon) or some other [plugin](https://github.com/hugsy/gef-binja).
Using a quick search on a Discord server there seem to have twice as much mentions of `binja` rather than `binary ninja`.

It is true that newcomers may not know that shortcut though, so if you wish I'd gladly rename it to `binary-ninja` for better clarity.

**Comment by nekowinston** [comment]
I'd like to rename it to `binary-ninja` then, we can use `binja` in the labels, so it should still be discoverable via both keywords then.

The coolest thing about color schemes that have been ported nearly everywhere, is that I always learn about new software when looking at available ports. 🙂 
I think `binary-ninja` serves that purpose better than `binja`.

Feel free to transfer this one as well then. 👍

**Comment by kkrypt0nn** [comment]
For sure, will do! Can also confirm that I've discovered lots of new softwares, websites, etc. by looking at some repositories ✨
