### ISSUE TITLE
Cutter

### ISSUE THREAD

**Issue by kkrypt0nn** [catppuccin/catppuccin#1724]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes -> https://github.com/kkrypt0nn/cutter

**Additional context 📷 (optional)**
This application is special and from what I've seen you can only change the background of the disassembler, graph view, etc. but cannot change the kind of grayish window colors; only the backgrounds.

**Comment by nekowinston** [comment]
Hi there 👋 

Left you a comment on https://github.com/catppuccin/catppuccin/issues/1722#issuecomment-1308213399.
I've sent you an invite to the org, feel free to transfer this one.

**Comment by kkrypt0nn** [comment]
Transferred it to https://github.com/catppuccin/cutter
