### ISSUE TITLE
CRT

### ISSUE THREAD

**Issue by iruzo** [catppuccin/catppuccin#1726]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**

- What is [CRT](https://github.com/Swordfish90/cool-retro-term)
- [Port current repo](https://github.com/iruzo/catppuccin-crt)
- This terminal emulator let you modify only font and bg color. But it has a lot of effects.

**Comment by nekowinston** [comment]
Thanks for your port! Sadly it seems that we really can't do much other than setting the background and foreground colors.

I also tried to set the colors via base16-shell, but it didn't seem to work. Guess we'll have to settle for those 2 colors.

The repo is still missing an emoji in the description, as well as some labels. I'll send you an invite to the org, please feel free to transfer once those are set.
