### ISSUE TITLE
wikiwand

### ISSUE THREAD

**Issue by Tnixc** [catppuccin/catppuccin#1732]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes, it's done

**Additional context 📷 (optional)**
Add any other context or screenshots about the port request here.

![image](https://user-images.githubusercontent.com/85466117/201460190-50d41f21-15cb-4a65-9972-0f2be14b7cda.png)

(as per request of NameExists#3898)

**Comment by Tnixc** [comment]
https://github.com/Tnixc/wikiwand/

**Comment by Tnixc** [comment]
@nekowinston Please fix the description and add tags on https://github.com/catppuccin/wikiwand because I forgor. Also use the 🤓 emoji thank you

**Comment by nekowinston** [comment]
> @nekowinston Please fix the description and add tags on https://github.com/catppuccin/wikiwand because I forgot to add them before transferring. Also use the nerd_face emoji thank you

Done! Also updated your permissions.
