### ISSUE TITLE
bemenu

### ISSUE THREAD

**Issue by iruzo** [catppuccin/catppuccin#1735]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
- What is [bemenu](https://github.com/Cloudef/bemenu)
- [Port current repo](https://github.com/iruzo/bemenu)

**Comment by isabelincorp** [comment]
Looks good! Add an emoji at the start of the description and some tags (Use other repositories for reference) then feel free to transfer this to the main org!

**Comment by iruzo** [comment]
Done, this is the url:

https://github.com/catppuccin/bemenu

Thanks !

**Comment by isabelincorp** [comment]
No Problem!
