### ISSUE TITLE
Plymouth

### ISSUE THREAD

**Issue by ndsboy** [catppuccin/catppuccin#1737]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
I have created a preview repository here: https://github.com/ndsboy/plymouth

**Comment by nekowinston** [comment]
Thanks for your work on this - I'll take a detailed look at this tomorrow.

**Comment by yavko** [comment]
I took a look, and in the mocha theme, the name is macchiato, just wanted to note

**Comment by ndsboy** [comment]
@yavko thanks, fixed it, I guess double checking is sometimes not enough :)

**Comment by nekowinston** [comment]
> Thanks for your work on this - I'll take a detailed look at this tomorrow.

I finally had a chance to check the port request out, sorry for the delay. The file structure & repo seem alright, i've sent you an invite to the org. Feel free to transfer it 🙂
