### ISSUE TITLE
HexChat

### ISSUE THREAD

**Issue by aszecsei** [catppuccin/catppuccin#1742]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes - I have a working draft [here](https://github.com/aszecsei/hexchat)

**Additional context 📷 (optional)**
[HexChat](https://hexchat.github.io/) is a cross-platform IRC client.

**Comment by nekowinston** [comment]
Thanks for your work on this port, looks great!

I've sent you an invite to the org, feel free to transfer it. 🙂
