### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by fapfaff** [catppuccin/catppuccin#1743]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
I have created a [repository](https://github.com/fapfaff/HA-Catppuccin-Theme)

**Comment by nekowinston** [comment]
Awesome! Thanks for your work on this, I've finally had a look and everything seems alright :)

I've sent you an invite to the org, feel free to transfer it over anytime.
