### ISSUE TITLE
SolveSpace

### ISSUE THREAD

**Issue by ndsboy** [catppuccin/catppuccin#1746]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
I have created a [preview repository](https://github.com/ndsboy/solvespace)

**Comment by nekowinston** [comment]
Hi there, sorry for totally missing this one! Awesome work, this looks ready to be transferred over.

**Comment by ndsboy** [comment]
Hi @nekowinston, no worries, it's not that urgent :smile:
