### ISSUE TITLE
LXTerminal

### ISSUE THREAD

**Issue by prateektade** [catppuccin/catppuccin#1747]
**Are you available to help in the creation of this port? 😄 (optional)**
**Yes**/~~No~~/~~Maybe~~

**Additional context 📷 (optional)**
Created a repository [here](https://github.com/prateektade/catppuccin-lxterminal).

**Comment by nekowinston** [comment]
I've finally had time to check this out - thanks for your port! I've invited you to the org, feel free to transfer it whenever you have the time.

**Comment by prateektade** [comment]
Thank you! I have transferred the repository to [catppuccin/lxterminal](https://github.com/catppuccin/lxterminal).
