### ISSUE TITLE
ggplot2

### ISSUE THREAD

**Issue by albert-ying** [catppuccin/catppuccin#1749]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**

https://github.com/albert-ying/catppuccin

**Comment by backwardspy** [comment]
i am going to close this issue due to inactivity.

the port looks *fantastic* and we would love to include it in the org, so if you or anyone else would like to pick this up and apply justTOBBI's suggestions above please do let us know and we'll reopen this. thanks!
