### ISSUE TITLE
Heroic

### ISSUE THREAD

**Issue by skinatro** [catppuccin/catppuccin#1752]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe ( I dont know CSS but I can help if someone needs it)

**Additional context 📷 (optional)**
[Heroic](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher) recently added themeing support.
You can check out the docs [here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/wiki/Custom-Themes)

**Comment by ndsboy** [comment]
Hi there, I have created a [draft](https://github.com/ndsboy/heroic) for you to try out. I'd appreciate your feedback.

**Comment by backwardspy** [comment]
hey @ndsboy thanks for your work on the port! i've just installed it and it looks great. i've only got one minor suggestion and that's just to consider updating the README to mention that you must point Heroic to the `themes/` folder within the repo. it's obvious in hindsight, but i admit i made the mistake of just passing it the repo dir on my first attempt. :)

other than that i'm happy for this to be transferred over. it looks like you are already a member of the org, so go ahead and update the various links (badges etc) in the README and then transfer the repo whenever you're ready!

**Comment by nekowinston** [comment]
I've also had a chance to check this out, agreeing with @backwardspy that this is ready to be moved over.

**Comment by ndsboy** [comment]
Sorry for the delayed answer, I am currently on vacation. I will move the repository in about two weeks.

**Comment by nekowinston** [comment]
No worries, enjoy your time off :sunglasses:

Thanks for letting us know!
