### ISSUE TITLE
QTerminal

### ISSUE THREAD

**Issue by prateektade** [catppuccin/catppuccin#1753]
**Are you available to help in the creation of this port? 😄 (optional)**
**Yes**/~~No~~/~~Maybe~~

**Additional context 📷 (optional)**
[QTerminal](https://github.com/lxqt/qterminal) is the default terminal emulator for the LXQt desktop environment.
I have already created a repository [here](https://github.com/prateektade/catppuccin-qterminal).

**Comment by nekowinston** [comment]
Similar to #1747, this is ready for transfer. Thanks for your work here too :)

**Comment by prateektade** [comment]
Thank you! The repository has been transferred to [catppuccin/qterminal](https://github.com/catppuccin/qterminal).
