### ISSUE TITLE
GitHub Readme Tech Stack

### ISSUE THREAD

**Issue by sakkke** [catppuccin/catppuccin#1754]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
### `catppuccin_latte`
![localhost_8080_api_cards_theme=catppuccin_latte lineCount=1 line1=node js,node js,539E43;typescript,typescript,2D79C7;express,express js,61DAFB](https://user-images.githubusercontent.com/84666033/205633053-95963bb1-08f8-4e6d-a15b-042a47193abe.png)

### `catppuccin_frappe`
![localhost_8080_api_cards_theme=catppuccin_frappe lineCount=1 line1=node js,node js,539E43;typescript,typescript,2D79C7;express,express js,61DAFB](https://user-images.githubusercontent.com/84666033/205633376-f81a7deb-1aef-46c2-878f-b55b6e015799.png)

### `catppuccin_macchiato`
![localhost_8080_api_cards_theme=catppuccin_macchiato lineCount=1 line1=node js,node js,539E43;typescript,typescript,2D79C7;express,express js,61DAFB](https://user-images.githubusercontent.com/84666033/205633394-47630c95-b3fd-4111-bbef-e3de797f11cc.png)

### `catppuccin_mocha`
![localhost_8080_api_cards_theme=catppuccin_mocha lineCount=1 line1=node js,node js,539E43;typescript,typescript,2D79C7;express,express js,61DAFB](https://user-images.githubusercontent.com/84666033/205633411-57055a6d-2c73-473b-9de3-b6c1863d035b.png)

URL: https://github.com/0l1v3rr/github-readme-tech-stack

I've created themes on upstream. I'm waiting 0l1v3rr/github-readme-tech-stack#14 to be merged.

**Comment by sakkke** [comment]
Repo creation is done: https://github.com/sakkke/catppuccin-github-readme-tech-stack

**Comment by nekowinston** [comment]
Seems great, feel free to transfer it!

**Comment by sakkke** [comment]
Transferred! Thanks 😄

https://github.com/catppuccin/github-readme-tech-stack
