### ISSUE TITLE
Vivaldi

### ISSUE THREAD

**Issue by sakkke** [catppuccin/catppuccin#1760]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Vivaldi is a web browser. Port creation is done!

![preview](https://user-images.githubusercontent.com/84666033/206841151-8e1e5577-01cd-42b0-824c-2ea7d28539e8.jpg)

Repo: https://github.com/sakkke/vivaldi

**Comment by DakshG07** [comment]
Perhaps getting this on Vivaldi themes would be more suitable?

**Comment by sakkke** [comment]
Sorry for delaying to reply. Yeah it's great idea! 😀 Do you think which is better for uploading themes, official Catppuccin account or a personal account? However I think to guess Vivaldi doesn't have official account feature...

**Comment by sakkke** [comment]
I made a new version.
![](https://raw.githubusercontent.com/sakkke/vivaldi/b699bb13360aad0688cd931744c8a6348657e874/assets/preview.webp)
https://github.com/sakkke/vivaldi/tree/dev

**Comment by nekowinston** [comment]
This seems fine to transfer, thanks for your port @sakkke!

**Comment by sakkke** [comment]
Transferred the port. Thanks too!

**Comment by sakkke** [comment]
Closing this issue and talking about Vivaldi themes has been moved to catppuccin/vivaldi#1.
