### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by thismoon** [catppuccin/catppuccin#1763]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes
here's my repo for the theme: https://github.com/thismoon/modrinth

**Additional context 📷 (optional)**
![res](https://user-images.githubusercontent.com/107642606/206880188-5d1db8e8-8b0e-4984-8325-2341db1a613f.png)

**Comment by sgoudham** [comment]
Hiya :wave:, just took the time to review the port. Nice work!

I just had two comments. 

1. It looks like when the webpage is viewed with light mode on Latte, the website is fairly unreadable as shown below:
![image](https://user-images.githubusercontent.com/58985301/209737568-525efcf3-e15f-4d2e-b5af-55905bb39d12.png)

	The same behaviour also occurs when using dark mode on a dark variant (frappe, macchiato or mocha)
	I believe one possible solution is to follow what the [SearXNG](https://github.com/catppuccin/searxng) port does and offer a light and dark mode option upon installation of the theme.

2. We should have a stylus install button, like the [DeepL](https://github.com/catppuccin/deepl) port shown below:
![image](https://user-images.githubusercontent.com/58985301/209737751-36920e42-412f-4ced-9af0-e018a66f21d0.png)

	I can see that the install link already exists but would be nice in the button format above ^^

Hope those 2 comments are okay!

**Comment by thismoon** [comment]
Hi sgoudham, thanks for reviewing
I did what you asked for with the colors (by borrowing some code from the SearXNG repo 😛, btw i noticed that it doesn't work when the theme is set to auto due to `:root.theme-auto` not being themed, I will probably open an issue there) and it's working correctly now
I also added a button to quickly install with stylus
is the repo good now?

**Comment by sgoudham** [comment]
Thanks for looking at it. A few more comments from me:

1. I would say that for the stylus drop-downs, we should limit the options for light and dark variants to only the applicable ones.

	The dropdowns should be as listed below:
	**Light Variant:** Latte
	**Dark Variant:** Frappe, Macchiato & Mocha

2. The _Install the style with Stylus:_ install link within the `Usage` section points to the raw GitHub user content for your repository but I'd imagine we'd want to change it to point towards catppuccin so that it works once transferred over. 

I think this repo should be good to transfer over after addressing the comments above!

**Comment by thismoon** [comment]
I did the changes you requested
but doesn't it feel wrong for a dropdown to only have one item?

**Comment by sgoudham** [comment]
Revisiting it now, you're right that it feels weird. The reason why I thought we'd want to limit it is that when I used the theme switcher (Frappe for Light, Mocha for Dark) it didn't make a difference on the light variant at all.

I'd imagine we want to allow scenarios in which the user chooses Frappe as the light variant and Mocha as the dark variant and is allowed to switch between those two modes.

**Comment by thismoon** [comment]
I re-added the options and now you can choose anything for light
and fixed the light problem
this is better IMO since it allows users to do what they want

**Comment by sgoudham** [comment]
Yup, the options look good and the theme looks great! Thanks for all the work and the revisions based on the comments.

@nekowinston should now be able to send you an invite to the organisation and you should be good to transfer the repository across!

**Comment by thismoon** [comment]
Thanks, now the repository is at https://github.com/catppuccin/modrinth
I think it's time to close this issue

**Comment by sgoudham** [comment]
Thanks for moving the repo over. 

We close the issue once the port has been added to the README as demonstrated [here](https://github.com/catppuccin/catppuccin/pull/1783)!
