### ISSUE TITLE
rEFInd

### ISSUE THREAD

**Issue by fapfaff** [catppuccin/catppuccin#1773]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
I have already created a [repository](https://github.com/fapfaff/refind-catppuccin)

**Comment by nekowinston** [comment]
Thanks for your work on this! 🙂 
The repo badges are [linking to catppuccin/template](https://github.com/fapfaff/refind-catppuccin/blob/7be78e3074da69fa6cb044e9c44c182e59144919/README.md?plain=1#L8-L12), but other than that, this looks good. We can transfer it once that's fixed.

**Comment by nekowinston** [comment]
@fapfaff any chance we could get this moved to the org? I'd happily fix the README afterward if you're short on time.

**Comment by fapfaff** [comment]
Sorry, I was very busy the last two months. I'll take care of it now
