### ISSUE TITLE
Optifine Shader

### ISSUE THREAD

**Issue by Gingeh** [catppuccin/catppuccin#1778]
**Are you available to help in the creation of this port? 😄**
Already done :)

![Preview Image](https://user-images.githubusercontent.com/39150378/209464301-092a18b7-c184-4792-8410-aff67e0ed491.png)

**Additional context 📷**
I've already [made a repo](https://github.com/Gingeh/Optifine-Catppuccin) for this port. 
I've listed this as separate from the existing [Minecraft port](https://github.com/catppuccin/minecraft), however it may be worth either combining the repos or linking to one from the other to aid discoverability.

**Comment by skinatro** [comment]
hey can you make an Iris version?

**Comment by Gingeh** [comment]
> hey can you make an Iris version?

Iris uses the Optifine shader format, sot it already supports this shader. In fact, these screenshots were taken using Iris :)

**Comment by skinatro** [comment]
> > hey can you make an Iris version?
> 
> Iris uses the Optifine shader format, sot it already supports this shader. In fact, these screenshots were taken using Iris :)

oh i see thanks a lot
I recently migrated to Iris so i didnt knew about that

**Comment by nekowinston** [comment]
This kinda reminds me of the Minecraft/MC Launcher discussion we had...
But in this case, I really think both projects are better off if they used the same repo. I gave you maintainer permissions on [ctp/minecraft](https://github.com/catppuccin/minecraft), I'd appreciate if you could include it there.

**Comment by Gingeh** [comment]
> I really think both projects are better off if they used the same repo. I gave you maintainer permissions on [ctp/minecraft](https://github.com/catppuccin/minecraft), I'd appreciate if you could include it there.

I've made a [pull request](https://github.com/catppuccin/minecraft/pull/11) to add it to the minecraft repo.
I would like a maintainer to look over / approve of the changes I've made before I merge it.

**Comment by backwardspy** [comment]
closing in favour of discussion on catppuccin/minecraft#11
thanks for your contribution @Gingeh!
