### ISSUE TITLE
Stable Diffusion WebUI / Gradio

### ISSUE THREAD

**Issue by Kettukaa** [catppuccin/catppuccin#1779]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
[webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)
[user.css](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#usercss)

Using user.css, we can theme the webui. I originally tried doing this, but then realized I have never used CSS before and I have no understanding of any coherent styling practices for Catppuccin - or anything for that matter. If anyone wants my feeble attempt at a css file, here is the [gist](https://gist.github.com/Kettukaa/ef2207b69f409f4e1b14c22a6149b4d9) 

Here is an image of what I've done: https://media.discordapp.net/attachments/850475527851737162/1057447353541460099/2022-12-27_18-52-46.png

And this is what webui normally looks like: https://user-images.githubusercontent.com/39339941/197560013-51e535d6-7cef-4946-ab6b-747e1c76b007.png

Some notable things I haven't done include the borders everywhere, hovering over buttons, text, and some other things. Also, I this was the first real time I've messed with css like this, so I have no clue how good or bad my attempt was.

**Comment by Kettukaa** [comment]
Oh one thing that I couldn't figure out for the life of me is styling the sliders. Everything I did either didn't work, or caused the whole style of the sliders to change plus leave a white background.

**Comment by Kettukaa** [comment]
wow oops, did not mean to close this haha. I meant to comment that I cannot figure out how to change the sliders for the life of me. Everything I do either does nothing, or changes the whole style of the slider and add a white background.

**Comment by Kettukaa** [comment]
I decided to continue to work on this and I've made some good progress. Though as this is the first css thing I've done, I'm now learning that different browsers require different things. So I need to work on chrome now. 

[Current image](https://cdn.discordapp.com/attachments/850475527851737162/1057483309824868372/2022-12-27_21-20-41.png)
[Updated gist](https://gist.github.com/Kettukaa/ef2207b69f409f4e1b14c22a6149b4d9)

**Comment by Kettukaa** [comment]
[Here](https://media.discordapp.net/attachments/992625159930388480/1057561284608020561/res_copy_1.webp) is the catwalk for where I'm at right now. I'm going to use my styles for a few days before I do anything more.

**Comment by Kettukaa** [comment]
I believe I'm ready to have my [repo](https://github.com/Kettukaa/catppuccin-webui) integrated

**Comment by nekowinston** [comment]
Giving this a try right now 🙂
