### ISSUE TITLE
Sidebery

### ISSUE THREAD

**Issue by thismoon** [catppuccin/catppuccin#1782]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes
here's my repo for the theme: https://github.com/thismoon/sidebery

**Additional context 📷 (optional)**
![image](https://user-images.githubusercontent.com/107642606/209811185-10edf2a4-0e44-4e95-bcc0-ae15d6d6ba16.png)

**Comment by nekowinston** [comment]
Thanks for your work on this, I made a PR on your repo so that we're using CSS variables instead of hardcoding the colors. I'd also like to get a better screenshot if possible, the current one has a pretty awkward aspect ratio 🤔

**Comment by thismoon** [comment]
hello @nekowinston
thanks for the PR, the sideberry css editor is difficult to use
what do you think of including firefox (with the catppuccin theme) in the screenshot to get a better aspect ratio?
that would be harder (change the firefox theme and sideberry theme 4 times) but i can do it if you agree

**Comment by nekowinston** [comment]
Yeah that's what I had in mind for the Screenshot, that should get us a more pleasant aspect ratio :slightly_smiling_face:

**Comment by thismoon** [comment]
![res](https://user-images.githubusercontent.com/107642606/212414056-c0985be6-854b-4cf8-9e5a-a36b979b820a.png)
is this better?

**Comment by nekowinston** [comment]
That's pretty good, once it's in the repo we can transfer it over!

**Comment by thismoon** [comment]
done
i think i can transfer it now
