### ISSUE TITLE
Bottom

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/catppuccin#1786]
**Are you available to help in the creation of this port? 😄 (optional)**
💖✨✨✨🥺,,,,👉👈💖💖,👉👈💖💖✨🥺👉👈✨✨✨,,👉👈✨✨✨✨🥺👉👈✨✨✨,,👉👈💖✨✨,,,👉👈✨✨✨,,👉👈💖💖🥺,,,,👉👈💖✨✨✨✨🥺,,👉👈💖💖👉👈💖💖,👉👈✨✨✨,,👉👈💖💖✨🥺,👉👈💖💖,,,,👉👈💖💖,👉👈✨✨✨,,👉👈💖💖✨,,👉👈💖💖✨,👉👈💖💖✨,,,,👉👈💖💖✨🥺,👉👈✨✨✨,,👉👈💖💖,,,,👉👈💖💖,👉👈💖💖✨,,,,👉👈💖💖,👉👈💖🥺,,,👉👈 https://github.com/nekowinston/catppuccin-bottom

**Additional context 📷 (optional)**
💖✨✨,,,👉👈✨✨✨,,👉👈💖✨✨✨✨🥺,,👉👈💖💖🥺,,,,👉👈✨✨✨,,👉👈💖💖✨🥺👉👈💖💖✨,👉👈💖💖✨,,,,👉👈💖💖✨,,,,👉👈💖💖✨✨,👉👈✨✨✨,,👉👈💖💖,,👉👈💖💖✨,👉👈💖💖✨,,,,👉👈✨✨✨,,👉👈💖💖✨🥺,👉👈💖💖,,,,👉👈💖💖🥺👉👈💖💖✨🥺👉👈✨✨✨✨🥺,👉👈

**Comment by nyxkrage** [comment]
As a bottom +1
