### ISSUE TITLE
https://news.ycombinator.com

### ISSUE THREAD

**Issue by Groovin-Dev** [catppuccin/catppuccin#179]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
It's a relatively simple site so creating a theme should be easy.

**Comment by asheeeshh** [comment]
I tried doing it, but still cant figure out how to style the faq, guidelines and security page

![image](https://user-images.githubusercontent.com/68690233/176450761-e39194e4-8e61-4226-ae0d-630c846ae3c0.png)

**Comment by asheeeshh** [comment]
> Got this style to work. Supports the [Refined Hacker News](https://github.com/plibither8/refined-hacker-news) extension. It also works for the Guidelines and FAQ pages. There are still some things I need to add (I think) but this is looking pretty good so far IMO.
> 
> ![image](https://user-images.githubusercontent.com/56172528/176476846-505ae098-6157-4c02-bc7e-e5acf3c15b86.png)

oh, i didnt know about that extension, i used stylus actually

**Comment by Groovin-Dev** [comment]
Yeah, I used Stylus as well I just added support for the RHN selectors like that sort stores bar at the top. There are some other things that were more annoying to get (for example the user info on hover) but I got it eventually.

**Comment by Groovin-Dev** [comment]
You can find my work here but I don't think I'm going to continue on this style any more. I lost all motivation to work on it when I got it to what I think is 95% done. If anyone would like to use the below code and improve on it, feel free to do so.

https://gist.github.com/Groovin-Dev/c8f413ba127b6b6af03163b3c4663731

**Comment by nekowinston** [comment]
Alright, thanks! I'll re-open the issue then (since it's not completed), and mark it as "draft available". Maybe someone will pick it up and do the work to make it official.

**Comment by lucasmelin** [comment]
I'd be willing to pick this up - I created a style using the Catppuccin Mocha color scheme for myself, and then extended it this evening to cover the other flavors using the port tools. Mine is more bright 😄 https://github.com/lucasmelin/hacker-news but I can rework it to better align with the color scheme picked out by the previous devs, and I can tackle the Guidelines and FAQ pages as well.

**Comment by lucasmelin** [comment]
Here's what I have so far, including the standard theme picker for Stylus themes. The Guidelines, FAQ, Lists and Security pages are all themed as well.

![Catppuccin HackerNews](https://raw.githubusercontent.com/lucasmelin/hacker-news/b3c77538aeb67341a531d55b5efa0639df6a9d38/assets/catwalk.webp)

**Comment by Groovin-Dev** [comment]
That looks pretty good! The only comment I have is suggesting that the background color just be 1 color instead of having padding and the content background be a different color

**Comment by lucasmelin** [comment]
> That looks pretty good! The only comment I have is suggesting that the background color just be 1 color instead of having padding and the content background be a different color

Can do - I think on mobile the default Hacker News css uses two different colors, but maybe using just one would look more cohesive.

**Comment by lucasmelin** [comment]
Having the single color for the background looks a lot better, imo:

![Updated Hacker News theme](https://raw.githubusercontent.com/lucasmelin/hacker-news/c950551b9b92fb523453425b8a5b5954fa38bae3/assets/catwalk.webp)

**Comment by nekowinston** [comment]
@lucasmelin thanks for your work on this! I've sent you an invite to the org, repo looks good :slightly_smiling_face:

**Comment by lucasmelin** [comment]
@nekowinston repo has been successfully transferred to the org. https://github.com/catppuccin/hacker-news
