### ISSUE TITLE
xed

### ISSUE THREAD

**Issue by justTOBBI** [catppuccin/catppuccin#1791]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Already made a repo here: https://github.com/justTOBBI/xed

**Comment by nullishamy** [comment]
This looks great!

**Comment by sgoudham** [comment]
Hiya :wave: 

I'm about to check it properly now but I just have a few comments from just skimming the files:

1. Could you please change the default branch from `master` -> `main`?

2. Our cursor highlights across all themes should be `rosewater`

I'll add more comments if I find anything else, just going to install it now

**Comment by justTOBBI** [comment]
![image](https://user-images.githubusercontent.com/47004621/212764303-c96888e8-16fb-42af-8b02-126fa8940889.png)
this is what it currenty ks ike

**Comment by sgoudham** [comment]
Sorry I didn't think `xed` was stupid enough to highlight strings as constants, those tags should be green!

**Comment by justTOBBI** [comment]
Hey, so I just fixed the few colors and the spelling mistakes, for the screenshot, I can't figure out, why this happens, so maybe someone else could make 4 screenshots for me?
