### ISSUE TITLE
Elk

### ISSUE THREAD

**Issue by ryanccn** [catppuccin/catppuccin#1797]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes! https://github.com/ryanccn/ctp-elk

**Additional context 📷 (optional)**
Elk is a nimble Mastodon web client, currently in alpha.

**Comment by sgoudham** [comment]
Hey :wave:

Just a few comments from me: 

1. Highlighting text in Latte looks a bit odd, see below:

`latte`
![image](https://user-images.githubusercontent.com/58985301/212310330-5ccbecaf-6814-441a-b468-9404a4262f0f.png)

2. I don't believe the specification for the Latte theme has been followed. In our style guide, it says that primary background should be `base` and the secondary background should be darker such as `crust` and/or `mantle`. However, when I hover above secondary elements (such as the `Explore` element) the highlight is lighter than the background

	![image](https://user-images.githubusercontent.com/58985301/212310204-13dabe10-e737-4eb8-b92d-2fd2f9a1142e.png)
	
	I see that you have multiple ports open so it would be great if you could ensure that all of them follow the spec above!

**Comment by ryanccn** [comment]
Fixed in https://github.com/ryanccn/ctp-elk/commit/dc18594b5b5f72e80559ce459a71a3f66c4a333a! I'll take a look at the other ports when I get time 😄

**Comment by sgoudham** [comment]
Thanks for the fix, just tried out the theme and it looks good!

Feel free to transfer it over to the organisation and we can raise a PR to get this issue closed :tada:
