### ISSUE TITLE
Pink on light background is hard to see

### ISSUE THREAD

**Issue by ken-scarf** [catppuccin/catppuccin#1798]
I'm loving this theme so far. So thank you for all the effort. Unfortunately, I can barely see pink on light background
![catpuccin-latte-pink-text](https://user-images.githubusercontent.com/92234785/210603706-b8b1bf62-7c6e-411a-9a12-28e998132705.png)

**Comment by skinatro** [comment]
which program?

**Comment by ken-scarf** [comment]
ooh. It's in emacs. I should open the issue there. Thanks!
