### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by jenslys** [catppuccin/catppuccin#18]

**Comment by elkrien** [comment]
I did a Chrome theme: https://github.com/elkrien/chrome
Please let me know if it is OK so I can upload it.

**Comment by tuhanayim** [comment]
It looks perfect!

**Comment by geekyBoogiepop** [comment]
It looks damn good! I was looking for it since a couple of weeks. I'm using Catppuccin on every app on my system and I totally love it, reminds me of Tokyo Night theme.

**Comment by elkrien** [comment]
OK, I did a PR with Chrome theme to dev branch

**Comment by Pocco81** [comment]
#57 resolves this. But still, if an space to discuss about the port's update to the Chrome Web Store is needed, then I guess it should be an issue in the repo for this port.
