### ISSUE TITLE
Proton

### ISSUE THREAD

**Issue by soya-daizu** [catppuccin/catppuccin#1802]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes https://github.com/soya-daizu/catppuccin-proton

**Additional context 📷 (optional)**
This is primarily for Proton Mail, but since all Proton products share the same base stylesheets, it should work on other Proton products as well.

**Comment by nekowinston** [comment]
Hi there, thanks for the port!
The repo looks good & I've had a quick look at the source code - seems clean. I'd like for someone who uses ProtonMail to review it, then we can transfer it to the org :slightly_smiling_face:

**Comment by ghostx31** [comment]
I've had a look at the theme and checked around the mail UI with mocha and latte as of now. Both work flawlessly. I'll be testing frappe and macchiato but otherwise, this looks good to me. Thanks for this!

**Comment by nekowinston** [comment]
I've sent you an invite to the org @soya-daizu, feel free to transfer the repository :+1: 
Please rename it to `catppuccin/proton` while transferring.

**Comment by soya-daizu** [comment]
Thanks! I've transferred the repository now.

**Comment by nekowinston** [comment]
I've set your maintainer permissions, cleaned up some URLs in the README, and added it to this repo's README with the most recent commit. Thanks again for porting it!
