### ISSUE TITLE
Ultrakill

### ISSUE THREAD

**Issue by Gingeh** [catppuccin/catppuccin#1805]
**Are you available to help in the creation of this port? 😄**
Yes

**Additional context 📷**
All that is needed for an Ultrakill port is to put an image with the desired colours in the `ULTRAKILL/Palettes` folder.

Example `Catppuccin.png` with all four flavours in one:
![Catppuccin.png](https://user-images.githubusercontent.com/39150378/211450257-017d9516-f5af-4290-ae10-056ceb51a60d.png)

**Why tho? 🤔**
Why not?

**Comment by Gingeh** [comment]
![Catwalk Preview](https://user-images.githubusercontent.com/39150378/211452645-12bb3d30-941c-4568-b26c-bddac9148528.png)

**Comment by Gingeh** [comment]
I've created a repository:
[https://github.com/Gingeh/catppuccin-ultrakill](https://github.com/Gingeh/catppuccin-ultrakill)

**Comment by nekowinston** [comment]
I don't really think there's any more reviews necessary, this should be good to be moved over 🙂 
Who doesn't want a soothing colorscheme for ULTRAKILL
