### ISSUE TITLE
egui

### ISSUE THREAD

**Issue by Stonks3141** [catppuccin/catppuccin#1815]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
The port is currently here: [Stonks3141/egui](https://github.com/Stonks3141/egui).

![preview](https://raw.githubusercontent.com/Stonks3141/egui/main/assets/previews/preview.webp)

**Comment by backwardspy** [comment]
nice work, thanks for this!

@nekowinston the crate has been reviewed and transferred into the catppuccin team on crates.io, so this is ready to go.

**Comment by nekowinston** [comment]
> nice work, thanks for this!
> 
> @nekowinston the crate has been reviewed and transferred into the catppuccin team on crates.io, so this is ready to go.

Thanks!
Sent you the invite to the org @Stonks3141
