### ISSUE TITLE
Quran.com

### ISSUE THREAD

**Issue by mustafakhalaf-git** [catppuccin/catppuccin#1821]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Work can be found [here](https://github.com/mustafakhalaf-git/quran)

![image](https://user-images.githubusercontent.com/42213155/213894777-32f08d16-10bb-444d-a47d-5fad70098296.png)

**Comment by sgoudham** [comment]
Hey :wave:

We appreciate your efforts in creating this port, it looks great!

However, the staff team has taken some extra time to review this particular port as it is the first one we have encountered with a religious context. After careful consideration, we have decided that we will not accept ports that are religious or political in nature.

It is important to note that we have no issue with our palette being used here. However, as an organization, we want to keep a neutral stance by not accepting any ports of that nature. As a result, we are updating our contributing guidelines to reflect this.

**Comment by mustafakhalaf-git** [comment]
@sgoudham Alright it's fine, I was kinda expecting this answer anyways but I thought I'd try submitting it and see what happens

either ways thanks for taking the time to review it, and I'm happy I was a reason in getting the contributing guidelines more clarified

Have a nice day

**Comment by mustafakhalaf-git** [comment]
just gonna mention my friend from discord @thismoon, since he was interested in this PR as well

**Comment by nekowinston** [comment]
> @sgoudham Alright it's fine, I was kinda expecting this answer anyways but I thought I'd try submitting it and see what happens
> 
> either ways thanks for taking the time to review it, and I'm happy I was a reason in getting the contributing guidelines more clarified and updated for other users
> 
> Have a nice day

Thanks for your work on this port, and understanding why we've decided to not move it over to the organisation.
I hope that people will still be able to find your work and benefit from it. 🙂 

We've updated our contribution docs with the referenced commit.

**Comment by mustafakhalaf-git** [comment]
@sgoudham btw, I'm making a theme for twitch https://github.com/mustafakhalaf-git/twitch

will submit it soon, there are a few things left to finish

**Comment by sgoudham** [comment]
Cool @mustafakhalaf-git! It would be great if you could open a [new discussion](https://github.com/catppuccin/catppuccin/discussions/new?category=port-requests) so that we can track it while it's WIP!

**Comment by mustafakhalaf-git** [comment]
https://github.com/catppuccin/catppuccin/discussions/1885
