### ISSUE TITLE
Starship Prompt

### ISSUE THREAD

**Issue by etrigan63** [catppuccin/catppuccin#1823]
**Are you available to help in the creation of this port? 😄 (optional)**
YES

**Additional context 📷 (optional)**
https://github.com/etrigan63/catppuccin-starship

All finished.

**Comment by rubyowo** [comment]
please look at #203

**Comment by etrigan63** [comment]
This is done and I am offering it for inclusion.

**Comment by nekowinston** [comment]
Closing this as a duplicate of #203. This isn't planned.
