### ISSUE TITLE
Logseq

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1872]
@griimick worked on this port which is available at [griimick/logseq](https://github.com/griimick/logseq)
It's now ready to be reviewed :tada: 

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1828

<div type='discussions-op-text'>

<sup>Originally posted by **dhruvinsh** October 24, 2022</sup>
**Are you available to help in the creation of this port? 😄**
Maybe (As a Tester)

**Additional context 📷 (optional)**
https://logseq.com/ 
Logseq is a knowledge base like obsidian.md that works on top of local plain-text Markdown and Org-mode files. Use it to write, organize and share your thoughts, keep your to-do list, and build your own digital garden. Having a color scheme for the same is great idea.

</div>

**Comment by griimick** [comment]
Thanks! Feel free to DM me in discord for a walkthrough.

**Comment by sgoudham** [comment]
Hey, just had a look at it. Looks pretty good!

Just one thing I noticed is that it's hard to tell when the checkboxes are ticked, can we use another colour for it?

![image](https://user-images.githubusercontent.com/58985301/214977141-bffa1673-5437-43cd-8d99-a8d8a5623438.png)

**Comment by griimick** [comment]
Ah! I missed this.  Will cover this and full-pallete over weekend. Btw did you face any issues setting it up following the README?

**Comment by griimick** [comment]
A new version of the port is up now.

**Comment by sgoudham** [comment]
Hey :wave: 

Thanks for putting up a new version, it looks good to transfer over! I think you're already part of the org so just feel free to do it in your own time and we can raise a PR to get this closed! @griimick 

Thanks again for your work 🫡
