### ISSUE TITLE
qBittorrent

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1875]
@Xurdejl has made a port for [qBittorrent](https://github.com/Xurdejl/qbittorrent) 
It's now ready for review! :tada: 

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1835

<div type='discussions-op-text'>

<sup>Originally posted by **rollingmoai** April 25, 2022</sup>
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Additional context 📷 (optional)**
[Examples of qBittorrent themes](https://github.com/qbittorrent/qBittorrent/wiki/List-of-known-qBittorrent-themes)
</div>

**Comment by nekowinston** [comment]
Like we talked about in Discord, I'm more than happy to see this moved over now @Xurdejl 🙂 
Thanks for your work!
