### ISSUE TITLE
Reddit

### ISSUE THREAD

**Issue by ghostx31** [catppuccin/catppuccin#1877]
### Discussed in https://github.com/catppuccin/catppuccin/discussions/1860

[jayylmao](https://github.com/jayylmao) has created a port for Reddit and the repo is present at: [jayylmao/catppuccin-reddit](https://github.com/jayylmao/catppuccin-reddit). 

The README contains stylus links formatted in such a way that they are functioning when the port is transferred so currently the stylus theme can be installed from: https://github.com/jayylmao/catppuccin-reddit/raw/main/css/reddit-catppuccin.user.css 

<div type='discussions-op-text'>

<sup>Originally posted by **kukapishi** March 23, 2022</sup>
I want catppuccin for reddit</div>

**Comment by nekowinston** [comment]
Invited @jayylmao, thanks for your port! This is good to transfer over from what I can see.
