### ISSUE TITLE
Twitch

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1886]
@mustafakhalaf-git made a Twitch userstyle / port!
It's ready to review at [mustafakhalaf-git/twitch](https://github.com/mustafakhalaf-git/twitch)

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1885

<div type='discussions-op-text'>

<sup>Originally posted by **mustafakhalaf-git** January 27, 2023</sup>
### Will you make the port?

- [x] Yes, I'm willing to make the port

### How can the requested port be themed?

with the browser extension 'stylus'

### Has the requested port been themed already?

No

### Any additional comments?

Currently working on it https://github.com/mustafakhalaf-git/twitch</div>

**Comment by mustafakhalaf-git** [comment]
Thanks!

**Comment by sgoudham** [comment]
Hey @mustafakhalaf-git :wave: 

Looks great overall, just a few things from me: 

1. When hovering above channels that I follow, it doesn't seem to be highlighted with the Catppuccin palette for Frappe/Macchiato/Mocha? See below:

	![image](https://user-images.githubusercontent.com/58985301/215351403-c79ffd59-9d15-4b2e-a028-51ed777a8b65.png)
	
	I would expect the hover highlight to be like this:
	![image](https://user-images.githubusercontent.com/58985301/215351437-898db416-42c8-48b1-abe0-1f21307d2500.png)

2. Similar sort of issue when using Latte when hovering above followed channels, it's very difficult to see it:

	![image](https://user-images.githubusercontent.com/58985301/215351675-ce279fd5-9797-4cf6-b926-38e09947750b.png)

	I would expect the hover highlight to be as pronounced as shown below:
	![image](https://user-images.githubusercontent.com/58985301/215351712-f6abfee4-9876-47b8-86a6-4b5a78a03051.png)

3. Twitch whispers on-hover highlights seem to suffer from the same problem above on Frappe/Macchiato/Mocha:

	![image](https://user-images.githubusercontent.com/58985301/215351879-4e13d3bc-595f-45cd-8a8d-f0160e239db9.png)
	
4. For any elements with a background of a mauve, I think the text colour for Frappe/Macchiato/Mocha can be improved to use a dark colour?

	![image](https://user-images.githubusercontent.com/58985301/215352629-a6dfd94f-c1f9-4f27-b0af-dee124e95651.png)
	![image](https://user-images.githubusercontent.com/58985301/215352641-7e10727b-e86f-4bf6-bbe7-11ae44e187b3.png)

	I think those elements and others would benefit from a text colour of crust - only on the darker flavours! Latte for those buttons looks really great. Let me know what you think on this one.

5. One final thing for me, this is the creator dashboard on Twitch. It would be good to theme the side panels with the Catppuccin palette?

	![image](https://user-images.githubusercontent.com/58985301/215352792-07d4935e-1e91-475b-8543-4b75ad02bc67.png)

Other than the tiny things above, this really looks great! Thank you for working on it!! Happy to chat about any of the comments further here or on our discord :heart:

**Comment by mustafakhalaf-git** [comment]
Fixed all

**Comment by sgoudham** [comment]
Thanks for making those changes! It looks good to be moved over!

@nekowinston will give you an invite to the organisation and then you can transfer it over then. We'll close off this issue once twitch has been added to the [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!

Great work!

**Comment by nekowinston** [comment]
@mustafakhalaf-git I've only just now sent you an invite, you should have received an email.

Thanks for this port! 🎉

**Comment by mustafakhalaf-git** [comment]
@nekowinston Done
