### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by jenslys** [catppuccin/catppuccin#19]

**Comment by mbeckrich** [comment]
Hey, sorry if I've misunderstood the directions, but I have a Firefox theme here: https://github.com/mbeckrich/firefox Please let me know if you'd like me to make any changes or use a different way to submit the theme. :)

**Comment by lokesh-krishna** [comment]
Looks like the theme isn't available on the Firefox Add-Ons site. Is that intentional?

**Comment by mbeckrich** [comment]
> Looks like the theme isn't available on the Firefox Add-Ons site. Is that intentional?

Yeah, just wanted to make sure the Firefox theme was cool with people here before I used the Catppuccin name on their theme site.

**Comment by andreasgrafen** [comment]
Cheers! I just quickly threw together a Firefox Colour Theme, with the Catppuccin colours. I've used magenta for all the highlights, but if that's wanted I could make Variants with the other colours as well. Luckily that's just a quick "search and replace". ^—^

As GitHub doesn't allow me to upload the manifest by itself as an attachment.. here are the [files](https://github.com/catppuccin/catppuccin/files/7809707/catppuccin_magenta_ffcolour.zip) zipped.. I know .zip archives suck, so i've also put the [files on discord](https://discord.com/channels/907385605422448742/907386197855322123/927997254034411572), as well as the [manifest.json itself on pastebin](https://pastebin.com/FbHFjiam).

**Comment by Pocco81** [comment]
#29 is a duplicate of this issue, however since the development on #29 was carried out faster and many people participated on it, I'm closing this issue in favor of it.
