### ISSUE TITLE
Replit

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1903]
@Gingeh has made a repo for repl.it: [Gingeh/replit](https://github.com/Gingeh/replit)
It's now ready for review! 

It is worth noting that while the repository itself won't contain the theme, having it under our namespace is good for people to identify which theme is the **official** theme as there are other versions of the Catppuccin theme on repl.it.

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1899

<div type='discussions-op-text'>

<sup>Originally posted by **Gingeh** January 31, 2023</sup>
### Will you make the port?

- [X] Yes, I'm willing to make the port

### How can the requested port be themed?

Replit now officially supports custom themes, which can be created using a very helpful editor at https://replit.com/themes. 
![Replit theme editor](https://user-images.githubusercontent.com/39150378/215679205-cbf9609c-acb3-4912-9bdb-cc6ff2a7716f.png)

### Has the requested port been themed already?

There are several existing "catppuccin" themes, however, it would be good to create a set of official themes.
![Existing catppuccin themes](https://user-images.githubusercontent.com/39150378/215678574-4e19abe1-f8e7-4824-88cf-02e03d609d13.png)

### Any additional comments?

We have a few options:
1. We contact one of the users that already made a theme and try to make it official
2. We create a set of themes from scratch

Also, should we use a catppuccin branded account or just a personal account?</div>

**Comment by sgoudham** [comment]
Hey :wave:
The theme looks good on all the flavours!

Just a comment on the wording of the README on the repo itself. I think it might be better if we clarify step one of the usage?

Something along the lines of 
> Browse official flavors [here](https://replit.com/themes?authorId=20252294).

What do you think?

**Comment by Gingeh** [comment]
> I think it might be better if we clarify step one of the usage?
> > Browse official flavors [here](https://replit.com/themes?authorId=20252294).

Yeah that makes sense, I'll change to README now. 
I'll also change step two to say "Click on the flavor you want to install".

**Comment by Gingeh** [comment]
Done 👍

**Comment by sgoudham** [comment]
Thanks for that!! Looks good to be transferred into the organisation.
I'll merge #1904 once that's done!

**Comment by Gingeh** [comment]
Transferred 👍
