### ISSUE TITLE
Catppuccin in VSCode vs Neovim

### ISSUE THREAD

**Issue by jrock2004** [catppuccin/catppuccin#191]
So on top I have Vscode and bottom is Neovim. Why does the import color look different

![image](https://user-images.githubusercontent.com/655716/178163473-20f0e880-320d-4762-99ba-7cf8208ce86b.png)

**Comment by andreasgrafen** [comment]
The VSCode port isn't fully up to date with the latest changes. Thus there are some issues with it as of right now. All the porting to v0.2.0 is still in the making sadly. :/

**Comment by jrock2004** [comment]
Thank you. Will close for now unless you think this should be open to track
