### ISSUE TITLE
NixOS Search

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1910]
A port has been made by @alaidriel for NixOS Search: [alaidriel/ctp-nixos-search](https://github.com/alaidriel/ctp-nixos-search)
It's now ready for review!

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1905

<div type='discussions-op-text'>

<sup>Originally posted by **alaidriel** February  3, 2023</sup>
### Will you make the port?

- [X] Yes, I'm willing to make the port

### How can the requested port be themed?

With [Stylus](https://github.com/openstyles/stylus).

### Has the requested port been themed already?

I've made a draft repo at [https://github.com/alaidriel/ctp-nixos-search](https://github.com/alaidriel/ctp-nixos-search).

### Any additional comments?

_No response_</div>

**Comment by nekowinston** [comment]
I have reviewed this one and had a few messages with @alaidriel on Discord, LGTM! Thanks for the port.

I've sent you an invite, feel free to transfer it over to the org. :slightly_smiling_face:

**Comment by alaidriel** [comment]
I transferred it over.
