### ISSUE TITLE
FluentTerminal

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1918]
@mrdoge515 has made a port for FluentTerminal: [mrdoge515/FluentTerminal](https://github.com/mrdoge515/FluentTerminal)
It's now ready for review!

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1916

<div type='discussions-op-text'>

<sup>Originally posted by **mrdoge515** February 11, 2023</sup>
### Will you make the port?

- [X] Yes, I'm willing to make the port

### How can the requested port be themed?

[FluentTerminal](https://github.com/felixse/FluentTerminal) can be themed using the `Themes` tab in settings.

### Has the requested port been themed already?

https://github.com/mrdoge515/FluentTerminal

### Any additional comments?

_No response_</div>

**Comment by justTOBBI** [comment]
Just looked into it. Looks done 👍🏻
(Also we really need to fix terminal colors)

**Comment by sgoudham** [comment]
This looks good to be moved over, @nekowinston should send you an invite to the organisation so you can transfer it over. We'll close off this issue once a PR has been raised adding it to the [`ports.yml`](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)

Thanks for your work!

**Comment by nekowinston** [comment]
I've just sent the invite.

**Comment by mrdoge515** [comment]
Thanks! I've transferred the repository

**Comment by backwardspy** [comment]
thanks for the contribution @mrdoge515!
