### ISSUE TITLE
Terminals   oh-my-zsh

### ISSUE THREAD

**Issue by KiligFei** [catppuccin/catppuccin#192]
Are you available to help in the creation of this port? 😄 (optional)
No

Can you provide a theme for oh-my-zsh

**Comment by andreasgrafen** [comment]
Heya, there is a port for [ZSH Syntax Highlighting](https://github.com/catppuccin/zsh-syntax-highlighting) out there. Regarding a theme (Prompt etc.), there shouldn't be a need to provide a spearate theme since the colours should respect your terminal colour scheme, no?

**Comment by KiligFei** [comment]
Thanks
