### ISSUE TITLE
starship.rs

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1929]
@JoshPaulie has made a port for starship.rs: https://github.com/JoshPaulie/starship
It's ready for review!

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1927

<div type='discussions-op-text'>

<sup>Originally posted by **JoshPaulie** February 14, 2023</sup>
### Will you make the port?

- [X] Yes, I'm willing to make the port
- [X] [Done](https://github.com/JoshPaulie/starship)! 🚀

### How can the requested port be themed?

[starship.rs](https://starship.rs) is a customizable prompt. one can define custom palettes and use defined color names, perfect for Catppuccin.

### Has the requested port been themed already?

Yes & no. Others have proposed ports, but were static opinionated. With the addition of user defined palettes, a much more flexible "port" is now possible.</div>

**Comment by nekowinston** [comment]
I'd still like to see a *sample screenshot* added, similar to https://github.com/catppuccin/waybar
![CleanShot 2023-02-20 at 18 26 43@2x](https://user-images.githubusercontent.com/79978224/220169731-631e696e-d418-4921-bc9f-024dd27638de.png)

I think we just have to represent the catppuccin brand somehow.

Otherwise this looks good, I'm now using palette definitions myself.

**Comment by nekowinston** [comment]
I forgot the mention, @JoshPaulie

Also we should probably document that it's best to keep the `[palette.<name>]` definitions on the bottom of the config file, otherwise it's easy to get caught by how TOML parses stuff.

**Comment by JoshPaulie** [comment]
I'll get 'em both done :)

**Comment by JoshPaulie** [comment]
@nekowinston Thoughts on what the palette table names should be?

- `[palettes.catppuccin-flavor]`
- `[palettes.catppuccin_flavor]`
- `[palettes.flavor]`

In addition, should the color names of capitalized?

**Comment by nekowinston** [comment]
`_` seems to be the standard for Starship config, so let's go with that. I'm all for namespacing it my default, as it just helps to avoid potential collisions.

`catppuccin_mocha` sounds good.

**Comment by JoshPaulie** [comment]
@nekowinston Added! Think it's ready to rock

**Comment by nekowinston** [comment]
Looks like it! I've sent you an invite to the org, feel free to transfer it over.

**Comment by JoshPaulie** [comment]
The port is live! Enjoy 😊
