### ISSUE TITLE
Xcode

### ISSUE THREAD

**Issue by PaulDoesDev** [catppuccin/catppuccin#193]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
Searched the issues and no one had requested it yet.
I'd love to be able to use catppuccin there too.

**Comment by quentinguidee** [comment]
Port: https://github.com/quentinguidee/xcode

<img width="1072" alt="xcode" src="https://user-images.githubusercontent.com/12123721/182108007-0fcd814a-556a-4ca0-a1d8-e35447ff12c7.png">

**Comment by nekowinston** [comment]
tranferred to the org, and added to the README in 12f8423bf5951eb697af9f3e57c9f15f730b42a5
