### ISSUE TITLE
DeepL

### ISSUE THREAD

**Issue by watatomo** [catppuccin/catppuccin#195]
**Are you available to help in the creation of this port? 😄 (optional)**
Done over [here](https://github.com/watatomo/deepl)!

**Additional context 📷 (optional)**
Still has some bugs. Struggling with identifying the white border that appears when the translated text is clicked (on some occasions).

**Comment by andreasgrafen** [comment]
A screenshot would be nice, other than that I don't have anything to nag about after a quick glance. c:

**Comment by watatomo** [comment]
Yeah, it wasn't ready yet so I didn't add a screenshot, but there's one now.
