### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by Dukeatron** [catppuccin/catppuccin#196]
**Are you available to help in the creation of this port? 😄**
Yes

**Additional context 📷 (optional)**
[Screenshot here](https://imgur.com/a/1XxRW3L)

**Repo link**: [here](https://github.com/Dukeatron/steam)

**Comment by WitherCubes** [comment]
Duplicate of #118.

**Comment by nekowinston** [comment]
Closing this in favour of #118. The Repo has now been transferred to the Org, to further collaborate there.
