### ISSUE TITLE
FreshRSS

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1962]
### Link to repository

https://github.com/isabelroses/freshrss

### Screenshots

![image](https://user-images.githubusercontent.com/58985301/222867212-6c6d2175-3b65-4de1-b985-219b02f9f085.png)

#### Discussed in https://github.com/catppuccin/catppuccin/discussions/1938

Originally posted by https://github.com/isabelroses February 22, 2023

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey there 👋, 
Had a chance to look at this earlier, just one thing really:

1. It's quite difficult to see the outlines surrounding input boxes, checkboxes etc. I think it would be really neat if these were accent coloured.
![image](https://user-images.githubusercontent.com/58985301/225021093-b2e71db1-9c54-48a3-adc6-f5559bebe98f.png)

I didn't really come across anything else, great work ❤️

**Comment by isabelroses** [comment]
I made these changes. 
Thanks for the suggestion its a good idea that i over looked.

**Comment by sgoudham** [comment]
Thanks for making those changes, I've had a chance to look at it again and found a couple more things:

1. The hover highlight is currently the same as the currently selected which goes against our style guide, currently hovered elements should be lighter. In the example below, `FreshRSS 1.20.0` should turn a lighter colour when hovered (maybe `surface2` ?)

	![image](https://user-images.githubusercontent.com/58985301/225482688-2f90cc5b-6f6e-4e9a-ba33-074aebd90e21.png)

2. Similar to the point above, it's impossible to know that I'm hovering above `Display` in the screenshot below, the hover should also be lighter here

	![image](https://user-images.githubusercontent.com/58985301/225483405-d4d665ef-95b1-42ba-a3dc-4730985857da.png)

3. The label management page still has dark input boxes

	![image](https://user-images.githubusercontent.com/58985301/225483533-d7db879f-0247-4602-ad8e-ae3648dd8c12.png)

Hope this feedback is okay!

**Comment by isabelroses** [comment]
All the requested changes have been made. 
Starting with hover:
![image](https://user-images.githubusercontent.com/71222764/225575655-9cb57498-d4be-429b-a441-72b98197aaba.png)
![image](https://user-images.githubusercontent.com/71222764/225575825-dd11f838-7a9a-4a0f-b790-9bcbdeed7248.png)
And ending with the labels:
![image](https://user-images.githubusercontent.com/71222764/225576012-062df220-0692-4835-96a0-3f6a6e69165e.png)

**Comment by sgoudham** [comment]
Looks great, thanks for making those changes. 

One slight nitpick (sorry!): The menu at the top right still doesn't have the hover highlights, the hover foreground is a bit darker so it's better but it would be preferable to change the background to a lighter colour so that it's consistent. Is that possible?

![image](https://user-images.githubusercontent.com/58985301/225696627-f0cbfaf4-ae46-4f51-a9c4-d34890c47c94.png)

**Comment by isabelroses** [comment]
No worries.
Change made:
![image](https://user-images.githubusercontent.com/71222764/225699639-5ccede18-8509-4df8-a3c0-f1974214d58a.png)

**Comment by sgoudham** [comment]
Looks great! Happy for you to transfer it over into the organisation! :tada: 
Thanks for all your work :heart:
