### ISSUE TITLE
YouTube Music CSS

### ISSUE THREAD

**Issue by nonetrix** [catppuccin/catppuccin#197]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe I am good at CSS I am not good at picking the right colors probably 

**Additional context 📷 (optional)**
https://music.youtube.com
![Screenshot from 2022-07-16 23-56-21](https://user-images.githubusercontent.com/45698918/179384527-35f8918e-7112-4345-86f4-4d4dd1fd8e74.png)

![Screenshot from 2022-07-16 23-56-36](https://user-images.githubusercontent.com/45698918/179384530-44ad9ee7-e4fb-426a-bce6-518583951c03.png)

**Comment by WitherCubes** [comment]
You can check out the [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md) and other ports like [Whoogle](https://github.com/catppuccin/whoogle), [MonkeyType](https://github.com/catppuccin/monkeytype), [Youtube](https://github.com/catppuccin/youtube), etc.

**Comment by nekowinston** [comment]
I'd suggest closing this issue here and maybe tracking it on https://github.com/catppuccin/youtube/issues

It's the same domain, we could have an additional UserCSS for the music subdomain — what's your take on this @andreasgrafen?

**Comment by andreasgrafen** [comment]
Hmm. I'm not sure how different everything is in comparison to just regular youtube in terms of markup etc. So I'd opt for a separate Stylesheet that exclusively works with Youtube Music. I agree that this could be tracked in the Youtube Repo directly tho. c:

**Comment by rubyowo** [comment]
I did this https://github.com/rubyowo/youtubemusic

**Comment by nekowinston** [comment]
@andreasgrafen 
> I'd opt for a separate Stylesheet that exclusively works with Youtube Music.

Would you be open to add your stylesheet as an extension to [catppuccin/youtube](https://github.com/catppuccin/youtube) @rubyowo?

Sadly, I don't have time to help out with this today.

**Comment by rubyowo** [comment]
sure

**Comment by AnubisNekhet** [comment]
> @andreasgrafen
> 
> > I'd opt for a separate Stylesheet that exclusively works with Youtube Music.
> 
> Would you be open to add your stylesheet as an extension to [catppuccin/youtube](https://github.com/catppuccin/youtube) @rubyowo?
> 
> Sadly, I don't have time to help out with this today.

The way the theming system works rn, the youtube music userstyle would need to be rewritten to match the youtube format.

**Comment by nekowinston** [comment]
I don't mind if you make this a separate file as well – that's up to you.

**Comment by rubyowo** [comment]
right. though how would we add it into the youtube repo?
would it be a separate folder in `src/`?

**Comment by nekowinston** [comment]
I'd like @elkrien's opinion on this, since they're the maintainer for that repository.

**Comment by elkrien** [comment]
It's up to You @rubyowo. If You want to add it to YouTube repo I suggest putting it to src and assets and update Readme. If You wish I will add You to YouTube owners (if I can) and You will be able to make changes. 
But don't know If it won't be easier to have it in separate repo like it is right now. Will be easier for You just to transfer repo to Catppuccin organization instead doing so many changes. Also from user's perspective I think it will be easier to find and read install instructions if this will be separate repos.

**Comment by rubyowo** [comment]
It is I again, this time knowing what I would like. It'll be easier to maintain if in a separate repo, and now that it isn't just one single file anymore, it makes more sense, so I'd like to transfer it in rather than just adding it to the youtube repo

**Comment by nekowinston** [comment]
@rubyowo if you want a separate repository so you can add more functionality & track issues easier, that's fine with me.

You should have permissions to transfer already :slightly_smiling_face: 

Repo looks good.

**Comment by rubyowo** [comment]
thanks.
