### ISSUE TITLE
Godot

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/catppuccin#1973]
### Link to repository

https://github.com/boranroni/godot-engine

### Screenshots

![image](https://user-images.githubusercontent.com/58985301/225300109-073a3790-9a06-4678-88e7-5d981f38daf2.png)

### Any additional comments?

**Discussed in https://github.com/catppuccin/catppuccin/discussions/1859**

Originally posted by **zt64** November 30, 2022

Repository author: @boranroni

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by mustafakhalaf-git** [comment]
Based

**Comment by mustafakhalaf-git** [comment]
I might review this myself maybe and see how will it colors Godot, is this the entire editor or just the code part?

**Comment by mustafakhalaf-git** [comment]
Hmm interesting, it seems like u swapped the files of frappe and macchiato
![image](https://user-images.githubusercontent.com/42213155/233792619-54b4cfba-02b2-4864-bb4b-dbb927243299.png)

because 24273a is the base color of macchaito, not frappe

**Comment by sgoudham** [comment]
So @backwardspy is pretty interested in testing it out. 

From the discussions that we've had, we came to the conclusion that this port really needs to support Godot 4 before it can be merged into the organisation. Also we recently merged in the new [code editor](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#code-editors) style guide which this port needs to follow.

**Comment by backwardspy** [comment]
> Hmm interesting, it seems like u swapped the files of frappe and macchiato ![image](https://user-images.githubusercontent.com/42213155/233792619-54b4cfba-02b2-4864-bb4b-dbb927243299.png)
> 
> because 24273a is the base color of macchaito, not frappe

i noticed this too, there are also colours in the other themes (primarily latte, if i recall correctly,) that are taken from macchiato/frappé too. i think once those are fixed and godot 4 support has been implemented this will be ready for final review & transfer.

**Comment by mustafakhalaf-git** [comment]
Adding GD4 support isn't that hard, I'll see if I can make a PR including both GD3.5 and GD4 while abiding by the new style guide

**Comment by backwardspy** [comment]
> would be good if the repo is renamed to just `godot` instead of `godot-engine`

agreed

**Comment by backwardspy** [comment]
@boranroni @GitMuslim do you have any updates on this?

**Comment by GitMuslim** [comment]
not really, he's been taking a break I guess

Honestly the theme he made is only for the text editor, not for the whole engine, and it may not be following all the guidelines listed, maybe sometime I or someone else will will make the full thing, or maybe he will come back

but for now keep this issue open

**Comment by backwardspy** [comment]
i've updated the port with godot 4 support, interface theme settings, and theme file generation via palette JSON.

https://github.com/backwardspy/ctp-godot

as per the readme, godot 3.x support lives on the `godot3` branch.

cc @sgoudham

**Comment by sgoudham** [comment]
Great work @backwardspy! Just tried out the port there and everything looks lovely. 

I'm happy for it to be transferred over to the organisation!

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by sgoudham** [comment]
Closed by https://github.com/catppuccin/catppuccin/pull/2175
