### ISSUE TITLE
Brave search

### ISSUE THREAD

**Issue by nonetrix** [catppuccin/catppuccin#198]
**Are you available to help in the creation of this port? 😄 (optional)**
I am good at CSS not colors

**Additional context 📷 (optional)**
![Screenshot from 2022-07-17 00-06-03](https://user-images.githubusercontent.com/45698918/179384705-420ef8c1-d677-4b43-9e09-68c805fe773f.png)

**Comment by WitherCubes** [comment]
You can check out the [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md) and other ports like [Whoogle](https://github.com/catppuccin/whoogle), [MonkeyType](https://github.com/catppuccin/monkeytype), [Youtube](https://github.com/catppuccin/youtube), etc.

**Comment by ndsboy** [comment]
Hi there, I have created a [draft](https://github.com/ndsboy/brave-search), overriding the css variables. I tried to match the style guide, but for some variables I could not find the concrete usage. I'd appreciate your feedback.

**Comment by sgoudham** [comment]
Hey @ndsboy, just checked out the repository and honestly looks great from what I looked at!

One thing for the repository is we should have a stylus install button, like the [DeepL](https://github.com/catppuccin/deepl) port shown below:
![image](https://user-images.githubusercontent.com/58985301/209737751-36920e42-412f-4ced-9af0-e018a66f21d0.png)
	I can see that the install link already exists but would be nice in the button format above ^^
	
Other than that, I actually think the port is more or less good to be transferred.

**Comment by ndsboy** [comment]
Hi @sgoudham, thanks for the feedback. I have added the button, it's a nice addition for stylus repos.

**Comment by sgoudham** [comment]
Thanks for adding that! @ndsboy 

@nekowinston will now send you an invite to the organisation and you should be able to transfer across the repo! Thanks for your work :D

**Comment by ndsboy** [comment]
I'm already a member of the organization, so I can just transfer it now :)
