### ISSUE TITLE
JetBrains Fleet

### ISSUE THREAD

**Issue by kkrypt0nn** [catppuccin/catppuccin#1982]
### Link to repository

https://github.com/kkrypt0nn/jetbrains-fleet

### Screenshots

https://raw.githubusercontent.com/kkrypt0nn/jetbrains-fleet/main/assets/previews/preview.webp

https://raw.githubusercontent.com/kkrypt0nn/jetbrains-fleet/main/assets/previews/latte.webp

https://raw.githubusercontent.com/kkrypt0nn/jetbrains-fleet/main/assets/previews/frappe.webp

https://raw.githubusercontent.com/kkrypt0nn/jetbrains-fleet/main/assets/previews/macchiato.webp

https://raw.githubusercontent.com/kkrypt0nn/jetbrains-fleet/main/assets/previews/mocha.webp

### Any additional comments?

Documentation on creating themes in Fleet is very limited so some colors may not fit the best at some places as I was unable to find where it was even being used, hence very open to suggestions on changing these if you find locations where colors don't fit at all.

Available in the Discord at `Krypton#7331` for discussions :D

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nekowinston** [comment]
Wow, thanks for working on this, this looks great!
Relevant discussion that we can close with this: #1893

I'll try to give it a go tomorrow!
