### ISSUE TITLE
Flow Launcher

### ISSUE THREAD

**Issue by ghostx31** [catppuccin/catppuccin#1983]
### Link to repository
[Syndrizzle](https://github.com/Syndrizzle) has created the port for Flow Launcher. The repository is present at [Syndrizzle/flow-launcher](https://github.com/Syndrizzle/flow-launcher). 

### Screenshots

![image](https://user-images.githubusercontent.com/68803793/226680628-7da2d5f2-b034-4ccc-9835-d90b01730ec2.png)

### Any additional comments?

**Discussed in https://github.com/catppuccin/catppuccin/discussions/1902**

Originally posted by **FnigePython** February  3, 2023

**Comment by ghostx31** [comment]
Can we not have `é` in the file name?

**Comment by andreasgrafen** [comment]
Gave it a quick test run and everythings seems like it should. Approval granted. :D

**Comment by Syndrizzle** [comment]
> Can we not have `é` in the file name?

Okay I've fixed that

**Comment by ghostx31** [comment]
Cool. Feel free to transfer then.
