### ISSUE TITLE
Gitea

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/catppuccin#1984]
### Link to repository

https://github.com/nekowinston/catppuccin-gitea

### Screenshots

![preview](https://gitea.catppuccin.com/nekowinston/catppuccin-gitea/media/branch/main/assets/preview.webp)

<details>
<summary>🌻 Latte</summary>
<img src="assets/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="assets/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="assets/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="assets/mocha.webp"/>
</details>

### Any additional comments?

Made from scratch, based on arc-green, for the latest 1.19.0 version. 👍

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Heya :wave:

I've been using this for the past few days it looks **amazing**! I've sent you an invite to the org so feel free to transfer it over when you have a chance! 

We'll close off the issue once it's added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!

Thanks again for doing this! :heart:

**Comment by nekowinston** [comment]
Closed via #1990
