### ISSUE TITLE
Microsoft PowerPoint (Slides)

### ISSUE THREAD

**Issue by kkrypt0nn** [catppuccin/catppuccin#1998]
### Link to repository

https://github.com/kkrypt0nn/powerpoint

### Screenshots

https://raw.githubusercontent.com/kkrypt0nn/powerpoint/main/assets/previews/preview.webp

https://raw.githubusercontent.com/kkrypt0nn/powerpoint/main/assets/previews/latte.webp

https://raw.githubusercontent.com/kkrypt0nn/powerpoint/main/assets/previews/frappe.webp

https://raw.githubusercontent.com/kkrypt0nn/powerpoint/main/assets/previews/macchiato.webp

https://raw.githubusercontent.com/kkrypt0nn/powerpoint/main/assets/previews/mocha.webp

### Any additional comments?

Who does not want to have a presentation with the amazing Catppuccin theme in their slides <img src="https://cdn.discordapp.com/emojis/1008407053062123540.webp?size=96&quality=lossless" height="20px" width="20px" />

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by isabelroses** [comment]
I love it. And I converted some of my slides to it. Just one question. Is it possible to change the default font here:
![image](https://user-images.githubusercontent.com/71222764/228919863-6ff5bf43-b035-4d10-84ba-f080093cbce5.png)

**Comment by kkrypt0nn** [comment]
Don't think it is, same for the colors available in the palette - they are very restrained - which means people will need to get the HEX values themselves to add the color for some things.

PowerPoint is essentially really bad for theming, what can be done though is to make a starter template with some of the most basic components, e.g. a table in your case.

**Comment by isabelroses** [comment]
> PowerPoint is essentially really bad for theming, what can be done though is to make a starter template with some of the most basic components, e.g. a table in your case.

It is what it is I guess.

**Comment by kkrypt0nn** [comment]
I do think it makes more sense to rename it to `powerpoint-slides` as well, that will prevent people from misunderstanding the theme as it's not a theme for PowerPoint itself.

cc @sgoudham

**Comment by andreasgrafen** [comment]
> I do think it makes more sense to rename it to `powerpoint-slides` if you're fine with it, that will prevent people from misunderstanding the theme as it's not a theme for PowerPoint itself.

I came here to mention this, and I'm happy that you brought it up yourself. It kinda goes against our naming convention, but I'd still stronly favour the longer version for the sake of clarity.

Furthermore we maybe want to look at a way to make the Previews a little bit more interesting. I'm not 100% sure as to how that should be done, but right now they almost feel a little soul-less?
