### ISSUE TITLE
Port request: VSCode

### ISSUE THREAD

**Issue by Gingeh** [catppuccin/catppuccin#2]
I would love to use this as a theme for VSCode/VSCodium

**Comment by benomine** [comment]
Hi there, I did a very dirty quick port of your theme for vscode.
If you'd like i can pr you the code and after you can tweak it as you like.

Let me know.

**Comment by benomine** [comment]
Gingeh beat me to it, it's fine :)

**Comment by Gingeh** [comment]
> Gingeh beat me to it, it's fine :) 

Ah, sorry about that

**Comment by benomine** [comment]
> 

Don't worry, it's fine, you did a better job than I did anyway. Way more complete. I did just the basic stuff nothing more.

**Comment by VictorTennekes** [comment]
I think this can be closed when we've merged the newest version of the vscode port.
