### ISSUE TITLE
Squirrel

### ISSUE THREAD

**Issue by moseeking** [catppuccin/catppuccin#2003]
### Link to repository

https://github.com/moseeking/squirrel.git

### Screenshots

<img width="520" alt="frappe" src="https://user-images.githubusercontent.com/17546266/229298020-0e211136-02d3-4752-a4e3-1bbdb7dd955b.png">
<img width="520" alt="latte" src="https://user-images.githubusercontent.com/17546266/229298027-d3ee3323-d505-456b-9697-7dd57ba8e838.png">
<img width="520" alt="macchiato" src="https://user-images.githubusercontent.com/17546266/229298028-2be5a681-ddb5-44b1-9531-831277c26917.png">
<img width="520" alt="mocha" src="https://user-images.githubusercontent.com/17546266/229298030-13b4cfa2-c0c2-420a-a848-36ba457cc850.png">

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hi @moseeking, thanks for your contribution! if you're still interested in maintaining this port, i would like to request that you split the README into two files, one for each language. we haven't really tackled any form of localisation yet in catppuccin, so your port would be the first. for readme files we're thinking of the following scheme:

- `README.md` - english
- `README.<country code>.md` - other languages

you can see an example of this localisation scheme in the [github-cheat-sheet](https://github.com/tiimgreen/github-cheat-sheet) repository.

if you are no longer interested in maintaining this port, let me know and we can close the issue.

thanks!

**Comment by moseeking** [comment]
Certainly! I have submitted the changes to the README file for review.

**Comment by backwardspy** [comment]
i think that looks really good!

one more thing @sgoudham mentioned about the preview screenshots - we usually go with the same accent colour (mauve) for all four previews, to help give a more consistent idea of what the different flavours/variants look like.

could you update the preview images & theme files to all use mauve for the selected input?

really appreciate all your work on this, it looks great. i think with the previews changed we'd be happy to get this transferred into the organisation.

**Comment by backwardspy** [comment]
nice work! i'm happy with this as it stands.

@catppuccin/core ready for org invite.

**Comment by sgoudham** [comment]
Thanks @backwardspy for reviewing, I've invited to you to the organisation @moseeking 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
