### ISSUE TITLE
🍅 Pomotroid

### ISSUE THREAD

**Issue by coldenate** [catppuccin/catppuccin#2011]
### Link to repository

https://github.com/coldenate/pomotroid.git

## Previews

<details>
<summary>🌻 Latte</summary>
<img src="https://raw.githubusercontent.com/coldenate/pomotroid/main/assets/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://raw.githubusercontent.com/coldenate/pomotroid/main/assets/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://raw.githubusercontent.com/coldenate/pomotroid/main/assets/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://raw.githubusercontent.com/coldenate/pomotroid/main/assets/mocha.webp"/>
</details>

### Any additional comments?

Time to be productive!! (lie) ![](https://cdn.betterttv.net/emote/5f1b0186cf6d2144653d2970/1x.gif)

I'll need to test the installation on Linux and Windows. Currently running a shell script. 

Thank you,
coldenate

### Submission Guidelines

- [x] I have read and followed Catppuccin's submission guidelines.

**Comment by isabelroses** [comment]
Hello, 

Seen how the application can be installed on windows without the need of `CYGWIN` and etc, it would be better if the bash script was converted to python. Furthermore using python would lead to less dependencies issues for different uses as the same environment can be created.

Other then that the port is looking really clean, thanks for your hard work.

**Comment by sgoudham** [comment]
Just to add onto the above, it doesn't have to be python but I think it would be good here since it's very familiar to a large number of people and we have an existing [library](https://github.com/catppuccin/python) that can give you the colours within the code - it means we don't have to duplicate the palette json in the repository :+1:

**Comment by coldenate** [comment]
Righty! 
I have written the script in python! 👍 
The main dependencies are `Rich`, `ctp`, and a prompt toolkit for typeahead when entering an accent color. @sgoudham @isabelroses

**Comment by isabelroses** [comment]
> The main dependencies are `Rich`, `ctp`

Could you make a `reqirements.txt` this way the user can run `pip install -r reqirements.txt`. 
Thank you.

**Comment by coldenate** [comment]
Yes. I will freeze the dependencies. 
I'll look into that oddity with the appdir. Wasn't expecting that. 
In my testing it does work on MacOS. I have the ability to simulate end-user on Windows and Linux, so I'll let you know how that goes. 😅
Thank you for reviewing the code! I appreciate it. 
@isabelroses

**Comment by coldenate** [comment]
I'll also fix the Catwalk. I was recently told that the catwalk has  a specific theme order.

**Comment by coldenate** [comment]
I added some new flags to the appdir construction that seem to fix the errors. @isabelroses 
In my testing on windows, I seemed to have consistent runs. 

## Super basic test-to-see-if-it-runs
- [x] MacOS (arm)
- [x] Windows (x86)
- [x] Linux (arm)

**Comment by isabelroses** [comment]
> In my testing on windows, I seemed to have consistent runs.

ill give it a test today or tomorrow, hopefully all is good.

**Comment by isabelroses** [comment]
> ill give it a test today or tomorrow, hopefully all is good.

Alright I'm happy to approve this. @sgoudham

**Comment by sgoudham** [comment]
I have a few comments that I'll get around to commenting later

**Comment by sgoudham** [comment]
Heya :wave:, apologies for the wait.
As mentioned above, just have a few comments:

<details>
<summary>I'm a little bit confused about the layout of the README</summary>
	
From the image shown below, I see that Installation Guide is a header with nothing inside of it. Looking inside the assets folder, I see that you've got a `iguide.webm` file which I'm guessing you wanted to show there. Additionally, the second FAQ question restates the usage which I don't think the user would find helpful.

It might be better to just remove the second question from the FAQ

![image](https://user-images.githubusercontent.com/58985301/235368586-fdae308d-f17d-4c26-807d-b6082f4271a7.png)

</details>

<details>
<summary>The IO Code in the python script seems verbose</summary>

In the image shown below, we're opening access two different times but I think this behaviour that you're looking can be reduced to one single `with` statement.
	
![image](https://user-images.githubusercontent.com/58985301/235368860-a2885bc4-50ff-4817-ae06-d12cdbba6062.png)
	
I think this can be reduced to as the behaviour of `'w'` is explained to be for only writing (an existing file with the same name will be erased). Although this also raises a question, what if the user has made some customisations to the theme? Do you want to override them anyways? You probably want to prompt the user if they want to continue to override the file if it already exists, if not then just write the file as normal.
	
I think the final version of the code might look like:
	
```python
if os.path.exists(theme_path):
	# prompt the user if they want to continue with the reading
	# if they say yes, go ahead write the file. If not, don't bother writing
else:
	write_files()

def write_files():
	with open(theme_path, "w", encoding="utf-8") as baked_json:
     	json.dump(base, baked_json, indent=4)
```

</details>

I think those were the main ones worth commenting on, other than that, looks nice and nice job! I think I'll be trying out this app :D

**Comment by coldenate** [comment]
Sweet! Thank you so much for those insights! I have implemented them!
@sgoudham 
I removed the progress bar entirely because it was a bit unnecessary.
The video isn't necessary either, so I removed it as well.

**Comment by sgoudham** [comment]
Sorry @coldenate for just now getting back to this. 

Nice job! I'm just looking at the code again and it would be good to ensure that people aren't forced to only use the Python installer to install the theme. 

I was thinking what if we had:

- `generate.py`:
   - `generate_themes()` -> Takes care of actually generating the themes and ideally returns 4 files as strings for each flavour
   - `write()` / `output()` (something along those lines) -> This would actually output the theme files to a `build` directory or equivalent in the repository
 - `install.py` -> Pretty much what you have now but the generation of the theme is de-coupled and stored within `generate.py` which you can call upon
 
De-coupling the generation of the theme and the installer logic would allow for a GitHub Actions workflow to run `generate.py` and release the JSON files as tagged releases. Then, in the README, you can mention that people can download the json files and manually configure it if they wish to do. 

What do you think?

**Comment by coldenate** [comment]
Yeah! That's a really good workflow for self-customization. It helps take the edge of the installer for managing all that. 
I'll get something out and see if it matches with what you're talking about! 
@sgoudham

**Comment by sgoudham** [comment]
Cool! I recently did something very similar with https://github.com/catppuccin/glamour which you might want to use as inspiration or a possible starting point.

**Comment by coldenate** [comment]
@sgoudham 
Just finished everything up! The code should mimic what you had in mind... 👀

**Comment by coldenate** [comment]
## Latest Compatibility Tests
- [x] Mac
- [ ] Linux
- [ ] Windows

**Comment by isabelroses** [comment]
> * [ ]  Windows

i can do this one

**Comment by isabelroses** [comment]
> i can do this one

I can confirm it works im just curious why all the files have a trailing `-`
![image](https://github.com/catppuccin/catppuccin/assets/71222764/b8290f30-ba90-4eb1-94d4-4827cef12ef7)

**Comment by coldenate** [comment]
> > i can do this one
> 
> 
> 
> I can confirm it works im just curious why all the files have a trailing `-`
> 
> ![image](https://github.com/catppuccin/catppuccin/assets/71222764/b8290f30-ba90-4eb1-94d4-4827cef12ef7)
> 
> 

@isabelroses Thanks for catching that. I'll look into it

**Comment by coldenate** [comment]
> > i can do this one
> 
> I can confirm it works im just curious why all the files have a trailing `-` ![image](https://user-images.githubusercontent.com/71222764/241725210-b8290f30-ba90-4eb1-94d4-4827cef12ef7.png)

@isabelroses Fixed as of [latest commit](https://github.com/coldenate/pomotroid/commit/c9e07eda1e1a4550f4d55216f3778625672b417a))

**Comment by sgoudham** [comment]
Apologies @coldenate, just got around to installing it myself. Everything looks good!
I'd just add a note in the README that files can be downloaded manually via releases (e.g. our [glamour port](https://github.com/catppuccin/glamour#usage))

However, I wouldn't consider that a blocker, feel free to transfer the repository over and create a PR adding it to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!

**Comment by coldenate** [comment]
Thank you for reviewing, @sgoudham @isabelroses!
The transfer is in progress.
