### ISSUE TITLE
catppuccin-wallpapers-git still exists on the AUR

### ISSUE THREAD

**Issue by CallMeEchoCodes** [catppuccin/catppuccin#2013]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### What is your concern?

since the wallpapers repo was remove you should prob remove this too :heart:

**Comment by ghostx31** [comment]
I have commented on the AUR page of the package. Let's see if it gets deleted this way or else, we would need to mail a trusted user on their public emails.

**Comment by perigoso** [comment]
Hi, I maintained that package, the correct way to get a package deleted (when that is the appropriate action) is to issue a deletion request, which can be done on the menu on the right of the package page (Submit Request), the request goes into a backlog and a trusted user eventually takes action.

I'll issue the request myself, just wanted to ask, were the wallpapers completely deprecated? as in, cappuccin no longer provides any wallpapers?

**Comment by sgoudham** [comment]
Hiya @perigoso, that's correct. Catppuccin no longer provides any wallpapers.

**Comment by isabelroses** [comment]
@sgoudham can you close this since the AUR package no longer exists: [link to search results](https://aur.archlinux.org/packages?O=0&SeB=nd&K=+catppuccin-wallpapers-git&outdated=&SB=p&SO=d&PP=50&submit=Go)

**Comment by perigoso** [comment]
Yes, the deletion request was accepted, sorry forgot to notify
