### ISSUE TITLE
Blender

### ISSUE THREAD

**Issue by codekisser** [catppuccin/catppuccin#2014]
### Link to repository

https://github.com/codekisser/blender

### Screenshots

<details>
<summary>🌻 Latte</summary>
<img src="https://raw.githubusercontent.com/codekisser/blender/main/assets/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://raw.githubusercontent.com/codekisser/blender/main/assets/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://raw.githubusercontent.com/codekisser/blender/main/assets/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://raw.githubusercontent.com/codekisser/blender/main/assets/mocha.webp"/>
</details>

### Any additional comments?

This might have to be put under GPL. I generated this theme based off of the default dark theme for Blender. I even have a a file generated by Blender in the repo (it is not included in the source code of Blender. It is a custom theme exported from Blender).

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Closing as author hasn't had any GitHub activity in over a year, happy to re-open if author gets back in touch with us.

**Comment by os3albert** [comment]
can I submit my own version of catppuccin for blender https://extensions.blender.org/themes/catppucin4blender/
