### ISSUE TITLE
Nilesoft Shell

### ISSUE THREAD

**Issue by jayylmao** [catppuccin/catppuccin#2015]
### Link to repository

https://github.com/jayylmao/catppuccin-nilesoft-shell

### Screenshots

<img width="347" alt="mocha" src="https://user-images.githubusercontent.com/73204320/233033050-8a637272-81f6-4e3b-84b3-503661d919f2.png">
<img width="327" alt="frappe" src="https://user-images.githubusercontent.com/73204320/233033056-20a6557d-2416-4d0a-b469-1833e3e0c424.png">
<img width="325" alt="latte" src="https://user-images.githubusercontent.com/73204320/233033058-fea13c32-8503-4f4a-8b16-f733ee9e085b.png">
<img width="344" alt="macchiato" src="https://user-images.githubusercontent.com/73204320/233033062-746df022-fc00-4e92-a65a-7bec765cf5c2.png">

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by isabelroses** [comment]
Hello,

1) Can you change the `assets\` to .webp
2) Can you change the sheld.io badges to point to `catppuccin/nilesoft-shell`
3) Is it possible to change this (disabled button)
![image](https://user-images.githubusercontent.com/71222764/233806941-62e830dc-4e68-48e7-8a9f-528a863008ed.png)

Thanks for your hard work so far.

**Comment by jayylmao** [comment]
sure, i'll get on that sometime later today.

**Comment by jayylmao** [comment]
ok, sorry for the delay. i changed the assets to webp and the URLs should be updated now. although i can't find that disabled button discoloration in your screenshot. you're using mocha sky, right?
<img width="229" alt="image" src="https://user-images.githubusercontent.com/73204320/234823067-53097877-c90c-4fda-b436-912eb5c13b26.png">

**Comment by isabelroses** [comment]
> you're using mocha sky, right?
I'm using sapphire, but if it is just a me issue that's fine.

**Comment by isabelroses** [comment]
> > you're using mocha sky, right?
> 
> I'm using sapphire, but if it is just a me issue that's fine.

I just checked the conf files and this is definitely just a me issue.
So I'm happy to approve this.

**Comment by sgoudham** [comment]
Thanks @isabelroses for testing it out. Looks good!
Feel free to transfer the repository into the organisation!

**Comment by jayylmao** [comment]
i transferred the repository into the organization.
