### ISSUE TITLE
Archcraft OS

### ISSUE THREAD

**Issue by vanillyn** [catppuccin/catppuccin#2019]
### Link to repository

https://github.com/vanillyn/archcraft

### Screenshots

![Frappe](https://user-images.githubusercontent.com/108785622/233737684-04556efd-5aae-486f-823e-ddc04229bdaa.png)
![Latte](https://user-images.githubusercontent.com/108785622/233737686-af40591e-cda7-4829-b1cb-c979ca9e7414.png)
![Macchiato](https://user-images.githubusercontent.com/108785622/233737687-2987360c-7136-4353-a0f9-2ee42c29d887.png)
![Mocha](https://user-images.githubusercontent.com/108785622/233737690-513abd01-bb9b-490e-ac5b-658c86cda8ed.png)

### Any additional comments?

Archcraft themes all of it's elements through a central theme.bash file, which I've used to apply to each of the themes, and I have also made an install script for people who are using Arch Linux.
Archcraft is an operating system (arch-based) centered around it's ricing. 
I needed to use the Catppuccin GTK theme, like [Regolith](https://github.com/catppuccin/regolith).
Discussion is #1935 

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hey! thanks for your submission, the project looks really cool!
we've discussed where this sits alongside other catppuccin ports and come to the conclusion that it best belongs in the showcase. if you are still interested in featuring this project then please feel free to [PR it into the showcase](https://github.com/catppuccin/catppuccin/pull/2268/files).

thanks!

**Comment by backwardspy** [comment]
disregard all that ⬆️ just some github ui shenanigans :)
