### ISSUE TITLE
Starship Shell

### ISSUE THREAD

**Issue by BlueFalconHD** [catppuccin/catppuccin#203]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
https://starship.rs
Themable via starship.toml.

**Comment by nekowinston** [comment]
Closing this after considering that #145 & #192 were marked as not planned as well.

Shell prompts tend to be highly customized anyhow, and at the moment we only concern ourselves with syntax highlighting.
