### ISSUE TITLE
MusicBee

### ISSUE THREAD

**Issue by James-McK** [catppuccin/catppuccin#2043]
### Link to repository

https://github.com/James-McK/catppuccin-musicbee

### Screenshots

![Screenshot showing all 4 palettes](https://github.com/catppuccin/catppuccin/assets/56560271/eb828430-c66c-406d-8748-a33ace2d5f3e)
![Settings menu](https://github.com/catppuccin/catppuccin/assets/56560271/c69a92cd-46cf-40db-b540-3f2eb8315642)
![Macchiato red theme with wavebar](https://github.com/catppuccin/catppuccin/assets/56560271/461a0524-2a93-4cde-8db0-4037cfaea21e)
![Latte green theme with accented bar](https://github.com/catppuccin/catppuccin/assets/56560271/b0fc47d5-96e6-46f4-9bc5-b917d9fdc412)
![Screenshot of the music explorer tab, using the mocha blue unaccented bar theme](https://github.com/catppuccin/catppuccin/assets/56560271/5eab61f2-1b14-4fd8-b135-4e398a7267f0)
![Mini player with mocha yellow theme](https://github.com/catppuccin/catppuccin/assets/56560271/ed97f806-c2b8-470b-98fe-e4812d6a4ae9)

### Any additional comments?

Covers all 4 palettes, and every accent colour from rosewater to lavender, and versions for both an accented or unaccented player controls bar.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Great work on this!
I've sent you an invite to the organisation, feel free to transfer it over when you have the time to do so!

We'll close off this issue once it's added to the [`ports.yml`](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml) in a following PR.

**Comment by James-McK** [comment]
I've transferred the repository over now, thanks!
