### ISSUE TITLE
Yakuake

### ISSUE THREAD

**Issue by southqaw** [catppuccin/catppuccin#2046]
### Link to repository

https://github.com/southqaw/yakuake

### Screenshots

![preview](https://github.com/catppuccin/catppuccin/assets/2060786/f47c6ca9-e33f-4946-863b-00228383575c)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by Starcr0ss** [comment]
Can this be accepted as an official port? It works really well and looks beautiful!

**Comment by sgoudham** [comment]
Hey :wave: @Starcr0ss @southqaw, apologies for not looking at this earlier.

I wanted to try it out quickly for myself and so I downloaded it and followed the instructions on the README, however, I'm seeing the following error message:

![image](https://github.com/catppuccin/catppuccin/assets/58985301/9f6f4c17-a0c7-4f37-96d7-c16e32d2af1c)

Is this a common error? I can't find much about that error online aside from a [2008 forum post with no answer](https://ubuntuforums.org/archive/index.php/t-802640.html), assuming it's just my system (Pop_OS) ?

**Comment by Starcr0ss** [comment]
@sgoudham this sounds like a weird OS issue, works fine for me. Try installing `tar` with `apt`?

**Comment by sgoudham** [comment]
I'd be very surprised at any unix distro that doesn't have `tar` installed 😄 @Starcr0ss. In any case, my only comment is that the [README badge URLs](https://github.com/southqaw/yakuake/blob/1dca026203e436180a805ef508f7b62959b38c64/README.md?plain=1#L9-L11) need changing from `catppuccin/template` to `catppuccin/yakuake` but that can be carried out afterwards.

I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164
