### ISSUE TITLE
Broken staff link in port-creation.md

### ISSUE THREAD

**Issue by wherewith** [catppuccin/catppuccin#2058]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

The link [https://github.com/orgs/catppuccin/teams/staff/members](https://github.com/orgs/catppuccin/teams/staff/members) for the staff team in **./docs/port-creation.md** is broken. The broken links are on lines 86 and 94 (as far as I can tell, there may be more). I couldn't replace the link with anything, as far as I can tell the link [https://github.com/orgs/catppuccin](https://github.com/orgs/catppuccin) now points directly to [https://github.com/catppuccin](https://github.com/orgs/catppuccin). Sorry if this is the incorrect type of issue, I couldn't create a PR with a change to the docs since I don't know what to replace the link with. Thanks!

**Comment by backwardspy** [comment]
@catppuccin/core looks like this link only works if you're logged in as a member of the team. perhaps we could link to [catppuccin/community](https://github.com/catppuccin/community#current-structure) instead?

**Comment by ghostx31** [comment]
I think we can redirect the URL to https://github.com/catppuccin/community/#staff

**Comment by backwardspy** [comment]
thanks for raising this @wherewith!
