### ISSUE TITLE
DioHub

### ISSUE THREAD

**Issue by UrNightmaree** [catppuccin/catppuccin#2059]
### Link to repository

https://github.com/UrNightmaree/catppuccin-diohub

### Screenshots

![latte](https://github.com/catppuccin/catppuccin/assets/71205197/5536888e-0802-47be-b70b-ddf38c1ba4ae)
![frappe](https://github.com/catppuccin/catppuccin/assets/71205197/6fb6bd48-9560-49f7-90a5-35e1023bcec0)
![macchiato](https://github.com/catppuccin/catppuccin/assets/71205197/fc7cde86-8669-44fd-8f7c-6f432eef885e)
![mocha](https://github.com/catppuccin/catppuccin/assets/71205197/f9b96a47-5aa5-4164-b4e6-d88408daed34)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by isabelroses** [comment]
Hello,

Good work so far I just have some things to ask about:
1) I noticed on your README there is no mocha preview present
2) Could it be possible to replicate this for other accent colours then have an install process similar to [catppuccin/firefox](https://github.com/catppuccin/firefox#-basic-install-recommended)
3) Also just curious about this section of the latte preview as this is almost unreadable is it possible to alter this?
![image](https://github.com/catppuccin/catppuccin/assets/71222764/20aa648a-4c79-4e2d-85bb-0436b42a2fa8)

Thanks again for the hard work

**Comment by UrNightmaree** [comment]
1. Thank you for telling me, I didn't realized that soon.
2. Yes it is possible, put might take a while since I need to write all hex colors into a JSON file (see `flavors` in the repository)
3. Seems to be screenshot issue, not related to the theme itself.

**Comment by isabelroses** [comment]
> 2. Yes it is possible, put might take a while since I need to write all hex colors into a JSON file (see `flavors` in the repository)

You could create a python script using [catppuccin/python](https://github.com/catppuccin/python) to make that alot faster and improved incase the colours change.

**Comment by UrNightmaree** [comment]
> > 2. Yes it is possible, put might take a while since I need to write all hex colors into a JSON file (see `flavors` in the repository)
> 
> You could create a python script using [catppuccin/python](https://github.com/catppuccin/python) to make that alot faster and improved incase the colours change.

Hmm, I'll consider it. But I have a plan to make Catppuccin library for Bash, so I could integrate it with `Bakefile.sh`

**Comment by UrNightmaree** [comment]
All things should be done now.
1. Fixed `<img />` tag for Mocha preview
2. Added  variations of Accent color for Mocha, Macchiato, Frappe and Latte.
3. Updated Screenshot for Latte.

**Comment by isabelroses** [comment]
I only have 1 gripe and its specific to latte, all the background text is a bit hard to read, this is probably easiest to notice with the search bar.

**Comment by UrNightmaree** [comment]
> I only have 1 gripe and its specific to latte, all the background text is a bit hard to read, this is probably easiest to notice with the search bar.

DioHub is still in Beta phase, so it's expected some colors are not affected to other things. I also found that while testing Latte theme.

**Comment by UrNightmaree** [comment]
Oh I found the problem now, I put the `fadedn` color in reverse. Let me fix it...

**Comment by UrNightmaree** [comment]
Done! All themes should be fixed now. Let me know if there's anything that should be fixed.
![preview](https://github.com/UrNightmaree/catppuccin-diohub/raw/master/assets/preview.webp)
![latte](https://github.com/UrNightmaree/catppuccin-diohub/raw/master/assets/latte.webp)
![frappe](https://github.com/UrNightmaree/catppuccin-diohub/raw/master/assets/frappe.webp)
![macchiato](https://github.com/UrNightmaree/catppuccin-diohub/raw/master/assets/macchiato.webp)
![mocha](https://github.com/UrNightmaree/catppuccin-diohub/raw/master/assets/mocha.webp)

**Comment by isabelroses** [comment]
> Done! All themes should be fixed now. Let me know if there's anything that should be fixed.

I have nothing left to critique.
Thanks so far.
@catppuccin/core anyone willing to approve?

**Comment by sgoudham** [comment]
Hiya 👋  @UrNightmaree

I'm happy to trust @isabelroses on this one. My only nitpicks are the re-definition of Catppuccin hex codes and the main README screenshot being a bit too long to scroll but it seems silly to block the transfer based on that. I'd be interested in raising the above points as issues on the repository if that's alright!

With the above points aside, feel free to transfer the repository to the organisation! I've just sent you an invite which should appear in your email. **We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

Thank you for your work :D

**Comment by UrNightmaree** [comment]
Thank you @sgoudham, @isabelroses!  for reviewing! Transfer is in progress...
