### ISSUE TITLE
Ueli

### ISSUE THREAD

**Issue by lighttigerXIV** [catppuccin/catppuccin#2060]
### Link to repository

https://github.com/lighttigerXIV/ueli

### Screenshots

![image](https://github.com/catppuccin/catppuccin/assets/35658492/a5d0b3b8-7bd2-4062-a664-fbe4ea4b7518)
![image](https://github.com/catppuccin/catppuccin/assets/35658492/044d2bb6-7b57-4863-9c61-04a61d20ba34)
![image](https://github.com/catppuccin/catppuccin/assets/35658492/e80f0bc1-67fd-47d7-b7d0-e36014e7dda4)
![image](https://github.com/catppuccin/catppuccin/assets/35658492/a3a5cdea-3744-4534-a45a-b70199060b45)
![image](https://github.com/catppuccin/catppuccin/assets/35658492/51a54614-545a-40d7-96f3-4f2316b4fe0a)

### Any additional comments?

It should be good to go. I need to change the previews location when the repo is moved  but that's only it.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Seems fine from the colours defined and the screenshots above. Feel free to transfer across the repository into the organisation! I would like to maybe see the files generated via a palette library but that can be raised via an issue on the repository itself, thanks for your work!

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by sgoudham** [comment]
The repository looks good now! Feel free to transfer into the organisation. 

As I mentioned earlier, it would be great to use one of our palette libraries to build/generate the JSON files to reduce the manual effort of any further changes to the palette and/or port.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by lighttigerXIV** [comment]
> 

Yeah i could easily do a rust or python script to do that but for now it will stay like this
