### ISSUE TITLE
ghostwriter

### ISSUE THREAD

**Issue by bagelwaffle** [catppuccin/catppuccin#2062]
### Link to repository

https://github.com/bagelwaffle/ghostwriter/

### Screenshots

![showcase](https://github.com/catppuccin/catppuccin/assets/134188288/72da0cec-7a91-465b-aba3-22e47d75cf17)

### Any additional comments?

I have no idea what the accent colour options does, might be just because I am on a tiling window manager idk. If anyone knows what it does, let me know.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by isabelroses** [comment]
Hellooo,

Thanks for your hard work so far. So changes I would like to see:

1) support for other platforms in the docs. Currently it only shows that Linux is customisable. However, the app is themeable on every platfrom it supports. Shown as bellow:
```Windows: C:\Users<your_user_name>\AppData\Roaming\ghostwriter\themes
Windows portable mode: <your_ghostwriter_portable_folder>\data\themes
GNU/Linux: ~/.config/ghostwriter/themes
macOS: ~/Library/Application Support/ghostwriter/themes```
2) Here the sapphire theme there is sapphire used for the numbers but the link uses blue (links should be in sapphire).
![image](https://github.com/catppuccin/catppuccin/assets/71222764/4b214d34-12ff-454f-b9b4-b234bff7917c)
3) the latte cursor, feels out of place to me as it doesn't fit with the previous standard that I see in any of the dark themes.
![image](https://github.com/catppuccin/catppuccin/assets/71222764/e18ba4fe-d9e1-43b6-b025-1441154b1de1)
4) Relating to latte (mocha) and sapphire again, the scrollbar appears to be blue rather then sapphire unlike in mocha which is sapphire.
![image](https://github.com/catppuccin/catppuccin/assets/71222764/7391c670-f632-4ad8-9f39-0ba2cbf8de85)
5) Finally to make this whole creation of the json files easier would it be possible to create a script that would generate them perhaps using github.com/catppuccin/python or other libraries.

Thanks again for your hard work. 👍

**Comment by bagelwaffle** [comment]
Thanks for the response,

1. I wasn’t aware it was available for any systems other than Linux, seeing that it is a KDE application haha. I’ll add it to the docs when I get home.

2. 3. 4. 
I’ll take a look at it later

5. I have tried puccinier from the catpuccin toolbox, but it didn’t end up so well, as it converted everything including the latte stuff. I haven’t gotten to learning python yet, but I’ll definitely give catppuccin/python a try!

Thanks again for reviewing the port! <3

**Comment by bagelwaffle** [comment]
Forgot to ask this earlier, but what do you think about the way the json files are distributed? Currently, they’re all thrown in a single zip file and put in the ”release” thing, and it might be a little difficult to find the theme you want.

Thanks!

**Comment by isabelroses** [comment]
> Forgot to ask this earlier, but what do you think about the way the json files are distributed? Currently, they’re all thrown in a single zip file and put in the ”release” thing, and it might be a little difficult to find the theme you want. Thanks!

[catppuccin/firefox](https://github.com/catppuccin/firefox/tree/main/dist) has the files distributed by theme, then accent. But in releases can be found individually
meanwhile [catppuccin/gitea](https://github.com/catppuccin/gitea/releases/tag/v0.2.1) places them all into one folder

So it is up to you, though personally i would leave it as is so that a user can just install them all and select the one they wish within the application.

**Comment by bagelwaffle** [comment]
@isabelroses 
Hey! I am a bit confused here

2, 3 - I followed the [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md) which says to use blue for links and rosewater for cursors. That is what I did, and I do agree that the rosewater cursor looks pretty odd. I can perhaps do what [catppuccin/cursors](https://github.com/catppuccin/cursors) is doing, which is using the accent colour as the cursor colour.

Regarding links, I did what the style guide said to do, and I don't quite think it's a good idea to use the accent colour as the highlight colour for links, as someone using a "non-standard colour?" like yellow would have yellow links.

4 - The scrollbar uses the colour that is set for links, which means that to change the colour for the scrollbar, you must also change the colour for links, which as I mentioned above, is not a good idea IMO

**Comment by isabelroses** [comment]
> use blue for links 

That's okay then I thought they had changed/updated this post a discussion but leave it as is then.

> rosewater for cursors

This i didn't know so that's my bad.

> 4 - The scrollbar uses the colour that is set for links

That's fine then.

**Comment by bagelwaffle** [comment]
So.....Is the port ready for transfer?

Thonks

**Comment by sgoudham** [comment]
Hey 👋 @bagelwaffle  
Nice work! Just a few comments from me:

1. I just had a look at the repository, a little bit confused about the structure of the repository as I don't actually see any JSON files there but only in the release. Could you please upload the source JSON files too? And as @isabelroses mentioned, it would be great to hopefully auto-generate those files with our palette libraries.


2. > Regarding links, I did what the style guide said to do, and I don't think it's a good idea to use the accent colour as the highlight colour for links, as someone using a "non-standard colour?" like yellow would have yellow links.

	Regarding the above comment, I'm slightly confused as I can't see where the style guide table mentions accent colour links. In the code editor section, I believe the markdown should strive to follow this: (while, of course, accounting for the limitations of ghostwriter)

	![image](https://github.com/catppuccin/catppuccin/assets/58985301/2b37aec2-e3c1-4bca-99c3-5fb06dedc171)

3. Just one other thing, it might be nice to decouple the scrollbar from the link colours? It seems a bit odd to tie in the scrollbar with the accent colour when I haven't really seen that before. I believe we usually try to go for something in the ranges of `overlay` or `surface` from within the palette. However, with that being said, the accented bars might be a nice touch and if you feel like they should be kept, feel free to do so.

**Comment by bagelwaffle** [comment]
Hey @sgoudham!

1. I have added the files to [colours](https://github.com/bagelwaffle/ghostwriter/tree/main/colours). I haven't really figured out how to use the libraries.
2. There isn't any mention about accent colour links, I was just confused about isablerose's comment. Since ghostwriter only allows me to set normal links. I used blue.
3. It is not possible (at least no option that I am aware of) to change the scrollbar colour without changing the link colour. It uses the link colour, and to test this, I changed link to red and the scrollbar turned red

Here are all the options that ghostwriter allows me to change:
![2023-06-11T12:00:03,951935530-07:00](https://github.com/catppuccin/catppuccin/assets/134188288/f4ecbb41-cbea-46b8-ba47-c5430cd6d70d)

**Comment by isabelroses** [comment]
> 2. There isn't any mention about accent colour links, I was just confused about isablerose's comment. Since ghostwriter only allows me to set normal links. I used blue.

That's my bad, I think a poor choice of wording from me. 
I was just curious about the links using `blue` rather than `sapphire` but it has come to my attention that this change has never gone through.

**Comment by bagelwaffle** [comment]
Hey @sgoudham,
Is there anything else you would like me to fix?

**Comment by sgoudham** [comment]
> 1. I have added the files to [colours](https://github.com/bagelwaffle/ghostwriter/tree/main/colours). I haven't really figured out how to use the libraries.

No worries! Thanks for uploading them. I have some ideas in mind for making it more maintainable without necessarily using the palette libraries themselves. 

> 2. There isn't any mention about accent colour links, I was just confused about isablerose's comment. Since ghostwriter only allows me to set normal links. I used blue.

Blue follows the style guide so happy with that!

3. It is not possible (at least no option that I am aware of) to change the scrollbar colour without changing the link colour. It uses the link colour, and to test this, I changed link to red and the scrollbar turned red

Oh, that's quite interesting. Don't worry about changing them :+1: 

<hr>

The options look good! I would just update **Emphasis** to be maroon to fall in line with [Neovim](https://github.com/catppuccin/nvim/blob/2df7036c5c303c9184869936e40ca18935e4afcb/lua/catppuccin/groups/integrations/treesitter.lua#L96)

**Comment by bagelwaffle** [comment]
@sgoudham
I have changed ***emphasis*** to maroon.

**Comment by bagelwaffle** [comment]
@sgoudham 

The images and the "lavendar" typo has been fixed :smile:

**Comment by sgoudham** [comment]
Nice job! I'm happy for it to be transferred over to the organisation!

You should get an invitation to join the organisation via email, accept it and transfer the repository to "Catppuccin" as specified [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account).

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**
