### ISSUE TITLE
Wrong naming and color preview images on Style Guide

### ISSUE THREAD

**Issue by d3r1n** [catppuccin/catppuccin#2066]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md

There's no 2nd variation of any color. There are two first variation of that color in the table and the color preview images (swatches?) are also wrong.

**Comment by backwardspy** [comment]
hey! thanks for raising this. are you referring to the surface/overlay elements?
those were just fixed in d7a1918a23fb28e912bfd721eedef0ff452db872
feel free to re-open this with more details if this wasn't your issue.

**Comment by d3r1n** [comment]
Yep, I was referring to those, thanks!
