### ISSUE TITLE
After indent depth 10, theme inserts uneccesary line breaks when editing

### ISSUE THREAD

**Issue by Josh5A** [catppuccin/catppuccin#2086]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

When I get 10 indents deep with lists, the theme starts adding an unnecessary line break in editing view, that goes away in reading mode…

Editing:
![image](https://github.com/catppuccin/catppuccin/assets/1118503/fe61eee1-3e84-4b6b-9a1a-b45004ab4934)

Reading:
![image](https://github.com/catppuccin/catppuccin/assets/1118503/07b8172a-5f61-476f-9106-b455af8b1b77)

**Comment by nekowinston** [comment]
Hey there, this is our central repo for creating and accepting new ports; please open an issue in the relevant port repo.
