### ISSUE TITLE
Glaze WM

### ISSUE THREAD

**Issue by fathulfahmy** [catppuccin/catppuccin#2088]
### Link to repository

https://github.com/fathulfahmy/glazewm

### Screenshots

![collections](https://github.com/catppuccin/catppuccin/assets/100550389/2e8441ab-9812-4226-991f-cf557c126304)
![latte](https://github.com/catppuccin/catppuccin/assets/100550389/b6e8f100-4c35-46ad-b334-48c39300dd2f)
![frappe](https://github.com/catppuccin/catppuccin/assets/100550389/c41734be-d41d-41b1-a848-c0830429a692)
![macchiato](https://github.com/catppuccin/catppuccin/assets/100550389/cbf25e8a-ceac-4eb5-868c-333c2615f706)
![mocha](https://github.com/catppuccin/catppuccin/assets/100550389/3150f14b-8fa3-4821-8168-b6949223f03f)

### Thank you
I'm enjoying catppuccin on my VSCode, Vim, Neovim, Windows Terminal, Brave and Vimium. Thank you catppuccin org and contributors for all the hardwork!

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by fathulfahmy** [comment]
Hello Catppuccin Org,

I have updated the repository and made it as YAML variables instead of full configuration files. I hope anyone can take a look on the changes and leave a feedback for improvement if there is any.

**Comment by sgoudham** [comment]
Hi there :wave:
Apologies for the wait! As I don't use windows myself, I asked some people in our discord to try out this port!

Please ensure that all hex codes in the YAML are all valid. In the future, we hope to have a tool that will automatically generate hex codes for simple ports and/or lint them but that time is not now :sweat_smile:
- `example.config.yaml` - [[Crust](https://github.com/fathulfahmy/glazewm/blob/4091f2f86c8de0ecc096fb956ea4375598b154a2/example-config.yaml#L27) should be `#11111b`)
- `mocha.yaml` - [[Crust](https://github.com/fathulfahmy/glazewm/blob/4091f2f86c8de0ecc096fb956ea4375598b154a2/mocha.yaml#L26) should be `#11111b`)
- `macchiato.yaml` - [[Crust](https://github.com/fathulfahmy/glazewm/blob/4091f2f86c8de0ecc096fb956ea4375598b154a2/macchiato.yaml#L26) - should be `#181926`)
	
As I'm not able to test myself, could you verify that you are able to import your example configurations in all flavours other than mocha? Thank you!

**Comment by fathulfahmy** [comment]
Thank you for the feedback @sgoudham 

- I have cross-checked with Catppuccin palette and updated the repository
- I have also verified that all flavour is working with the same config as `example-config.yaml`

**Comment by sgoudham** [comment]
Oh just one other thing, could you please rename your `master` branch to `main` ? 

Just to keep consistency with https://github.com/catppuccin/template repository and other ports across the organisation!

**Comment by fathulfahmy** [comment]
@sgoudham Sure thing! I have renamed `master` branch to `main`

**Comment by sgoudham** [comment]
Cool, I'll send you an invite to the organisation and feel free to transfer the repository over!

You can use this [example PR](https://github.com/catppuccin/catppuccin/pull/2133/files) as inspiration for adding `glazewm` to the ports.yaml. This ensures that `glazewm` appears on the README in this repository.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by fathulfahmy** [comment]
Sorry @sgoudham I need help. Can you help me with #2135 . GitHub action to Re-generate README sections failed. I am encountering this error and can't find the solution.
```
Error: The process '/usr/bin/git' failed with exit code 1
```
