### ISSUE TITLE
Utility Repo with definitions of catppuccin for most programming langs.

### ISSUE THREAD

**Issue by BlueFalconHD** [catppuccin/catppuccin#209]
**Are you available to help in the creation of this port? 😄 (optional)**
**YES**

**Additional context 📷 (optional)**
It would have things like:
```
catppuccin = {
  mocha: ...
}
```
with all of the color values defined for each theme.

**Comment by ap-1** [comment]
I separated each theme into its own [json file](https://github.com/ap-1/puccinier/tree/main/palettes/v2) a while back. If you wanted to, you could use something like `jq` on each of them to generate what you want.

**Comment by nekowinston** [comment]
We discussed this on the Discord for a bit, IMO this is out of scope for a separate repository, and should be added to https://github.com/catppuccin/toolbox instead (like NPM, the Java draft, etc.)
