### ISSUE TITLE
Limine

### ISSUE THREAD

**Issue by mekb-turtle** [catppuccin/catppuccin#2090]
### Link to repository

https://github.com/mekb-turtle/catppuccin-limine

### Screenshots

![latte](https://raw.githubusercontent.com/mekb-turtle/catppuccin-limine/main/assets/latte.png)
![frappe](https://raw.githubusercontent.com/mekb-turtle/catppuccin-limine/main/assets/frappe.png)
![macchiato](https://raw.githubusercontent.com/mekb-turtle/catppuccin-limine/main/assets/macchiato.png)
![mocha](https://raw.githubusercontent.com/mekb-turtle/catppuccin-limine/main/assets/mocha.png)
![preview](https://raw.githubusercontent.com/mekb-turtle/catppuccin-limine/main/assets/preview.webp)

### Any additional comments?

I wasn't too sure what to do with Latte, I've tried to stick to the style guide as much as I can without it looking too ugly, the 16 terminal colours are correct but the foreground uses the non-bright (dark) by default which looked weird so foreground uses text now. I can change if needed.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hey, thanks for your contribution! i just got round to testing it out. i got it all set up easily, so no complaints there.

some feedback on colour choices:

**latte**: `surface2` used for text. this is a very light shade and the contrast is not good against the `base` background. i would advise using the named `text` colour (#4c4f69) for better contrast.

**dark themes**: in all three of mocha, macchiato, and frappé, `subtext1` is used for most of the text. visually this looks fine, but it's a slightly odd choice to make. as with latte, i'd recommend using the `text` colour (#cdd6f4 in mocha for example) for consistency's sake. that way each variant is using the same named colours.

with the above changes addressed, i would be happy to accept this port.

**Comment by mekb-turtle** [comment]
I've gone ahead and done that, lmk if there is anything else that should be changed, thanks

(also I made a mistake in my last commit which I've amended, but it still shows the comment here)

**Comment by backwardspy** [comment]
this all looks good now with the changes you made, i'm happy for this to be transferred over.

@catppuccin/core org invite please!

**Comment by nekowinston** [comment]
> @catppuccin/core org invite please!

Sent, thanks for the ping.

**Comment by mekb-turtle** [comment]
thanks, do I just transfer the repo over?

**Comment by nekowinston** [comment]
Yeah, you can specify the name to use when transferring:
![image](https://github.com/catppuccin/catppuccin/assets/79978224/852dde0f-e0e2-4be0-8bb3-12dd8d4265eb)

**Comment by mekb-turtle** [comment]
Done! https://github.com/catppuccin/limine
