### ISSUE TITLE
Lite XL

### ISSUE THREAD

**Issue by Garbg** [catppuccin/catppuccin#2092]
### Link to repository

https://github.com/Garbg/litexl-catppuccin

### Screenshots

![Latte screenshot](https://raw.githubusercontent.com/Garbg/litexl-catppuccin/main/assets/latte.webp)
![Frappe screenshot](https://raw.githubusercontent.com/Garbg/litexl-catppuccin/main/assets/frappe.webp)
![Macchiato screenshot](https://raw.githubusercontent.com/Garbg/litexl-catppuccin/main/assets/macchiato.webp)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey there 👋 
Great work on this! I have some thoughts:

1. We actually have a [Lua Library](https://github.com/UrNightmaree/catppuccin-lua) that's in the middle of the [review process](https://github.com/catppuccin/catppuccin/issues/2079) but already published on Luarocks. It totally makes sense for the `.lua` files in this repository to be auto-generated with our library as the configuration language itself is Lua. I'm trying to avoid blocking port transfers based on simple repositories not having their files auto-generated but for this repository, I think it makes sense. Let me know what you think!
2. Could you please update [this line](https://github.com/Garbg/litexl-catppuccin/blob/84fe59bc05cf99a70a366bb4b7486667ea6e34cc/LICENSE#L3) in the LICENSE to `Copyright (c) 2023 Catppuccin` in accordance with our submission guidelines

Aside from those comments above, looks amazing!

**Comment by Garbg** [comment]
These files are not auto generated and I'll update the license to say that and I'll check if I need to update the theme.

**Comment by Garbg** [comment]
The theme syntax colors are correct

**Comment by sgoudham** [comment]
Hiya there :wave: - apologies for the wait!

@nekowinston and I had a look through the repository and it looks good! Upon transfer of the repository into the organisation, we'd identified some changes that can be made to improve the syntax highlighting that will align it further with our style guide.

E.g. 
- [`normal`](https://github.com/Garbg/litexl-catppuccin/blob/9156a1ef2fc8fb43960959040b14a4eb3044330d/colors/catppuccin-mocha.lua#L19) -- red) should be `text`
- [`keyword`](https://github.com/Garbg/litexl-catppuccin/blob/9156a1ef2fc8fb43960959040b14a4eb3044330d/colors/catppuccin-mocha.lua#L22) should be `mauve`

But we can apply these improvements in a later PR - happy to see the repository moved into the organisation!

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by Garbg** [comment]
> Hiya there 👋 - apologies for the wait!
> 
> @nekowinston and I had a look through the repository and it looks good! Upon transfer of the repository into the organisation, we've identified some changes that can be made to improve the syntax highlighting that will align it further with our style guide.
> 
> E.g.
> 
>     * [`normal`](https://github.com/Garbg/litexl-catppuccin/blob/9156a1ef2fc8fb43960959040b14a4eb3044330d/colors/catppuccin-mocha.lua#L19) should be `text`
> 
>     * [`keyword`](https://github.com/Garbg/litexl-catppuccin/blob/9156a1ef2fc8fb43960959040b14a4eb3044330d/colors/catppuccin-mocha.lua#L22) should be `mauve`
> 
> 
> But we can apply these improvements in a later PR - happy to see the repository moved into the organisation!
> 
> **We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

Lite XL color config names are weird, normal isn't normal text, it's something else (I forgot what it was). Text is normal text.

**Comment by nekowinston** [comment]
We both reviewed this port on macOS and Linux, `normal` being `red` *definitely* looked off.

**Comment by Guldoman** [comment]
Hi, Lite XL contributor here.
Yeah, in most color schemes `normal` is usually the same as `symbol`.
An example usage of `normal` is the color used for plaintext files, and there `red` looks kinda off indeed.

**Comment by backwardspy** [comment]
hey @Garbg, are you still interested in maintaining this port? if so please let me know so we can send you another org invite and get this port transferred!

**Comment by Garbg** [comment]
I'm not interested

**Comment by backwardspy** [comment]
understood, thanks for your work on this!
