### ISSUE TITLE
R Studio

### ISSUE THREAD

**Issue by jonathanpipping** [catppuccin/catppuccin#2093]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

No theme currently exists for R Studio. Would it be possible to upload this to Github?

**Comment by Garbg** [comment]
If you want a catppuccin theme for a specific software, make it yourself. Here is the [official guide](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md) on how to create a port

**Comment by sgoudham** [comment]
Please raise a separate [Port Request](https://github.com/catppuccin/catppuccin/discussions/new?category=port-requests) discussion (as specified in our [FAQ](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md#faq)) for applications that you would like to see themed, thanks!
