### ISSUE TITLE
Openbox

### ISSUE THREAD

**Issue by Gingeh** [catppuccin/catppuccin#21]

**Comment by pspiagicw** [comment]
Can I work on this ?

**Comment by Gingeh** [comment]
I don't see why you couldn't :)

**Comment by andreasgrafen** [comment]
> Can I work on this ?

@pspiagicw Heya. Is there any progress on this by chance? c:

**Comment by prateektade** [comment]
Thanks to all the Catppuccin team members for their work on v0.2.0 and all the new and updated existing ports! I was wondering if any of the new members would be able to work on the Openbox port too? It will be a great way to get a uniform appearance on the LXQt desktop in conjunction with the already present ports, namely -
* [lxqt](https://github.com/catppuccin/lxqt)
* [qt5ct](https://github.com/catppuccin/qt5ct)
* [Kvantum](https://github.com/catppuccin/Kvantum)

**Comment by prateektade** [comment]
![Screenshot from 2022-11-26 16-56-29](https://user-images.githubusercontent.com/108054324/204086382-8eb848f1-ceef-4507-9b30-fcdf97ee8724.png)

This is my attempt of creating a Catppuccin flavored Openbox theme, taking inspiration from the [Catppuccin style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md) and the [Vent](https://github.com/addy-dclxvi/openbox-theme-collections/tree/master/Vent/openbox-3) theme.

I have made themes for all 4 flavors, and hope to seek some feedback about the colors. I have no experience with `git` apart from using `git clone` for getting the Catppuccin themes for all my favorite apps. I hope that I can start by contributing to this project.

**Comment by h4rldev** [comment]
This port looks great!

**Comment by nekowinston** [comment]
@prateektade sorry for the delay on this. Thanks for your work on the port, @backwardspy gave this a try today & we're happy to move this to the org! Feel free to transfer it over. 🙂

**Comment by prateektade** [comment]
@nekowinston No worries!
Thank you @backwardspy for checking it out and for the inputs about the hover highlighting and menu borders!
