### ISSUE TITLE
sc-im

### ISSUE THREAD

**Issue by 5FeetUnder** [catppuccin/catppuccin#210]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe (low on time and no real experience in porting themes)

**Additional context 📷 (optional)**
sc-im is a tui spreadsheet program with vim-like keybinds
github page [here](https://github.com/andmarti1424/sc-im)
wiki entry on how to change colors in it [here](https://github.com/andmarti1424/sc-im/wiki/Changing-colors)

**Comment by nekowinston** [comment]
I've created a port at https://github.com/catppuccin/sc-im 🎉
