### ISSUE TITLE
mIRC

### ISSUE THREAD

**Issue by lemon-sh** [catppuccin/catppuccin#2105]
### Link to repository

https://github.com/lemon-sh/mirc

### Screenshots

![preview](https://github.com/lemon-sh/mirc/raw/master/assets/previews/preview.webp)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hey, thanks for your contribution!

i tested your port and found one small mistake; in the macchiato variant the maroon colour is `#eba0ac` (from mocha) instead of `#ee99a0`. otherwise it all looks great!

with that one issue fixed, i'd be happy to have this transferred to the org.

**Comment by lemon-sh** [comment]
Should be fixed with https://github.com/lemon-sh/mirc/commit/b2f2c3bcfeaa0d58c2c5e79c867585fd6a65e89f

**Comment by backwardspy** [comment]
@sgoudham ready for org invite

**Comment by sgoudham** [comment]
Great work on this! I've sent you an invite to the organisation now @lemon-sh

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by lemon-sh** [comment]
I have transferred the repo over: https://github.com/catppuccin/mirc

Thank you for taking the time to review this. Is there anything else that needs to be done on my part?

**Comment by sgoudham** [comment]
Oh one thing I forgot to mention/pick up on, could you please rename your `master` branch to `main` ? 

It keeps consistency with our template repository and other ports across the organisation. Thanks! @lemon-sh

**Comment by lemon-sh** [comment]
- I have updated the links in the README: https://github.com/catppuccin/mirc/commit/fd2bd907c075217658e27e24e813aafbad8668eb
- I have created a PR for ports.yml: https://github.com/catppuccin/catppuccin/pull/2132
- I do not seem to be able to change the branch name: 
![image](https://github.com/catppuccin/catppuccin/assets/26277478/1cb4b8e4-c838-4c3d-8cf0-f10ea342ac30)
