### ISSUE TITLE
aerc

### ISSUE THREAD

**Issue by Stonks3141** [catppuccin/catppuccin#2113]
### Link to repository

https://github.com/Stonks3141/ctp-aerc

### Screenshots

![preview](https://github.com/Stonks3141/ctp-aerc/raw/main/assets/previews/preview.webp)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nekowinston** [comment]
Looks ready to be transferred, thanks for your work! :slightly_smiling_face:
