### ISSUE TITLE
Missing a pink-ish color

### ISSUE THREAD

**Issue by OwOchle** [catppuccin/catppuccin#2123]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

Every color in the scheme has a subtle but noticeable counterpart (i.e. for button hovering flamingo -> rosewater, sky -> sapphire/teal) but the pink color is missing a similar counter-part. Mauve in the latte theme has a huge difference.

**Comment by backwardspy** [comment]
hey @OwOchle, thanks for raising this! while we have no immediate plans to change the palette, if and when such an update comes around rest assured we will take this into consideration.

cheers!
