### ISSUE TITLE
Tabby

### ISSUE THREAD

**Issue by sakkke** [catppuccin/catppuccin#214]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
I made: https://github.com/sakkke/catppuccin-tabby

![ss](https://user-images.githubusercontent.com/84666033/183292081-6c704e5a-320d-4a8e-bc7f-ed72316ac5db.png)

Official repo: https://github.com/eugeny/tabby
Official site: https://tabby.sh/

> Tabby is an infinitely customizable cross-platform terminal app for local shells, serial, SSH and Telnet connections.

**Comment by nekowinston** [comment]
Hi there! 👋 
Thanks a lot for the port, but there are 2 small issues with the repo.

- The repository has that "generated from catppuccin/template" text, which we can't remove on GitHub.
	Please delete the existing repo on GitHub, create a new one with the same name, and push your code there.
- It's also missing a Description on GitHub, and an emoji. In the format `<emoji> Soothing pastel theme for Tabby`

Feel free to transfer it, once those issues are fixed 🙂

**Comment by nekowinston** [comment]
I just had a look at the repo again, feel free to transfer it. 👍

**Comment by nekowinston** [comment]
I've added it to the README and updated your permissions after the transfer.

Thanks for your port!
