### ISSUE TITLE
Trilium Notes

### ISSUE THREAD

**Issue by SadAlexa** [catppuccin/catppuccin#2141]
### Link to repository

https://github.com/SadAlexa/trilium-theme-catppuccin

### Screenshots

![screenshot](https://github.com/catppuccin/catppuccin/assets/91429296/e063d770-a6d1-465f-8bc1-4b577480c46b)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by NicKoehler** [comment]
Nice

**Comment by ghostx31** [comment]
Hi @SadAlexa!
Thanks for opening the issue. I found a few bugs, for example: hovering over the currently selected note highlights it but the text colour remains white. There are a few bugs which can be fixed quite easily. 

Since this is a port request, please add the other three missing theme flavours. We require ports to have all 4 flavours before they're added to the organization.

**Comment by SadAlexa** [comment]
Sorry, this is my first time working with CSS. I’ve fixed the bug you mentioned. Could you please let me know about the other bugs you’ve found so that I can fix them as well? Thank you.

**Comment by justTOBBI** [comment]
Hey, I made a theme over on my profile, maybe you can steal some of the code

**Comment by SadAlexa** [comment]
Wow, it’s beautiful! Thank you so much. I’ll make sure to take care of that soon

**Comment by SadAlexa** [comment]
I updated the repository, hope everything is ok^^
![latte-theme](https://github.com/catppuccin/catppuccin/assets/91429296/41408749-e946-4d23-bbf6-e880d0aa1323)
![frappe-theme](https://github.com/catppuccin/catppuccin/assets/91429296/ea715bef-ac5b-41fa-990a-81b16cc1aa18)
![macchiato-theme](https://github.com/catppuccin/catppuccin/assets/91429296/65ff8da5-0b8c-4939-9f7e-0890a1ae7ff3)
![mocha-theme](https://github.com/catppuccin/catppuccin/assets/91429296/4c7a9925-0951-4b44-b0d1-663dc16507ff)

**Comment by justTOBBI** [comment]
Is there some way to change the accent? Most people want an easy way to change that

**Comment by SadAlexa** [comment]
Is not possible right now, but I could create a download script that automatically change the accent color

**Comment by SadAlexa** [comment]
I added a bash script for the accent color

**Comment by backwardspy** [comment]
lgtm! @catppuccin/core ready for org invite

**Comment by sgoudham** [comment]
Sent you an invite to the org!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
