### ISSUE TITLE
skim

### ISSUE THREAD

**Issue by gabrielmagno** [catppuccin/catppuccin#2143]
### Link to repository

https://github.com/gabrielmagno/skim

### Screenshots

![latte](https://github.com/catppuccin/catppuccin/assets/244890/53c81173-3e35-41c1-81ad-3e0650f44148)
![frappe](https://github.com/catppuccin/catppuccin/assets/244890/62cec54e-193f-494d-8871-dbc95b5c572f)
![macchiato](https://github.com/catppuccin/catppuccin/assets/244890/5fcefd8a-ef53-4f3e-a93d-f13840b08dd6)
![mocha](https://github.com/catppuccin/catppuccin/assets/244890/1cd4fd3f-39d2-4b91-b67b-4f39e98902ce)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hi, thanks for your contribution! i've tested the port and it all seems to work as expected, and the repo looks good.

side note; the stars/issues/contributors badges at the top of the readme should continue to work after transferring the port as github will handle the redirect, however it'd be good to update their URLs to point to `catppuccin/skim` anyway so we don't have to rely on that.

@catppuccin/core: ready for org invite.

**Comment by nekowinston** [comment]
I've sent the invite. Thanks for the port 🙂

**Comment by gabrielmagno** [comment]
Thank you @backwardspy and @nekowinston !

I've just accepted the invitation to the catppuccin organization and moved the skim repository to it.

I also renamed the URLs of the badges to refer to the cappuccin URL, as suggested by @backwardspy .

Cheers!
