### ISSUE TITLE
Infinity

### ISSUE THREAD

**Issue by AnubisNekhet** [catppuccin/catppuccin#216]
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Additional context 📷 (optional)**
[Infinity](https://github.com/Docile-Alligator/Infinity-For-Reddit) is an alternative reddit client for android with support of creating themes and importing/exporting them as JSON files.

**Comment by nekowinston** [comment]
Seems like there is a 0.1.0 port, which might help with the 0.2.0 version:
https://github.com/lepz0r/Infinity-For-Reddit

**Comment by skinatro** [comment]
does anybody knows any method how to convert the java negative integer values back to hex?

**Comment by nekowinston** [comment]
@skinatro if you have:
```json
{
   "backgroundColor": -15330528
}
```

In JS, you could do:
```js
console.log((0xFFFFFF & -14803410).toInt(16))
// #1e1e2e
```

**Comment by Xurdejl** [comment]
I have a port for this app.
https://github.com/Xurdejl/infinity-for-reddit.

**Comment by nekowinston** [comment]
@Xurdejl that is simply lovely! Thanks for your port, let me invite you to the org.

Glad to see `catwalk` being used again. :slightly_smiling_face:

**Comment by andreasgrafen** [comment]
I've been test-driving each theme for a couple minutes now. I can't spot anything out of the ordinary. I def. approve this one. It's great! c:
Likely to make me switch back to Infinity again actually. xd

<details>
<summary> Screenshots</summary>

![01_infinity_latte](https://user-images.githubusercontent.com/35840154/189453845-d5180bd5-fc64-47db-ad3e-723ec6757b04.jpg)
![02_infinity_frappe](https://user-images.githubusercontent.com/35840154/189453847-c3ca7a8d-eab4-4790-aa9a-273541fac982.jpg)
![03_infinity_macchiato](https://user-images.githubusercontent.com/35840154/189453850-5050fdf7-3fe8-4b43-a650-7f78b67d1dbc.jpg)
![04_infinity_mocha](https://user-images.githubusercontent.com/35840154/189453851-7597215f-a139-431a-ac7f-4b022fbdf147.jpg)

</details>

**Comment by skinatro** [comment]
> 

thanks a lot, will be useful for other android themes as well

**Comment by Xurdejl** [comment]
Oh, I missed that one.
Fixed the contrast issue by changing the highlighted background color with `Surface0`. ^^

**Comment by nekowinston** [comment]
@Xurdejl will you transfer the repo to `catppuccin/infinity` ?

**Comment by nekowinston** [comment]
Thanks for transferring it! 🎉 
I've updated your permissions for the repo, and I'll add it to the main README.

**Comment by andreasgrafen** [comment]
One tiny thing: We want the repo name to be the simplest version of the app, right? So I'd advocate for renaming it to just »Infinity«? c:

**Comment by nekowinston** [comment]
Yeah, I was kinda wondering about that, could it clash with anything else named `infinity`? Otherwise I agree.

**Comment by andreasgrafen** [comment]
> Yeah, I was kinda wondering about that, could it clash with anything else named `infinity`? Otherwise I agree.

Likely, but that could potentially be the case for a lot of repos, no?

**Comment by nekowinston** [comment]
@Xurdejl I'll rename it to infinity, tweak the links in your README, and add it to the main repository.
