### ISSUE TITLE
Wofi

### ISSUE THREAD

**Issue by quantumfate** [catppuccin/catppuccin#2165]
### Link to repository

https://github.com/quantumfate/wofi

### Screenshots

![wofi-mocha](https://github.com/catppuccin/catppuccin/assets/62796852/ef862136-03a4-44f3-b0ea-78e6e042e7ee)
![wofi-macchiato](https://github.com/catppuccin/catppuccin/assets/62796852/1f08d22b-37f7-439f-b59f-7df9534e9ba1)
![wofi-frappe](https://github.com/catppuccin/catppuccin/assets/62796852/99d873c3-ae30-4404-9060-7f0f2f239718)
![wofi-latte](https://github.com/catppuccin/catppuccin/assets/62796852/ef2f37f2-4003-491d-8463-9e56ae9f9bc3)

### Any additional comments?

Hey! I've seen that there was another Wofi Port request before but it was closed and I personally needed this desperately. 

I'm looking forward to hear about tips and tricks from you regarding the design. 

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave:, apologies for the wait on this.

Thank you for working on this! However, I've just checked out Wofi and I believe it's not actively maintained anymore (and there doesn't seem to be any one else picking it up?)

![image](https://github.com/catppuccin/catppuccin/assets/58985301/9aed750e-ac84-4483-bfac-1baf84a91395)

From my point of view, I'm not excited at the thought of bringing ports of applications that are explicitly unmaintained into the organisation. Even if the software still continues to work, that might stop at any time and then the theme isn't very useful if the original application doesn't continue to work. 

Of course, this is no way in relation to the quality of the repository itself but I'm personally not comfortable with new ports based on explicitly unmaintained software with no alternatives listed!

I hope that makes sense, I'll be closing this issue as not planned but please feel free to reply if you still do think this should be brought into the organisation.
