### ISSUE TITLE
Gitkraken

### ISSUE THREAD

**Issue by davi19** [catppuccin/catppuccin#2170]
### Link to repository

https://github.com/davi19/gitkraken

### Screenshots

Catppuccin Frappé
![Catppucin-Frappé](https://github.com/catppuccin/catppuccin/assets/9946675/776addc2-ca97-429a-993d-c1b278a85a0b)

Catppuccin Macchiato
![Catppuccin-Macchiato](https://github.com/catppuccin/catppuccin/assets/9946675/31ae4f3b-602b-483d-bff5-efb5486f3c08)

Catppuccin Latté
![Catppuccin-Latte](https://github.com/catppuccin/catppuccin/assets/9946675/e2412098-8ee0-460a-b7eb-fa96790f1a00)

Catppuccin Mocha
![Catppuccin-Mocha](https://github.com/catppuccin/catppuccin/assets/9946675/fc69deca-3732-47c0-8f69-2e692fa97366)

### Any additional comments?

The pallet i used was:

```
      "current__line": "#dd7878", // Flamingo
      "background": "#eff1f5", // Base
      "foreground": "#4c4f69", // Text
      "comment": "#209fb5", // Sapphire
      "pink": "#ea76cb", // Pink
      "red": "#d20f39", // Red
      "orange": "#fe640b", // Peach
      "yellow": "#df8e1d", // Yellow
      "green": "#40a02b", // Green
      "purple": "#8839ef", // Mauve
      "cyan": "#179299", // Teal
```

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nullishamy** [comment]
https://github.com/davi19/Catppuccin-Gitkraken-Theme/blob/main/README.md?plain=1#L4 Typo of "GitKraken".

https://github.com/davi19/Catppuccin-Gitkraken-Theme/blob/main/README.md?plain=1#L34 Missing "Thanks to" section here, not sure if it is required though.

https://github.com/davi19/Catppuccin-Gitkraken-Theme/blob/main/README.md?plain=1#L11 is this always the same, regardless of a setting / user preference?

**Comment by davi19** [comment]
Thanks for reply, i added the thanks to section, fix the name and added a better description of usage

**Comment by davi19** [comment]
@sgoudham i fixed the requests.

**Comment by sgoudham** [comment]
Hey @davi19, apologies for the wait on this. I've frankly not found the motivation to review ports in the free time that I have.

I have a few comments regarding the theme and the repository:

### Repository

1. I don't believe the [catppuccin/template](https://github.com/catppuccin/template) repository has been used for the creation of this repository, please follow the steps outlined in the [port creation](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md#creation) document and use the README given.
2. In the first step of the README, you showcase the path for Windows. Thankfully, GitKraken have an [installation page](https://help.gitkraken.com/gitkraken-client/how-to-install/) which highlights the installation paths. Could you please update this step to something like the following:

	```md
	1. Navigate to the `.gitkraken` themes folder, here are the default locations for each platform:
		- Linux & MacOS: `~/.gitkraken/themes`
		- Windows: `C:\Users\{user}\AppData\Roaming\.gitkraken\themes`
	```

	This also removes the need for step `2.`
	
3. We should follow the default naming convention for themes, e.g. `dark.jsonc-default` - I'd prefer if the themes were just named `catppuccin-{flavour}.jsonc`

### Theme

1. The overall theme, while looks nice, doesn't fully adhere to the style guidelines / conventions that other applications use. For most, if not all, applications that are themed, the background is set to `base` and any sidebars/secondary panels are either `mantle` or `crust`.

	Given the screenshot below:
	
	`GitKraken - Mocha`
	![image](https://github.com/catppuccin/catppuccin/assets/58985301/d2704dd9-9998-4364-9c96-4cc09fdae17e)

	It would be good to keep the background as base but convert the sidebars to `mantle` and the top/bottom bars to `crust`. Note that this also applies to the preferences screen where the left sidebar should be `mantle`. My reference point is our VSCode theme, also shown below:
	
	`VSCode - Mocha`
	![image](https://github.com/catppuccin/catppuccin/assets/58985301/0243f6b5-97d4-4ee1-83ba-29c589d4eddd)
	
2. In the implementation for Latte, the git log background should be set to `base` and sidebars to `mantle` as discussed in the previous bullet point. 

3. I can see that we're using functions such as `lighten` and `fade` a fair amount in the code to generate different shades. However, I think these are somewhat overused and leads to some sections of the theme not representing Catppuccin. I think implementing the previous bullet point will reduce this, and of course I understand that there are many keys to be themed so it definitely makes sense for things like hover states. That being said, I would appreciate if you could go through each key and see if there are existing palette colours that can be used without modification and/or bring the modified colours closer to the palette colours.

That's all from me, and apologies again for taking a while to properly review this.

**Comment by backwardspy** [comment]
hey @davi19, just checking in to see where we're at. with hammy's suggestions above implemented we'd be very happy to get this port transferred into the org.

let me know if you're still interested!

**Comment by davi19** [comment]
Hi, I'm still interested in continuing with the port. I should be able to adjust it again this week.

**Comment by backwardspy** [comment]
thanks for the update, that's great news! no rush of course, just wanted to see if we should keep this issue open. :)

**Comment by davi19** [comment]
@sgoudham  Hi, can you validate if the repository is up to standard ? https://github.com/davi19/gitkraken

The images i will change when I make the changes you requested.

**Comment by davi19** [comment]
@sgoudham i'm adjusted some colors but somes fades and lighten is necessary. Like the buttons. In images below its without fade, then buttons has strong color.
![Captura de tela de 2024-04-19 19-58-30](https://github.com/catppuccin/catppuccin/assets/9946675/5d6c2cf1-928c-47fb-918a-f56faac8228e)

**Comment by sgoudham** [comment]
Thanks for taking the time to update the port @davi19 

I believe @backwardspy would be interested in trying out the theme again to see if it better matches our other applications.

One comment about the repository, the `assets` directory is for the preview images so would be great if you could move the `catppuccin-flavour.jsonc` files into the root of the repository or under a `src` directory.

**Comment by davi19** [comment]
@backwardspy when you go test use the mocha theme. The others im go change when the design of mocha its ok for you. Thanks

**Comment by backwardspy** [comment]
hey @davi19 thanks for the update. i think it looks pretty good now! the only comment i've come up with is some of the background-coloured elements are a little hard to read in some cases:

![image](https://github.com/catppuccin/catppuccin/assets/289746/3fda8fa4-7400-4c2c-97ca-fdaf0bca1a20)
![image](https://github.com/catppuccin/catppuccin/assets/289746/a48884b5-d549-4b0f-9029-93d71630023a)

it might be worth further darkening those colours, or using a dark text colour instead.

vscode for example does this:

![image](https://github.com/catppuccin/catppuccin/assets/289746/fe42faf0-6e1b-4123-83a7-d85da19dd792)

otherwise it looks great - once you're happy with the tweaks i've mentioned then please feel free to get started on the other variants!

**Comment by davi19** [comment]
Thanks for reply. I'm go change this elements for a dark color. And after this im go make The other flavors

**Comment by nicolas-goudry** [comment]
This looks neat! Thanks for the work @davi19 :slightly_smiling_face: 

I found the following issues using the mocha variant (some of them have already been reported):

- the « Amend » checkbox is still using the default blue color, as well as all checkbox in the settings menu
- green buttons (« Stage all changes », « Stage files/changes to commit », « Amend Previous Commit ») are very hard to read (disabled or not)
- the selected item in the left sidebar (eg. the current branch) is also very hard to read
- the « New » badge next to the « Workspaces » section of the new tabs is also very hard to read
- the highlight box around selected profile icon is using the default blue color
- the text fields in the profile edit window have the same background as the window
- (not sure about this one, just feels weird) the « Cancel » button of the profile edit window has a yellow-ish color when focused
- purple buttons (like in the SSH settings section when local agent is selected or in the terminal settings section) are a bit hard to read (disabled or not)

**Comment by davi19** [comment]
@nicolas-goudry thanks for the feedback. I'm go fix this errors in this week.

**Comment by nicolas-goudry** [comment]
I also just noticed that the buttons on the « New tab » tab have the same background as the window background.

**Comment by nicolas-goudry** [comment]
Sorry for the spam-ish comments, I noticed that GitKraken is complaining of some errors in the theme file, but somehow manages to load it.

```jsonc
{
  // ...
  "themeValues": {
    // values applied to the entire app
    "root": {
      // ...
      "crust": "#11111b" // missing comma
      // ...
      "filter-match": @purple", // missing dcol
      // ...
    },
    // ...
  }
}
```

**Comment by davi19** [comment]
Thanks for the help catching this bugs. I will solve these issues, more quickly than i can.

**Comment by sgoudham** [comment]
Hi, I'm going to close this in favour of #2492 as catppuccin/whiskers has been used in that repository, making it much easier to iterate and improve on the theme.

Of course, I really appreciate @davi19 for pushing the gitkraken work forward and continuing to collaborate with us on this issue, even though this issue has gone through periods of inactivity. I think it would be great if any improvements mentioned here were also contributed to the repository in #2492!

Thanks again everyone.
