### ISSUE TITLE
tofi

### ISSUE THREAD

**Issue by iruzo** [catppuccin/catppuccin#2171]
### Link to repository

https://github.com/iruzo/tofi

### Screenshots

<details>
<summary>🌻 Latte</summary>
<img src="https://raw.githubusercontent.com/iruzo/tofi/main/assets/latte.png"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://raw.githubusercontent.com/iruzo/tofi/main/assets/frappe.png"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://raw.githubusercontent.com/iruzo/tofi/main/assets/macchiato.png"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://raw.githubusercontent.com/iruzo/tofi/main/assets/mocha.png"/>
</details>

![preview](https://raw.githubusercontent.com/iruzo/tofi/main/assets/preview.webp)

### Any additional comments?

Port should be ready.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hiya :wave: Good work on this!

 Just 2 comments from me:

1. The current assets directory contains png files and our submission guidelines state that these images should be in `.webp` format so it would be great if you could convert them (and update the README!)

	If you run the following command inside of the assets directory, it should automatically convert them without losing any quality: `for file in *.png; do convert -quality 100 "$file" "${file%.png}.webp"; done`
	
2. This is more of a nitpick than anything but I think it would be nicer if the `themes` file was split out into 4 different files like many of our other ports? It might also allow users to do something like `wget https://raw.githubusercontent.com/iruzo/tofi/main/catppuccin-<flavour>.json >> ~/.config/tofi/config`

	What do you think about this?

**Comment by iruzo** [comment]
Hi!,

1. All images have been converted to WebP.
2. Themes have been split into multiple files and README was updated with `curl` commands, so users can copy them and use it directly in their terminals.

Thanks for the tip about using ImageMagick package to convert the PNG files!

**Comment by sgoudham** [comment]
Thanks for that! 

I think you've still got all your old changes so once you've removed the `themes` file and all the `*.png` assets, we should be good for transfer!

**Comment by iruzo** [comment]
Woops!, sorry, I forgot about removing them.

Done. Themes and old PNG files have been deleted.

Thanks!

**Comment by sgoudham** [comment]
I'm happy for it to be transferred over to the organisation!

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by iruzo** [comment]
@sgoudham port has been transferred. [I linked the PR](https://github.com/catppuccin/catppuccin/pull/2172) related to [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml).
