### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by useEffects** [catppuccin/catppuccin#2174]
### Link to repository

https://github.com/useEffects/catppuccin-dart

### Submission Guidelines

- [x] I have read and followed Catppuccin's submission guidelines.

**Comment by justTOBBI** [comment]
Lgtm. 👍

**Comment by sgoudham** [comment]
Great work on this! I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. An example pull request of an application being added to this file can be found here: https://github.com/catppuccin/catppuccin/pull/2164.

Feel free to ask any questions!

**Comment by backwardspy** [comment]
thanks!
