### ISSUE TITLE
Chatterino 2

### ISSUE THREAD

**Issue by fruzitent** [catppuccin/catppuccin#2177]
### Link to repository

https://github.com/fruzitent/chatterino2

### Screenshots

The only customizable screen is the main one, to avoid redundancy, you can find screenshots in the preview section within the repository.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nekowinston** [comment]
Thanks for the work on the port!

Two things stood out to me, could you please
- include the [Footer ](https://github.com/catppuccin/template/blob/main/README.md#-thanks-to)of our template README ("thanks to" with a link to your profile, and the cat banner at the bottom)
- change the `LICENCE.md` to our `LICENSE` [here](https://github.com/catppuccin/template/blob/main/LICENSE)?

**Comment by fruzitent** [comment]
Done.

**Comment by backwardspy** [comment]
lgtm! @catppuccin/core ready for org invite

**Comment by sgoudham** [comment]
Sent you an invite to the org!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
