### ISSUE TITLE
Qt Creator

### ISSUE THREAD

**Issue by backwardspy** [catppuccin/catppuccin#2183]
### Link to repository

https://github.com/backwardspy/ctp-qtcreator

### Screenshots

![preview](https://github.com/catppuccin/catppuccin/assets/289746/44ea80fd-1b8b-43f6-90e0-86ff4ece8ca8)

### Any additional comments?

the port itself has been tried by several people on discord already, but i'd appreciate a sanity check on the repo before transferring it

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Great work on this! I'm happy for it to be transferred over to the organisation!

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**
