### ISSUE TITLE
Fitbit

### ISSUE THREAD

**Issue by lighttigerXIV** [catppuccin/catppuccin#2187]
### Link to repository

https://github.com/lighttigerXIV/fitbit

### Screenshots

![frappe](https://github.com/catppuccin/catppuccin/assets/35658492/e22127e5-81de-41db-9032-554a13f61efa)
![latte](https://github.com/catppuccin/catppuccin/assets/35658492/18554e36-d2f9-427c-80c7-4411dd1d00a5)
![macchiato](https://github.com/catppuccin/catppuccin/assets/35658492/720e85d6-f96a-4d53-8155-25c02bd759ec)
![mocha](https://github.com/catppuccin/catppuccin/assets/35658492/10ea2f48-41b6-4863-a312-7f4b841ceaa8)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by justTOBBI** [comment]
Just a small thing I noticed: 
The description is missing a space between the emoji and `Soothing` :P

**Comment by lighttigerXIV** [comment]
> Just a small thing I noticed: The description is missing a space between the emoji and `Soothing` :P

Ok. I updated it

**Comment by sgoudham** [comment]
Just putting the outcome of our conversation on discord, this should be good to transfer after all the boxes (besides the first one) are ticked. @lighttigerXIV 

![image](https://github.com/catppuccin/catppuccin/assets/58985301/b9e02f83-cc62-4346-86f2-605bf6f9e8b6)

**Comment by sgoudham** [comment]
Discussed on discord and have confirmed that all of the above tasks have been completed.

Happy to approve the port and allow it into the organisation :+1: 

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
