### ISSUE TITLE
Linear

### ISSUE THREAD

**Issue by kkrypt0nn** [catppuccin/catppuccin#2188]
### Link to repository

https://github.com/kkrypt0nn/linear

### Screenshots

![Preview](https://raw.githubusercontent.com/kkrypt0nn/linear/master/assets/preview.webp)

<details><summary>🌻 Latte</summary>
<p>
<img src="https://raw.githubusercontent.com/kkrypt0nn/linear/master/assets/latte.webp" />
</p>
</details>

<details><summary>🪴 Frappé</summary>
<p>
<img src="https://raw.githubusercontent.com/kkrypt0nn/linear/master/assets/frappe.webp" />
</p>
</details>

<details><summary>🌺 Macchiato</summary>
<p>
<img src="https://raw.githubusercontent.com/kkrypt0nn/linear/master/assets/macchiato.webp" />
</p>
</details>

<details><summary>🌿 Mocha</summary>
<p>
<img src="https://raw.githubusercontent.com/kkrypt0nn/linear/master/assets/mocha.webp" />
</p>
</details>

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hello :wave:, just tried this out on the free plan. It looks lovely!

I'm happy for it to be transferred over to the organisation!

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)!**

**Comment by sgoudham** [comment]
Merged in https://github.com/catppuccin/catppuccin/pull/2190
