### ISSUE TITLE
V

### ISSUE THREAD

**Issue by backwardspy** [catppuccin/catppuccin#2196]
### Link to repository

https://github.com/Delta456/catppuccin

### Any additional comments?

discussion: https://github.com/catppuccin/catppuccin/discussions/2179

cc @Delta456

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by Delta456** [comment]
Thanks for making this issue, @backwardspy!

**Comment by backwardspy** [comment]
thank you for your work on this!

just one more change request from me; please rename the "FAQ (optional)" heading to just "FAQ". the "optional" part is *supposed* to indicate that it's not a required readme section for every port.

finally, when we transfer the repo you should update the badge links at the top of the readme to point to `catppuccin/v` instead of the current URL. it's up to you whether you want to do this now or after transfer.

**Comment by Delta456** [comment]
> thank you for your work on this!
> 
> just one more change request from me; please rename the "FAQ (optional)" heading to just "FAQ". the "optional" part is _supposed_ to indicate that it's not a required readme section for every port.

It's done.

> finally, when we transfer the repo you should update the badge links at the top of the readme to point to `catppuccin/v` instead of the current URL. it's up to you whether you want to do this now or after transfer.

I will do that after the transfer.

**Comment by sgoudham** [comment]
Hi @Delta456, thank you for working on this! 

@backwardspy confirmed that he was happy to have this transferred into the organisation and I agree with him! I've sent you an invite to the organisation.

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure with the steps for transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by sgoudham** [comment]
Oh actually @Delta456, please update the [LICENSE](https://github.com/Delta456/catppuccin/blob/main/LICENSE) file to use [Catppuccin's License](https://github.com/catppuccin/template/blob/main/LICENSE) instead (you can replace the year from 2021 to 2023 too)

**Comment by Delta456** [comment]
> Oh actually @Delta456, please update the [LICENSE](https://github.com/Delta456/catppuccin/blob/main/LICENSE) file to use [Catppuccin's License](https://github.com/catppuccin/template/blob/main/LICENSE) instead (you can replace the year from 2021 to 2023 too)

Done

> Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure with the steps for transferring the repository to Catppuccin.

Transferring.
