### ISSUE TITLE
MobaXterm

### ISSUE THREAD

**Issue by likendev** [catppuccin/catppuccin#2197]
### Link to repository

https://github.com/likendev/catppuccin-mobaxterm

## Latte
![mobaxterm-latte](https://github.com/catppuccin/catppuccin/assets/15458805/622e0210-4e9b-4fe9-9256-e583bd1a7f71)

## Frappe
![mobaxterm-frappe](https://github.com/catppuccin/catppuccin/assets/15458805/5f86d75f-5e78-4b9f-94ce-61585f6e7d76)

## Macchiato
![mobaxterm-macchiato](https://github.com/catppuccin/catppuccin/assets/15458805/a322cfd8-0f15-4fff-990f-48aa63eddbce)

## Mocha
![mobaxterm-mocha](https://github.com/catppuccin/catppuccin/assets/15458805/21fdc87c-88d4-48a3-929c-9e48d8e01f22)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hi @likendev, thanks for the contribution! i've given the port a quick test and it all looks good. just one change please; please could you change the image links in the readme file to be relative instead of absolute?
for example:
```diff
- <img src="https://raw.githubusercontent.com/likendev/catppuccin-mobaxterm/main/assets/latte.webp"/>
+ <img src="/assets/latte.webp"/>
```

once this is done, i'd be happy to get this port transferred into the org.

**Comment by likendev** [comment]
> hi @likendev, thanks for the contribution! i've given the port a quick test and it all looks good. just one change; please could you change the image links in the readme file to be relative instead of absolute? for example:
> 
> ```diff
> - <img src="https://raw.githubusercontent.com/likendev/catppuccin-mobaxterm/main/assets/latte.webp"/>
> + <img src="/assets/latte.webp"/>
> ```
> 
> once this is done, i'd be happy to get this port transferred into the org.

Hi @backwardspy this is done and I've updated the stats tag to catppuccin repo as well.

**Comment by backwardspy** [comment]
ah perfect, i missed the badges!

@catppuccin/core ready for org invite

**Comment by andreasgrafen** [comment]
Invitation was sent. Another terminal in the ranks of Catppuccin! 🙏

**Comment by likendev** [comment]
Done transferring! 
https://github.com/catppuccin/mobaxterm

**Comment by backwardspy** [comment]
cheers!
