### ISSUE TITLE
Cinny

### ISSUE THREAD

**Issue by jan-senaa** [catppuccin/catppuccin#220]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
I've prepared a Stylus UC for the [Cinny](https://github.com/cinnyapp/cinny) app.
You can find the repository I've prepared [**here**](https://github.com/jan-senaa/cinny). I am willing to do any changes if requested.

Here is a screenshot:

![screenshot.png](https://user-images.githubusercontent.com/45771313/185622298-715ab50a-7889-46d7-a48a-4776808e22ec.png)

**Comment by nekowinston** [comment]
Thanks for your port, everything looks in order. :)

Feel free to transfer it anytime. 👍

**Comment by jan-senaa** [comment]
Transferred to [catppuccin/cinny](https://github.com/catppuccin/cinny)! 🥳
