### ISSUE TITLE
Color mismatch between iTerm2 and Neovim?

### ISSUE THREAD

**Issue by docwhite** [catppuccin/catppuccin#2207]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

Hello dear team!

Sorry if this issue does not belong here, but I downloaded your [iTerm's catppuccin-mocha.itermcolors](https://github.com/catppuccin/iterm/blob/main/colors/catppuccin-mocha.itermcolors) and installed it as the current Colors of my iTerm2 profile.

Then I downloaded `neovim` and installed [NvChad](https://nvchad.com/). After installing I changed the theme to `catppuccin`, so now my `~/.config/nvim/custom/chadrc.lua` looks like this:

```
---@type ChadrcConfig
local M = {}

M.ui = { theme = 'catppuccin' }

return M
```

If I open now two terminals, one with zsh and the other with Neovim I get different background colors:

<img width="1412" alt="Screenshot 2023-11-05 at 14 49 09" src="https://github.com/catppuccin/catppuccin/assets/6486812/017c46c1-3cd3-48ba-9961-c82f2497f433">

My easy workaround is to simply head over the iTerm2 Colors and change the background from `#1e1e2d -> #1e1d2d`, but that means I cannot automate fetching your updates blindly :) 

My questions are:

1. Is this because NvChad's theme might use an older commit?
2. How could I check in neovim the actual color being rendered in the background?
3. Does this issue maybe belong to `catppuccin/nvim` or `NvChad/NvChad`?

I haven't found out how NvChad manages the themes, I guess in the end of the day it uses your reference guide in [catppuccin/nvim](https://github.com/catppuccin/nvim).

Thank you!

**Comment by siduck** [comment]
close the issue, nvchad's catpuccin is a modified version of catpuccin back then when it wasnt famous. I dont plan to add any of its variants now nor its default colorscheme, will port plenty of other colorschemes but not this. I   refuse to elaborate.

**leaves**

**Comment by backwardspy** [comment]
hi @docwhite! as siduck has implied above, we do not maintain the catppuccin-based colourscheme that is included in nvchad.
if you would like an exact match, installing & using [the official neovim theme](https://github.com/catppuccin/nvim) will give you the correct colours, including mocha's #1e1e2e base colour. this will make it consistent with all of our other application ports.

i'll close this for now, but please feel free to reply & ping me if you have any further questions!
