### ISSUE TITLE
Linux TTY

### ISSUE THREAD

**Issue by CallMeEchoCodes** [catppuccin/catppuccin#221]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes
**Additional context 📷 (optional)**
I ported catppuccin to the linux TTY!
repo here: https://github.com/CallMeEchoCodes/tty

**Comment by Aurn1ox** [comment]
i tried it, and for some reason it just kept asking me to log in over and over again when i sourced it in my .bashrc, though it worked for some reason when i just used what was in the script directly in my bashrc if $TERM was linux

**Comment by nekowinston** [comment]
Hi there 👋
Thanks for your port!
I don't get why you merged https://github.com/CallMeEchoCodes/tty/pull/1, please revert that before transferring the Repo to the org.

I've had a look at the colour choices, please look at our https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#regular-colours; Latte has different colours for term colours 0, 7, 8 and 15.

**Comment by CallMeEchoCodes** [comment]
@nekowinston 
heya! setting 0 to base is because TTY uses 0 for bg. same with 7. the others are my fault and ill fix them now

**Comment by CallMeEchoCodes** [comment]
added to org!
