### ISSUE TITLE
Directory Opus Catppuccin Theme

### ISSUE THREAD

**Issue by Mojas84** [catppuccin/catppuccin#2212]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

Hi Please we can make Directory Opus Catppuccin Theme

**Comment by vanillyn** [comment]
you can make requests for themes to be added to catppuccin via [discussions](https://github.com/catppuccin/catppuccin/discussions/new?category=port-requests), but making an issue i believe is not a valid way to request a theme

**Comment by sgoudham** [comment]
Closing since this should be a [port request](https://github.com/catppuccin/catppuccin/discussions/new?category=port-requests), as mentioned above.
