### ISSUE TITLE
Userstyles

### ISSUE THREAD

**Issue by justTOBBI** [catppuccin/catppuccin#223]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
I created the MonoRepo for the catppuccin Userstyles here: https://github.com/justTOBBI/userstyles :)

**Comment by nekowinston** [comment]
Really wanna hear your input on this, @Pocco81 & @andreasgrafen

We could auto-update the git submodules with a workflow, for example.

**Comment by andreasgrafen** [comment]
Right! I totally forgot to answer this. I personally still think that a bundled repo makes a lot of sense to reduce noise. The question is what the best way to approach this would be.

The submodule approach still requires everything to has it's own repo, where the main repo is just another collection point to point users to. Maintenance for the individual themes is def. easier this way, but it still leaves a lot of clutter behind.

Another idea would be to actually just use subfolders for each theme, that way it would be a true mono repo. This would *actually* bundle everything in one place, but also requires a lot more disciplin from maintainers to prevent breakage.

I'm not 100% sure which approach I would actually prefer. One thing I'd def. opt for tho is to have a more complex list of the available userstyles in the overarching readme. Kinda like it is on the [toolbox](https://github.com/catppuccin/toolbox) repo, where each module has it's own little section where we can put a preview image and short description.

**Comment by isabelincorp** [comment]
I agree with the mono repo that is like toolbox, but maybe have every category collapsed by default due to the sheer amount of user styles we got.

**Comment by nekowinston** [comment]
Closing this in favor of the RFC/discussion: https://github.com/catppuccin/community/discussions/4
