### ISSUE TITLE
`ports.schema.json`: allow multiple categories

### ISSUE THREAD

**Issue by isabelroses** [catppuccin/catppuccin#2230]
### Background information
Currently, the [userstyles repo](https://github.com/catppuccin/userstyles) organises and lists userstyles into nice categories that can be quickly read and understood. However, the repo largely inherits its categories from the [main repo](https://github.com/catppuccin/catppuccin), which has a much more generalized schema leading to some categorisation issues. As a result of such, categories which are likely to encompass more then one port, but are *supposed* to have one clear main category. Which is not the case at the moment. This issue preposes a fix which consists of improving the schema, by creating and reclarifying categories for the userstyles repo, which *could* be adopted by the main repo.

### Why we need this change
To start I would like to reclarify `Leisure`, `Social` and `Messaging` since there is a lot of overlap between these categories.
Take YouTube for example, it could come under `Social` and `Leisure` since its both a social media platform and a leisure activity. But then what about Instagram, which has a lot of similar features. Or even something like substack, which is currently listed under social along with hacker news, but both could be argued as `Leisure`, `Social` or even `Productivity`.

Another example is Syncthing and Homepage, both of which are currently listed as `Productivity`, perhaps they would go better under a `Self-hosted` category. This category however does not make much sense for the more main repos schema, since a large amount of the tools and apps come under this category.

But only looking at negative examples is not the best way to show how well this could work. Therefore, a good example of this already in place is the `Search Engines` category which encapsulates a lot of the userstyles perfectly, and has enough userstyles to warrant a specialized category of its own. This shows how well, the improved schema could work with the given changes.

Something else to consider is suites of products like the google suite and the proton suite. Currently, all the proton websites are under one userstyle, but the google suite is not complete and broken up into multiple userstyles, such as Gmail and Google. So perhaps it would make sense to create a category for these items.

### The preposed changes
In my idealised schema we would also include the following categories:
- `Social media` : This would fit websites like YouTube and Instagram.
- `Fun` : One example of this might be stylus.
- `Self-hosted` : This would contain ports such as Syncthing and Homepage.

Please feel free to add your options and suggestions particularly on the choices of categories. The categories are up for debate and change, if a better category is suggested.

**Comment by uncenter** [comment]
I know it was just an example, but I would argue Stylus would fit in the `Development` category more than anything else.

**Comment by isabelroses** [comment]
> I know it was just an example, but I would argue Stylus would fit in the `Development` category more than anything else.

Yeah, after typing it up I realised `Fun` was not the best category since a lot of the `Self-hosted` would be a better fit, like the best example I had was InvokeAI. And `Fun` seems a bit too general for games, so perhaps it was not the best of the suggested categories, hence why I really want some feedback and suggestions.

**Comment by sgoudham** [comment]
Unironically, I think it might actually be best to kinda look towards prior art and at stuff like Google's Play Store / Apple App Store. Here are the google play store ones: https://developers.apptweak.com/reference/google-play-store-categories

Of course, we're a bit more nerdy but I think we want to take inspiration from those categories. 

I also mentioned on discord, the model at the minute restricts us a little as we can only define one category for our applications. The reality is that they can be many (but still come under one primary/canonical category)

I'd like us to move towards a model where any application can have multiple categories, and we can say that the first in the list is the "primary one" to be displayed in the README. This also opens up some cool doors, e.g. the ports list on the WIP website can sort by categories and we can assign weights based on the position of the category in the list.

For a concrete example, let's take the `YouTube` port, if we could define it like so:

```yaml
youtube:
    name: YouTube
    categories: ["Entertainment", "Social Networking", "Leisure"]
```

You would put YouTube primary under `Entertainment`, and this is analogous to a weight of `1`. The rest of the weights could probably be distributed evenly by doing `1 / categories.size() - 1` -> giving us `0.5` for the rest. I feel like this would be quite handy when implementing fuzzy searchers in websites.

To wrap up though, I do agree that the categories can be fleshed out a bit more. In my opinion, we should take more inspiration from the play stores of the world and just make it a bit more nerdy to suit us right. And move towards a multi-category model.

**Comment by sgoudham** [comment]
I _feel_ this is getting into the over-engineered territory :/ I think we always want just one set of categories, much like the play store. I personally don't mind too much about the amount of categories as long as it makes sense to have them.

First of all, I think we need to add a `description` field for the current categories so that we can expand on what `Social` or `Productivity` means for Catppuccin.

With regards to your suggestions, `Social` already exists so maybe renaming to `Social Networking` ?
`Fun` seems really vague here, pretty much all of the stuff can be under Fun depending on who you talk to haha.
`Self Hosted` seems odd because I don't know if I'd want the self-hostedness of something to be the **primary** filter that separates it.

Of course, this is regarding the markdown list. Multiple categories for the website is an absolute no brainer where it's interactive and searchable right. I'm just trying to think what would be nice for the markdown generation in the main README :thinking:

**Comment by isabelroses** [comment]
> I _feel_ this is getting into the over-engineered territory :/ I think we always want just one set of categories, much like the play store. I personally don't mind too much about the amount of categories as long as it makes sense to have them.
>
> First of all, I think we need to add a `description` field for the current categories so that we can expand on what `Social` or `Productivity` means for Catppuccin.

Completely agree, with all of this.
 
> With regards to your suggestions, `Social` already exists so maybe renaming to `Social Networking` ? 

This seems appropriate, and would narrow down what it means.

> `Fun` seems really vague here, pretty much all of the stuff can be under Fun depending on who you talk to haha. 

I feel like `Fun`  was a bit of a bad example and basically covered by `Games` anyways. 

> `Self Hosted` seems odd because I don't know if I'd want the self-hostedness of something to be the **primary** filter that separates it.

I can see where your coming from, however when it comes to userstyles, most of them are broken into there own respective categories that make more sense but for a lot of these, at least at the moment, they don't fit into a clear category, in particular  InvokeAI. Of course, this does not mean that there is not better categories out there for these userstyles.

**Comment by sgoudham** [comment]
In the case of InvokeAI, ChatGPT - I feel like those could totally come under like `Machine Learning` / `Large Language Model` or `Generative AI` right?

I think the next action for this is to go ahead with adding category descriptions and adding support for multiple categories for one port before we actually add new categories :+1:
