### ISSUE TITLE
Gitlab

### ISSUE THREAD

**Issue by NamesCode** [catppuccin/catppuccin#2232]
### Link to repository

https://github.com/NamesCode/gitlab

### Screenshots
![Mockup](https://raw.githubusercontent.com/NamesCode/gitlab/main/assets/preview.webp)
I am unable to actually run or test it since Gitlab is a proper pain.
It should hopefully work but in the likely case it doesn't I will gladly work with someone capable of testing it to fix the theme.

I really should've finished this a while ago.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave:, we've discussed this a fair bit on the discord and just outlining some of those conversations here.

As you've mentioned, this port requires two things:
1. A patch script to run.
2. A self-compiled installation once patched.

The idea of a patch script is not unique to Catppuccin so I'm more or less okay with that, but the requirement of a self-compiled installation doesn't fill me with joy. Putting aside the fact that self-compiling something as large as GitLab requires a lot more effort than installing the package binaries, GitLab's [Self-compiled installation](https://docs.gitlab.com/ee/install/installation.html) docs explicitly mentions the following:

> Because a self-compiled installation is a lot of work and error prone, we strongly recommend the fast and reliable [Linux package installation](https://about.gitlab.com/install/) (deb/rpm).
>
> One reason the Linux package is more reliable is its use of runit to restart any of the GitLab processes in case one crashes. On heavily used GitLab instances the memory usage of the Sidekiq background worker grows over time. The Linux packages solve this by [letting the Sidekiq terminate gracefully](https://docs.gitlab.com/ee/administration/sidekiq/sidekiq_memory_killer.html) if it uses too much memory. After this termination runit detects Sidekiq is not running and starts it. Because self-compiled installations don’t use runit for process supervision, Sidekiq can’t be terminated and its memory usage grows over time.

I don't really think adding our themes is worth actively worsening the reliability of the product, especially for something like GitLab. As discussed on discord, I think it's much better to focus on creating a GitLab userstyle for [catppuccin/userstyles](https://github.com/catppuccin/userstyles) which would allow Catppuccin to be applied via Stylus.

With all that being said, I notice that @Maxb0tbeep, @rxbn and @gi8lino have reacted with a thumbs up on this, would any of you be willing to self-compile and patch GitLab for Catppuccin? I've had a pretty biased view towards this but happy to hear others thoughts.

**Comment by gi8lino** [comment]
hi @sgoudham 

Thank you for the detailed answer!
While I'm open to executing a patch script, the idea of self-compiling GitLab raises concerns for me, primarily due to the effort and potential for errors.

**Comment by sgoudham** [comment]
Thanks for your insight @gi8lino, I agree and share those concerns.

Taking everything into consideration, I think it's best to close this issue as not planned and label the GitLab discussion as a potential userstyle to be included in [catppuccin/userstyles](https://github.com/catppuccin/userstyles).

Thanks @NamesCode for your efforts on this and apologies for rejecting it in its current form.

**Comment by NamesCode** [comment]
Nope, I completely agree with this decision. Maintaining this would be an absolute hell and this doesn't solve the problem across all gitlab instances
