### ISSUE TITLE
ShareX-Themes

### ISSUE THREAD

**Issue by kingofcube** [catppuccin/catppuccin#2240]
### Link to repository

https://github.com/kingofcube/sharex-theme

### Screenshots

![ShareX_8Ivzp3y2vO](https://github.com/catppuccin/catppuccin/assets/138169081/339a800d-77d2-489e-9130-6f38797f14ca)

### Any additional comments?

port aint finished, only macchiato was made (since this used to be only for me)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by vanillyn** [comment]
don't we already have a [sharex port?](https://github.com/catppuccin/sharex)

**Comment by kingofcube** [comment]
> don't we already have a [sharex port?](https://github.com/catppuccin/sharex)

ye that was a while ago, it's merged now
