### ISSUE TITLE
imv

### ISSUE THREAD

**Issue by Anomalocaridid** [catppuccin/catppuccin#2245]
### Link to repository

https://github.com/Anomalocaridid/imv

### Screenshots

![stacked screenshots of imv with all four Catppuccin flavours](https://raw.githubusercontent.com/Anomalocaridid/imv/main/assets/preview.webp)

### Any additional comments?

In case it is relevant, the screenshots were taken by running `imv -d` to show the overlay. Otherwise, the overlay is hidden by default unless you set it in `~/.config/imv/config`.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
this looks good, thanks for your contribution! i'm happy for this to be transferred to the organisation.

check out ["transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) if you need more info about this process.

we'll close this issue once the port has been added to the [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml?rgh-link-date=2024-03-15T02%3A52%3A33Z) file. you can see an example of this in https://github.com/catppuccin/catppuccin/pull/2164.

thanks!

**Comment by backwardspy** [comment]
thanks!
