### ISSUE TITLE
delta

### ISSUE THREAD

**Issue by Anomalocaridid** [catppuccin/catppuccin#2246]
### Link to repository

https://github.com/Anomalocaridid/delta

### Screenshots

![composite screenshot of a terminal window showing delta themed with all four catppuccin flavours](https://raw.githubusercontent.com/Anomalocaridid/delta/main/assets/preview.webp)

### Any additional comments?

Related discussion: #1829

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by thelooter** [comment]
One thing I noticed is that it doesn't seem properly styled when using git blame. Maybe thats a nice addition

**Comment by Anomalocaridid** [comment]
@thelooter Thanks for catching that! It should be fixed now.

**Comment by sgoudham** [comment]
Hey :wave:, nice work on this! I know it's been a long-standing discussion. The codebase looks fine, no comments from there! (Bonus points for using whiskers :smile:)

One thing that I did want to raise is the use of the colours themselves, @nekowinston and I spent a fair amount of time trying to standardise and agree upon the highlights for diffs. I've not tried the port yet myself but could you please confirm that you have followed the diff highlights as outlined in the [style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#diff--merge)? Once it matches those highlights, I think we should be good to transfer!

**Comment by Anomalocaridid** [comment]
@sgoudham You're right, I missed the opacity in the "diff and merge" section.

I fixed it and now the diff highlights are 10% for normal, 25% for emph. It certainly improves the contrast between the highlights and the text. I took a slight liberty in using the minimum for text bg, but the maximum for line bg so the emph highlights would stand out a better.

**Comment by sgoudham** [comment]
Thanks for updating those highlights! I assume you've regenerated the catwalk image too @Anomalocaridid 

Great work on this! I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164 (I think the category of cli tools is best for this one?)

**Comment by Anomalocaridid** [comment]
My mistake, the images slipped my mind. However, I just now updated them. Should I wait for you to take another look at it before transferring it?

**Comment by sgoudham** [comment]
Looks good to me! Feel free to proceed with the transfer :D
