### ISSUE TITLE
SpeedCrunch

### ISSUE THREAD

**Issue by Zazucki** [catppuccin/catppuccin#2254]
### Link to repository

https://github.com/Zazucki/speedcrunch

### Screenshots

see repo

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by Zazucki** [comment]
https://github.com/catppuccin/catppuccin/discussions/2253

**Comment by sgoudham** [comment]
Hey :wave:, thanks for working on this! I didn't even know you could theme calculators :smile: 

The theme looks great, I have a few minor comments about the codebase:

1. Please convert the `*.png` files to `*.webp` in the [assets](https://github.com/Zazucki/speedcrunch/tree/main/assets) directory. (Also please delete the `.DS_STORE`)
2. I think the [README's Usage steps](https://github.com/Zazucki/speedcrunch?tab=readme-ov-file#usage) can be simplified to the following:
	
	```
	## Usage
	
	1. Download your preferred flavor from the [themes](themes) directory.
	
	2. Copy the downloaded file to your `color-schemes` folder:

		- **Windows**: `C:/Users/<USERNAME>/AppData/Roaming/SpeedCrunch/color-schemes`
		- **Linux/Unix**: `~/.local/SpeedCrunch/color-schemes`
		- **macOS**: `~/Library/Application Support/SpeedCrunch/color-schemes`
	
	> **_NOTE:_** When using a portable version of SpeedCrunch on any operating system, additional color schemes are loaded from the `color-schemes` subdirectory in the portable application directory.
	
	3. Restart SpeedCrunch and select the theme in `Settings` -> `Display` -> `Color Scheme`.
	```
	
My comments above are pretty minor and can be fixed easily so happy to approve this for transfer into the organisation! Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164
