### ISSUE TITLE
base16

### ISSUE THREAD

**Issue by joeyschoblaska** [catppuccin/catppuccin#226]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes, it's me.

**Additional context 📷 (optional)**
https://github.com/joeyschoblaska/catppuccin-base16

If the colors look good I can make a nicer demo image for the README.

**Comment by nekowinston** [comment]
I've had a look at it, and the colours from 07-15 look solid.

There's some stuff I'd change, but I think it'd be best if we can review it as a repo on `catppuccin/base16`. Could you please mark it as `"🎨 (WIP) Soothing pastel theme for base16"` before transferring it?

I know we won't be able to replicate the official themes 1:1 with base16, but I'd like to get as close as possible. 🙂

**Comment by joeyschoblaska** [comment]
https://github.com/catppuccin/base16 🎉
