### ISSUE TITLE
Loungy - An application launcher in the vein of Spotlight, Alfred, Raycast. 

### ISSUE THREAD

**Issue by MatthiasGrandl** [catppuccin/catppuccin#2263]
### Link to repository

https://github.com/MatthiasGrandl/loungy

### Screenshots

![image](https://github.com/catppuccin/catppuccin/assets/50196894/2d470426-af2b-4186-9e3c-0c1759063ac3)

### Any additional comments?

I guess it's not a port but rather something for the showcase. The default themes are Catppuccin. Still early in development so if it's not something you want to showcase yet, no worries :)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nekowinston** [comment]
Congratulations on launching it, I saw the Zed folks shouting you out on twitter for using GPUI 🚀 

Feel free to open a PR to add your repo to the [showcase here](https://github.com/catppuccin/catppuccin/blob/be76166edb19906a8414ee9919cd39220f6cae7d/resources/ports.yml#L1142-L1166), our README is generated via that data. 🙂

**Comment by sgoudham** [comment]
As said above, congrats on launching it and cool of you to use Catppuccin!

I'll mark this as resolved as issues are usually related to ports to be transferred into the org or "meta" issues relating to the org itself, but completely happy to accept a PR to the showcase section!

**Comment by MatthiasGrandl** [comment]
Jup I will gladly open a PR soon. Just traveling right now :)
