### ISSUE TITLE
mpv

### ISSUE THREAD

**Issue by Anomalocaridid** [catppuccin/catppuccin#2269]
### Link to repository

https://github.com/Anomalocaridid/mpv

### Screenshots

![stacked screenshots of mpv themed with all four catppuccin flavours and playing a movie](https://raw.githubusercontent.com/Anomalocaridid/mpv/main/assets/preview.webp)

### Any additional comments?

The template relies on a rather recent addition to `whiskers`: https://github.com/catppuccin/toolbox/pull/120

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by Anomalocaridid** [comment]
@aman333nolawz If I understand correctly, you want the theme to support mpv's ModernX script, right? Should be doable.

**Comment by aman333nolawz** [comment]
yeah. I don't care if it is modernX or not, but I think changing some UI like osc to look more pleasing would be nice

**Comment by backwardspy** [comment]
great work, thanks!
