### ISSUE TITLE
Lavender is too subtly different from Text

### ISSUE THREAD

**Issue by gotgenes** [catppuccin/catppuccin#227]
While working with a markdown file in Neovim, I failed to notice a color distinction between the lines `1.` and `2.` as shown below.¹

<img width="282" alt="Screen Shot 2022-08-26 at 8 42 09 PM" src="https://user-images.githubusercontent.com/8517/187013176-b411d125-bc7a-411f-9261-6a2a3af7855f.png">

I initially thought some support for treesitter in catppuccin/nvim was missing. I dug into the treesitter highlighting and found that the link text was being highlighted as `TSTextReference`, which [uses lavender as the coloration](https://github.com/catppuccin/nvim/blob/2d1eda3382bc8d48554ae17eddc2923d4ea9ce07/lua/catppuccin/groups/integrations/treesitter.lua#L85).

I see from #157 that the color of Text might have moved closer to Lavender, which helps explain why I'm having trouble distinguishing between the colors.

Could you please consider making these two colors more distinct?

¹ The text in the line for `1.` ("Install chezmoi") is Lavender. The line for `2.` ("Initialize with chezmoi") is Text.

**Comment by gotgenes** [comment]
I'm revisiting this issue this morning. They look more distinct now.

I'm viewing this from the display of a M1 MacBook Pro (14" 2021). I know colors were being impacted by Night Shift, which I turned off, but that gave a modest improvement in distinction. I also think the colors were being impacted by True Tone. Both of these display settings were shifting the tones towards red.

I still want to ask if you could please consider making Text and Lavender more distinct from each other.

**Comment by backwardspy** [comment]
hey @gotgenes, thanks for raising this! while we have no *immediate* plans to change the palette, if and when such an update comes around rest assured we will take this into consideration.

cheers!
