### ISSUE TITLE
LaTeX

### ISSUE THREAD

**Issue by walshyb** [catppuccin/catppuccin#2271]
### Link to repository

https://github.com/walshyb/catppuccin-latex

### Screenshots

Latte:
![latte](https://github.com/catppuccin/catppuccin/assets/6893300/5ffea520-e464-4dba-b458-f413a1273d0f)

Frappe:
![frappe](https://github.com/catppuccin/catppuccin/assets/6893300/8ed86e8a-eaeb-43d2-8fad-3dbe90b2d416)

Macchiato:
![macchiato](https://github.com/catppuccin/catppuccin/assets/6893300/5756be37-185b-4670-bbe7-8359804690ed)

Mocha:
![mocha](https://github.com/catppuccin/catppuccin/assets/6893300/47ef6f76-c859-481a-b59c-c3c3cfb3952b)

### Any additional comments?

Known issues I'm addressing, per Hammy:

- [x] Catwalk-generated image mismatch due to variations in fed in assets
- [x] Colors in latte are different to darker flavors
- [x] Update import syntax to be `\usepackage[xyz]{catppuccin}`, where `xyz` is the flavor name (defaults to mocha if no flavor provided)

Niceties (potentially) post merge:

- [ ] Register package as official TeX package with [CTAN](https://www.ctan.org/pkg)
- [ ] Use `whiskers` to generate file(s) reliably + not have to repeat RGB values

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave:, thanks for working on this! It looks lovely! I know we've talked a fair bit about this issue on discord, so also thanks for summarising them in the checkboxes.

With regards to registering the package on CTAN, I just found their FAQ for [uploading packages](https://www.ctan.org/help/upload-pkg) which is quite detailed! I think it'd be best to track this via an issue after transfer.

I only have 2 more comments about the codebase:

1. Please update the [README badges](https://github.com/walshyb/catppuccin-latex/blob/1ab280f017cc06c3249e0f84f30db9726ed1129d/README.md?plain=1#L8-L12) to point towards `catppuccin/latex`.
2. Please update the [README asset links](https://github.com/walshyb/catppuccin-latex/blob/1ab280f017cc06c3249e0f84f30db9726ed1129d/README.md?plain=1#L14-L35) to be [relative urls](https://github.blog/2013-01-31-relative-links-in-markup-files/).

However, those can be easily carried out after the transfer so I'm happy to see this get merged into the organisation!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164 (I believe the best category for this repository is technically `library` as we're only providing colour definitions to be imported into LaTeX.)

(And of course, thanks to @nyxkrage for testing the package and providing insightful discussion on discord)
