### ISSUE TITLE
Blockbench

### ISSUE THREAD

**Issue by Tnixc** [catppuccin/catppuccin#228]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
https://github.com/Tnixc/Blockbench
I've placed my port there for now

**Comment by Pocco81** [comment]
Looking good. Let me know when you are ready to transfer the port so that we can set-up permissions and such on our end.

**Comment by Tnixc** [comment]
I've transferred it.
