### ISSUE TITLE
GitHub File Explorer Icons

### ISSUE THREAD

**Issue by uncenter** [catppuccin/catppuccin#2290]
### Link to repository

https://github.com/uncenter/ctp-github-file-explorer-icons

### Screenshots

<p align="center">
	<img src="https://github.com/uncenter/ctp-github-file-explorer-icons/raw/main/assets/previews/preview.webp"/>
</p>

<details>
<summary>🌻 Latte</summary>
<img src="https://github.com/uncenter/ctp-github-file-explorer-icons/raw/main/assets/previews/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://github.com/uncenter/ctp-github-file-explorer-icons/raw/main/assets/previews/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://github.com/uncenter/ctp-github-file-explorer-icons/raw/main/assets/previews/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://github.com/uncenter/ctp-github-file-explorer-icons/raw/main/assets/previews/mocha.webp"/>
</details>

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave: 
Repository and theme looks good, thanks for working on this! I have a few minor comments:

1. Do we need a separate `COPYING.md` when the licenses are also MIT? I think we can include them in the same header? E.g. [catppuccin/steam-deck](https://github.com/catppuccin/steam-deck/blob/2d161c148a2b3dfc695053c8501ae09d38dff2fd/LICENCE#L3-L4)
2. Are we able to deduplicate the CSS colour definitions in [style.css](https://github.com/uncenter/ctp-github-file-explorer-icons/blob/b27a60428cf35cf617e64b60ddbcfc868afe347e/src/entries/popup/styles.css#L1-L119) going forward?

Those are minor comments so I'm happy to see this get merged into the organisation! As discussed on discord, we'll transfer the extensions into the respective Catppuccin accounts on CWS & Firefox Add-Ons.

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
