### ISSUE TITLE
Serenity OS

### ISSUE THREAD

**Issue by nullishamy** [catppuccin/catppuccin#2294]
### Link to repository

https://github.com/nullishamy/ctp-serenity-os

### Screenshots

![macchiato](https://github.com/catppuccin/catppuccin/assets/99221043/3c11c5e5-bfe5-4d4b-b053-3e62559dc386)
![frappe](https://github.com/catppuccin/catppuccin/assets/99221043/b980beac-6f86-4421-8d99-527debee0905)
![mocha](https://github.com/catppuccin/catppuccin/assets/99221043/c3c2cff7-44d2-4e8f-9313-31332214b649)
![latte](https://github.com/catppuccin/catppuccin/assets/99221043/37c3d4c8-6e41-40f6-b9fe-4888086e82bd)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nullishamy** [comment]
Tracking upstream @ https://github.com/SerenityOS/serenity/pull/23429

**Comment by sgoudham** [comment]
Hey :wave: 
Thanks for working on this, it looks great!

I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164

**Comment by backwardspy** [comment]
great work!
