### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by djflan** [catppuccin/catppuccin#230]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
https://github.com/djflan/Catppuccin-Visual-Studio-Themes

**Comment by nekowinston** [comment]
Hi there 👋 

Thanks for contributing to Catppuccin! Your port's looking good, but there are 2 things that I'd like to sort out:
- [ ] Minor issue: the GitHub repo description is missing the "<allusive emoji> "Soothing pastel theme for Visual Studio" description.
- [ ] We actually have an [Azure account](https://marketplace.visualstudio.com/publishers/Catppuccin) set up, from which we distribute the VSCode theme. I'd love for this theme to be added there as well, if possible!

We can use GitHub actions to publish to the Azure pipeline, so we won't have to share login tokens.
Please let me know if you have any input on how whether we should transfer it, or upload it as a new Extension.

Thanks again for your work 😄

**Comment by djflan** [comment]
@nekowinston Fixed the emoji. (I think). I'll be completely honest, I have no idea what "allusive emoji" means unless you mean I can use any I see fit. I picked a wave, please let me know if this should be changed. Should consider revising the contribution instructions to indicate it belongs in the repo description, it is a small change, but I was super confused when I read through the steps.

I agree - the existing, official Azure account should be used for distribution, I'll remove mine from listing at your convivence. Please let me know if I can help with setup or you need any assistance. I've been popping in the discord server from time to time.

**Comment by nekowinston** [comment]
Thanks for the feedback on the contributing guidelines, I'll see if I can improve them. :+1:

I think we can handle the transfer to our Azure account after the repository has been moved to Catppuccin.
I'd appreciate if I could ping you on Discord, should I need help with rolling the release. 🙂 

I'll invite you to the org, feel free to transfer it anytime.

**Comment by djflan** [comment]
Joined. Transfer in progress :)

**Comment by nekowinston** [comment]
Thanks for the transfer, I've renamed the repository https://github.com/catppuccin/visual-studio.
I've also updated your permissions to Maintainer Access. Many thanks!

Please keep the issue open, until I add the entry on this repo's README.
