### ISSUE TITLE
Scrivener

### ISSUE THREAD

**Issue by NickSquiggles** [catppuccin/catppuccin#2300]
### Link to repository

https://github.com/NickSquiggles/scrivener

### Screenshots

![preview](https://github.com/catppuccin/catppuccin/assets/375991/a13f6fc7-0c6b-4f55-84fa-1b108a9acbe5)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
repo looks good! i noticed that catwalk layered the drop shadow in the main preview screenshot so it gets darker to the left, i've sent you an edited version to fix that if you'd like to use it.

**Comment by backwardspy** [comment]
comments from @sgoudham on discord:

- "Keep Main Editor Light Option" could be a lower level heading to group it properly in the usage section.
- `!NOTE` callout about macOS support might be better as an `!IMPORTANT` callout instead.

**Comment by NickSquiggles** [comment]
> comments from @sgoudham on discord:
> 
> * "Keep Main Editor Light Option" could be a lower level heading to group it properly in the usage section.
> * `!NOTE` callout about macOS support might be better as an `!IMPORTANT` callout instead.

Thanks, I have made these changes.

**Comment by sgoudham** [comment]
Hey 👋 

Thanks @backwardspy for replying with my comments, I was meaning to get around to it but have been pretty busy. 

I would have also accepted your port for transfer as my comments were mostly README nitpicks/suggestions that could be easily committed at a later date, thanks for applying them!

I'm happy for it to be transferred over to the organisation! Will send you an invite to be a maintainer. Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164 (The `categories` is actually now a list - need to add documentation sorry!)

**Comment by backwardspy** [comment]
thanks @NickSquiggles and @sgoudham!
