### ISSUE TITLE
Giscus

### ISSUE THREAD

**Issue by uncenter** [catppuccin/catppuccin#2313]
### Link to repository

https://github.com/uncenter/ctp-giscus

### Screenshots

<p align="center">
	<img src="https://github.com/uncenter/ctp-giscus/raw/main/assets/previews/preview.webp"/>
</p>

<details>
<summary>🌻 Latte</summary>
<img src="https://github.com/uncenter/ctp-giscus/raw/main/assets/previews/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://github.com/uncenter/ctp-giscus/raw/main/assets/previews/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://github.com/uncenter/ctp-giscus/raw/main/assets/previews/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://github.com/uncenter/ctp-giscus/raw/main/assets/previews/mocha.webp"/>
</details>

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave: 

Repository looks good, thanks for your work on this! We'll transfer the URLs after transfer.

 I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by uncenter** [comment]
Transferred! I'll make a PR to ports.yml in a second.
