### ISSUE TITLE
Semantic Highlighting - basedpyright

### ISSUE THREAD

**Issue by karimlevallois** [catppuccin/catppuccin#2320]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

With the release of the new pyright fork basedpyright, semantic highlighting has now been enabled within Python. However, it looks like something might have to be updated in catppuccin as enabling semantic highlighting seems to change functions from peach to blue.

Please see my comments / screenshots on the below issue:-

https://github.com/DetachHead/basedpyright/issues/176

**Comment by backwardspy** [comment]
judging from your comments there i assume you're referring to the neovim port. please raise an issue over at [catppuccin/nvim](https://github.com/catppuccin/nvim).
thanks!
