### ISSUE TITLE
Gradience

### ISSUE THREAD

**Issue by sininen-blue** [catppuccin/catppuccin#236]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
[scrceenshot of gradience (forgot to save color palette), drawing, thunar, and alacritty-mocha](https://imgur.com/a/PwXmKmN)
[Gradience](https://flathub.org/apps/details/com.github.GradienceTeam.Gradience) is a color customizer tool for adwaita 3 and 4 that recently released on flathub. I'm aware that there's already a gtk theme for catppucccin, but changing themes can be quite the hassle and I actually do like the adwaita look  but just want the colors to match

**Comment by ghostx31** [comment]
I had a look at the tool. It seems it makes changes to the Adwaita and adw-gtk3. Can the configuration changes made be exported or imported from within the application?

I'd suggest making a repository as well and porting all the four flavours of the theme. You might wanna take a look at style guide while making these flavours :)

**Comment by sininen-blue** [comment]
From my knowledge, you can make a json file that you can import to Gradience.
I'm not very well versed in designing stuff but the style guide seems to have most of the stuff necessary, I'll see what I can do

**Comment by sininen-blue** [comment]
[screenshot](https://imgur.com/a/Bu1R8mG)
Here's something that I'm quite happy with and  I _think_ it follows the standards set in the style guide. I'll probably make the repo tomorrow and start work on the other flavors

**Comment by ghostx31** [comment]
This looks good. Looking forward to your repository and the other flavours!
Just a bit of suggestion in the screenshot you linked. The selected elements (or the `Apply` button too) are probably sky while the written text is white. It leads to poor readability. If possible, try to change the colour of the text for selected element to the _text_ colour. All else is good enough!

**Comment by sininen-blue** [comment]
https://github.com/sininen-blue/Gradience
still a few things missing, namely
- a better, more symmetric preview, and
- the palette colors not being changed

**Comment by nekowinston** [comment]
Hey @sininen-blue, thanks for your work - I'd really love to get this to the org! ❤️ 

For the preview I can suggest our tool [catwalk](https://github.com/catppuccin/toolbox#catwalk). Please let me know whenever you feel that this is ready for review. 🙂

**Comment by mdeboer** [comment]
Ohlala, great work so far! Keep it up and I hope your laptop gets fixed soon!

**Comment by nekowinston** [comment]
Seems like this has been merged [upstream](https://github.com/GradienceTeam/Community/pull/39)

**Comment by SpomJ** [comment]
> Seems like this has been merged [upstream](https://github.com/GradienceTeam/Community/pull/39)

But it is pretty inaccurate and in some modal dialogs yo can barely see text.
