### ISSUE TITLE
Gleam

### ISSUE THREAD

**Issue by MAHcodes** [catppuccin/catppuccin#2368]
### Link to repository

https://github.com/MAHcodes/catppuccin

### Submission Guidelines

- [x] I have read and followed Catppuccin's submission guidelines.

**Comment by MAHcodes** [comment]
I'm writing the build script...

**Comment by MAHcodes** [comment]
I wrote the build script, and used it to generate the library files under the `lib`directory

**Comment by sgoudham** [comment]
Hey :wave: 

Thanks for porting the palette to Gleam! A few things:

1. Please update the code generation to use a pinned version of the palette JSON, this can be done either by copying a version of the palette.json locally into the repository or using a pinned commit hash. FYI: https://github.com/catppuccin/palette/pull/81 has been merged which may or may not break your current builds
2. Update the LICENSE to be [Catppuccin](https://github.com/catppuccin/template/blob/4335bca70b2cc4b8bdd1b51164005207f46aeff6/LICENSE#L3)

Happy to approve after these changes are carried out!

Also can you document / let me know how the repository is published to https://hexdocs.pm/catppuccin/? I don't see a publish script/task or any CI/CD workflows. Is it automatically driven by the `gleam.toml`?

**Comment by MAHcodes** [comment]
Hey @sgoudham,

Thanks for the review! I've fixed all the issues. Feel free to suggest any further code improvements.

For now, there's no CI/CD pipeline in place. I'm publishing the library through Gleam CLI.

**Comment by sgoudham** [comment]
Great, thanks for pushing out those updates (I believe you need to update the Usage section in the README too!)

It'd be great to get a CI/CD pipeline in place for publishing to Gleam, happy to collaborate further on this! We usually try to publish our packages under a shared organisation account, does Gleam support that concept or is it just 1 library -> 1 author for now? Not a blocker but figured I'd ask anyways.

Happy to approve and get it merged into the organisation, thanks for your work again and apologies for the wait!

You should shortly receive an email inviting you to be apart of the Catppuccin GitHub organisation. Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by MAHcodes** [comment]
Alright, so it seems possible to publish packages with an organiazation on Hex here: https://hex.pm/docs/faq#can-i-publish-public-packages-with-an-organization, I'll need either the organization name you want to use or the author name if you prefer me to transfer ownership here: https://hex.pm/docs/faq#can-i-transfer-ownership-of-a-package.

For CI/CD, I will create a GitHub workflow that will automatically publish the package to Hex.pm whenever a new release is created on GitHub.

**Comment by MAHcodes** [comment]
I updated the README with the links and implemented CI/CD, which successfully published the latest release to Hex.
