### ISSUE TITLE
daisyui

### ISSUE THREAD

**Issue by Liumingxun** [catppuccin/catppuccin#2379]
### Link to repository

https://github.com/Liumingxun/daisyui

### Screenshots

![preview](https://raw.githubusercontent.com/Liumingxun/daisyui/main/assets/previews/preview.webp)

### Any additional comments?

haven't published on npmjs.com

now can use `npm install https://github.com/Liumingxun/daisyui` for test, and provide example in the repo

link #2285 

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave: 
Thanks for your work on this. 

I've looked into daisyui and it looks like it relies solely upon TailwindCSS, which we already have an existing port/repository for. I'd like to make the same argument/case as I did for [shadcn-ui (view comment)](https://github.com/catppuccin/catppuccin/issues/2270#issuecomment-1974954170).

I'd rather not merge a new repository for something that seems like it can be added to [catppuccin/tailwindcss ](https://github.com/catppuccin/tailwindcss)without too much maintenance burden?

Feel free to share your thoughts!

**Comment by Liumingxun** [comment]
@sgoudham Yes, daisyui is a TailwindCSS component library. However, its theme definition does not depend on the TailwindCSS color palette, but [use color value directly](https://github.com/saadeghi/daisyui/blob/master/src/theming/themes.js). I just try use the palette [catppuccin/tailwindcss](https://github.com/catppuccin/tailwindcss) added, [it can't access](https://stackblitz.com/edit/daisyui-vite-mf21bf?file=tailwind.config.js) and doesn't work.

I still believe there should be a stand-alone port for this.

**Comment by Skarian** [comment]
> @sgoudham Yes, daisyui is a TailwindCSS component library. However, its theme definition does not depend on the TailwindCSS color palette, but [use color value directly](https://github.com/saadeghi/daisyui/blob/master/src/theming/themes.js). I just try use the palette [catppuccin/tailwindcss](https://github.com/catppuccin/tailwindcss) added, [it can't access](https://stackblitz.com/edit/daisyui-vite-mf21bf?file=tailwind.config.js) and doesn't work.
> 
> I still believe there should be a stand-alone port for this.

I agree with this take. I've wasted most of my morning getting catppuccin color palette into DaisyUI manually. The tailwindcss color palette published did not fit into DaisyUI's design system.

This solves that for me and probably many others.

Thanks @Liumingxun for building, if this can't be merged here please consider publishing independently.

**Comment by sgoudham** [comment]
> However, its theme definition does not depend on the TailwindCSS color palette

Thanks for letting me know. I'd be okay with it existing as a separate repository given your reasoning. 

I've got a few comments regarding the repository/theme:

1. Does the [dist](https://github.com/Liumingxun/daisyui/tree/main/dist) directory need to be committed into the repository? 
2. I don't believe [info](https://github.com/Liumingxun/daisyui/blob/80f7c63e012c674de2e6def76160380846804553/src/index.ts#L54) should be `rosewater`. We tend not to use `rosewater` for anything meaningful across our ports, aside from the terminal cursor colour. Please switch info to `blue`.
3. To me, it feels odd that [accent](https://github.com/Liumingxun/daisyui/blob/80f7c63e012c674de2e6def76160380846804553/src/index.ts#L49) defaults to a single colour. The accent variant in Catppuccin means that the colour can be any one of the "rainbow" colours defined in each flavour. E.g.

	![image](https://github.com/catppuccin/catppuccin/assets/58985301/e29afb22-e4bc-4b90-9817-a5ff7455312f)
	
	Can we modify the configuration API to allow users to choose the flavour + accent, instead of just the flavour? Where accent is one of the rainbow colours shown above. E.g. something like `catppuccin("latte", "mauve"),` 
	
I'd be happy to merge if `2.` is at least implemented and we can raise issues / discuss other bulletpoints afterwards. Thanks for creating the repository :+1:

**Comment by sgoudham** [comment]
Thanks for updating @Liumingxun, I'm honestly a bit unsure what to put as the `primary` and `secondary` colours - maybe @unseen-ninja has some opinions here.

In any case, I think we can raise issues afterwards to discuss improvements/refactors, happy to approve for now and get it transferred to the organisation!

You should receive an email invitation to join the repository soon, I'll generate the creds for publishing to the NPM organisation and I believe we'd want to essentially copy/paste the [publish actions workflow from catppuccin/insomnia](https://github.com/catppuccin/insomnia/blob/main/.github/workflows/npm-publish.yml). I'd quite like to use [release-please](https://github.com/googleapis/release-please) more across the organisation but it might be a fair amount of learning that you don't want to do so a tag based workflow is also fine to me.

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. You can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164
