### ISSUE TITLE
PlugData Theme

### ISSUE THREAD

**Issue by GSNinjaMusic** [catppuccin/catppuccin#2385]
### Link to repository

https://github.com/plugdata-team/plugdata

### Screenshots

![c33aa9f5-2613-4f55-b530-85b83c097a60](https://github.com/catppuccin/catppuccin/assets/84602064/32d8dd9a-7644-49ed-a759-1db4c6f2b295)

![9165d19b-73b2-4037-9336-7ac0e0f9e9e7](https://github.com/catppuccin/catppuccin/assets/84602064/7bee4232-3b4b-4e23-9239-db079bf917e3)

![5a75a5b2-9308-477a-bcb9-4437e6a2ba20](https://github.com/catppuccin/catppuccin/assets/84602064/5d739dda-54e1-45e9-b3fd-3b754045689e)

![4499aa44-3e99-4ed9-96ff-3d9ed935debf](https://github.com/catppuccin/catppuccin/assets/84602064/46cef351-3f36-4460-855b-0f94f4ee1071)

![06cf8177-17ab-4444-a5e2-033090d9f3cf](https://github.com/catppuccin/catppuccin/assets/84602064/cb80eb72-2efb-4b26-96ac-e61ee1402d41)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Issues are reserved for ports that have already been themed, please raise a [Port Request](https://github.com/catppuccin/catppuccin/discussions/new?category=port-requests) instead.
