### ISSUE TITLE
sent

### ISSUE THREAD

**Issue by xzi** [catppuccin/catppuccin#2390]
### Link to repository

https://github.com/xzi/sent

### Screenshots

![image](https://github.com/catppuccin/catppuccin/assets/96212687/78402411-a3e3-4151-9c0e-dfdd9c7e0c30)
![image](https://github.com/catppuccin/catppuccin/assets/96212687/eb682fa3-2f48-4bce-a11e-4a0a1fe7e847)
![image](https://github.com/catppuccin/catppuccin/assets/96212687/6abbd6b7-7078-407b-862d-c3a14b5c3f45)
![image](https://github.com/catppuccin/catppuccin/assets/96212687/b0c7abbd-dbb4-42ad-97b6-93227ed0e7fd)
![image](https://github.com/catppuccin/catppuccin/assets/96212687/2e140cb7-ce1a-4f10-a388-17552eb92679)

### Any additional comments?

A dream told me to make this. Don't know what else to put here

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave:, sorry for taking so long on officially reviewing this.

Thanks for using whiskers! The repository looks good. Just one comment from me - I see that we have a duplicated template for the `text` variant aside from the accents. We can deduplicate this by making use of the `overrides` flag in Whiskers. 

E.g. to generate the `text` variant from the `sent-accents.tera` file, we can simply run `whiskers templates/sent-accents.tera --overrides '{ "accent": "text" }'`. 

This can be pretty easily carried out at any point so I'm happy to approve the port and get it merged into the organisation!

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by xzi** [comment]
Hey incredibly sorry for the wait, I don't check my email and just flat out didn't see the notification. If you could reinvite me to the org that would be great. Thank you!

**Comment by sgoudham** [comment]
No worries, reinvited!

**Comment by xzi** [comment]
Finally got around to sending it in. It has been transferred over. Is there anything else I need to do?
