### ISSUE TITLE
mixplorer

### ISSUE THREAD

**Issue by auriafoxgirl** [catppuccin/catppuccin#2392]
### Link to repository

https://github.com/auriafoxgirl/mixplorer

### Screenshots

![meow](https://github.com/catppuccin/catppuccin/assets/53555592/b9e2478c-1000-486e-9b7c-5fdc8b482211)

### Any additional comments?

meow

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by soymadip** [comment]
Hello, when will this get merge?

**Comment by backwardspy** [comment]
> Hello, when will this get merge?

@soymadip have you tested this, or if not are you able to? if so, could you offer some thoughts on your experience with it? that would actually help the review process quite a bit!

in the meantime @auriafoxgirl, thanks for your contribution! i have some comments about the repo itself:

1. the stars/issues/contributors badges at the top of the readme should link to `catppuccin/mixplorer` (they won't work until the repo is transferred, but that's fine)
2. the readme heading `Genering all theme flavors and accentd s with script yourself` has some typos
3. requiring both lua and python to build the theme is a lot, can this be simplified? my suggestions would be to implement the lua parts in python, or take a look at [whiskers](https://github.com/catppuccin/whiskers)
	- as part of this, consider building the theme from our [palette.json](https://github.com/catppuccin/palette/blob/main/palette.json) instead of duplicating the palette data. (if you use whiskers, this step isn't necessary)

that's all for now, let me know what you think.

**Comment by auriafoxgirl** [comment]
fixed badges at top and typos
im unsure if whiskers is able to put things automatically into zip with `.mit` extention, i could try rewriting lua parts in python

**Comment by auriafoxgirl** [comment]
Oh and i wanted to ask about `palette.json` should i just include it in repository?

**Comment by auriafoxgirl** [comment]
Done! Now it uses python only and catppuccin python library

**Comment by backwardspy** [comment]
nice work! that looks really good. i have one more suggestion to make, then i think we'd be happy to accept this port.

rather than keeping the zips tracked in the repo itself, we'd prefer to upload them as release artifacts instead. that way cloning the repo doesn't pull down all the historical build artifacts, while keeping downloads easy for our users.

once you've made that change, let me know and i'll send you an org invite!

**Comment by soymadip** [comment]
> > Hello, when will this get merge?
> 
> @soymadip have you tested this, or if not are you able to? if so, could you offer some thoughts on your experience with it? that would actually help the review process quite a bit!
> 
> in the meantime @auriafoxgirl, thanks for your contribution! i have some comments about the repo itself:
> 
>     1. the stars/issues/contributors badges at the top of the readme should link to `catppuccin/mixplorer` (they won't work until the repo is transferred, but that's fine)
> 
>     2. the readme heading `Genering all theme flavors and accentd s with script yourself` has some typos
> 
>     3. requiring both lua and python to build the theme is a lot, can this be simplified? my suggestions would be to implement the lua parts in python, or take a look at [whiskers](https://github.com/catppuccin/whiskers)
>        
>        * as part of this, consider building the theme from our [palette.json](https://github.com/catppuccin/palette/blob/main/palette.json) instead of duplicating the palette data. (if you use whiskers, this step isn't necessary)
> 
> 
> that's all for now, let me know what you think.

Oh yeah, i installed the mocha-lavender one before but will install all of them, then will say...

**Comment by auriafoxgirl** [comment]
> nice work! that looks really good. i have one more suggestion to make, then i think we'd be happy to accept this port.
> 
> rather than keeping the zips tracked in the repo itself, we'd prefer to upload them as release artifacts instead. that way cloning the repo doesn't pull down all the historical build artifacts, while keeping downloads easy for our users.
> 
> once you've made that change, let me know and i'll send you an org invite!

done now download is in releases

**Comment by backwardspy** [comment]
> Oh yeah, i installed the mocha-lavender one before but will install all of them, then will say...

@soymadip no need, if you've installed one without issue then that's good enough for me! i just like somebody other than the creator to give it a test just to double check for any issues that might have been passed over.

> done now download is in releases

@auriafoxgirl awesome, looks great! i have sent you an invite to the organisation. once you have accepted it, you may transfer the repository as `catppuccin/mixplorer`. please refer to [transferring a repository owned by your personal account](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) if you are not familiar with this process.

**we will close this issue when the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml).** you can find an example of this in https://github.com/catppuccin/catppuccin/pull/2378.
