### ISSUE TITLE
Lapce

### ISSUE THREAD

**Issue by Relwi** [catppuccin/catppuccin#240]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
https://github.com/lapce/lapce

**Comment by nekowinston** [comment]
Hi there :wave:

A port exists @ https://github.com/ghishadow/lapce-catppuccin

I've reached out to the author on [our Discord](https://discord.catppuccin.com), this is the rational why it isn't transferred *yet*.
![CleanShot 2022-09-05 at 14 32 01](https://user-images.githubusercontent.com/79978224/188450014-37df0652-fa48-47e1-b5f9-0eab311a958b.png)

**Comment by ghishadow** [comment]
I am interested in moving it to Catppuccin org, @nekowinston can you review if I am missing anything for transfer https://github.com/ghishadow/lapce-catppuccin

**Comment by nekowinston** [comment]
Hi @ghishadow :wave:

Thanks for wanting to port it over! Some things the repo doesn't have at the moment:
- Catppuccin is MIT Licensed, the repo itself is Apache-2.0 licensed. Please consider re-licensing under MIT.
- There's no need to add the `FUNDING.yml` in your repo, we have a [global file](https://github.com/catppuccin/.github/blob/main/FUNDING.yml). 🙂 
- Please link to lapce.dev in your README
```diff
<h3 align="center">
 <img src="https://raw.githubusercontent.com/catppuccin/catppuccin/dev/assets/logos/exports/1544x1544_circle.png" width="100" alt="Logo"/><br/>
 <img src="https://raw.githubusercontent.com/catppuccin/catppuccin/dev/assets/misc/transparent.png" height="30" width="0px"/>
-  Catppuccin for Lapce
+  Catppuccin for <a href="https://github.com/lapce/lapce">Lapce</a>
 <img src="https://raw.githubusercontent.com/catppuccin/catppuccin/dev/assets/misc/transparent.png" height="30" width="0px"/>
</h3>
```

**Comment by nekowinston** [comment]
hey there @ghishadow, sorry for not checking in since your last commit, the repo looks good now!

I'll add you to maintainers, feel free to transfer it anytime.
