### ISSUE TITLE
Windows 9x

### ISSUE THREAD

**Issue by backwardspy** [catppuccin/catppuccin#2406]
### Link to repository

https://github.com/backwardspy/ctp-windows9x

### Screenshots

![image](https://github.com/catppuccin/catppuccin/assets/289746/5ac57e48-00b4-4701-9e18-57ffd67bcfca)

### Any additional comments?

the port you've all been waiting for

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by somerand0mcat** [comment]
you should make catppuccin for windows xp/2000

**Comment by muffinV136** [comment]
> you should make Catppuccin for windows xp/2000 too

That should be its own repo(s) personally.

**Comment by muffinV136** [comment]
I like the idea of what's going on here, and should be generally easy to create without needing maintaining. I will offer to help make the creation of the theme if needed.

**Comment by sgoudham** [comment]
Transfer it :+1:

**Comment by backwardspy** [comment]
transferred it 👍
