### ISSUE TITLE
Waybar

### ISSUE THREAD

**Issue by Relwi** [catppuccin/catppuccin#241]
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Additional context 📷 (optional)**
https://github.com/Alexays/Waybar

**Comment by rubyowo** [comment]
i have this https://github.com/rubyowo/waybar
just need to add the preview image

**Comment by nekowinston** [comment]
Transferred to https://github.com/catppuccin/waybar
Thanks @rubyowo!
