### ISSUE TITLE
Elixir

### ISSUE THREAD

**Issue by MikaelFangel** [catppuccin/catppuccin#2416]
### Link to repository

https://github.com/MikaelFangel/elixir

### Screenshots

I don't have any screenshots to show because it is a port for a programming language.

### Any additional comments?

I know about the existence of the gleam port and that it works with the BEAM engine. However, I still think that a pure Elixir port has its merits as it is easier to manage dependency wise.

I've currently only linked the dependency as a GitHub link because the name is conflicting with the gleam package on Hex.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by backwardspy** [comment]
hey, thanks for your work on this!

> However, I still think that a pure Elixir port has its merits as it is easier to manage dependency wise.

would you mind elaborating on this a little? i'm not super familiar with the ecosystem, so it would help me understand where this sits in relation to gleam.

**Comment by MikaelFangel** [comment]
Of course. The thing is that gleam and elixir shares the package repository Hex and both compile to intermediate code that can be run on the BEAM virtual machine. This means that you can use gleam package in elixir but you have to include the gleam compiler to your mix project (and maybe some other changes, not sure) and because the gleam library also depends on gleam colours this library also needs inclusion. One could argue the above is easy, but again this might not be so apparent to newcomers. 

But, if you use the pure elixir port I've just written you only need to include the dependency in your mix project and then you are able to use it. 

About the Hex issue, because is share across gleam and elixir there can only be one package with the name catppuccin (currently the gleam package). 

One last detail which I don't if matters, but I would also argue Elixir as of writting is the most popular language of the two.

**Comment by sgoudham** [comment]
Thanks for explaining @MikaelFangel, I'm happy to have Elixir as a separate repository.

I suppose the one "blocker" for this is the existing gleam package that has been published in Hex already. Do you know if we can rename the package to something like `catppuccin_gleam` @MAHcodes ?

Although, that being said, I feel like there must be other packages before Catppuccin that may have gleam / elixir / erlang variants. How have they handled the potential naming conflict?

**Comment by MAHcodes** [comment]
Unfortunately, it's not possible to rename a package on hex afaik, the hex repository is designed to be immutable, meaning published packages cannot be changed or removed after publication. 

One thing we can do, is to publish a new package with the name `catppuccin_gleam`, then retire the current package (deprecate).

> Instead of unpublishing we recommend to instead retire a package or release. This should be done if the maintainers no longer recommend its use, because it does not work, has security issues, been deprecated or any other reason. A package is retired with the `mix hex.retire` task. A retired package will still be resolvable and fetchable but users of the package will get a warning message and the website will show the release as retired.
> 
> https://hex.pm/docs/faq#can-packages-be-removed-from-the-repository

**Comment by MikaelFangel** [comment]
I think that it would be better to come up with some name for the Elixir package instead, so we avoid the breaking change of "renaming" the existing lib. Maybe the name could be `ex_catppuccin` if we publish it on hex. Another idea could be to just manage the package via GitHub as suggested by my repo (:

**Comment by sgoudham** [comment]
> I think that it would be better to come up with some name for the Elixir package instead, so we avoid the breaking change of "renaming" the existing lib. Maybe the name could be `ex_catppuccin` if we publish it on hex. Another idea could be to just manage the package via GitHub as suggested by my repo (:

Ah sorry! I didn't even realise that you had it working via GitHub. I agree with @backwardspy!

I'll allocate some time this weekend to give the repository a review if @backwardspy doesn't get around to it beforehand.

**Comment by sgoudham** [comment]
Sorry for the wait! @MikaelFangel 

I can't speak much to the code but it looks good and it seems like it's been well designed alongside the data structure of the `palette.json`.

I've got a few comments about the repository:

1. Our other repositories don't include a [Palette section](https://github.com/MikaelFangel/elixir#-palette) in the README so I think this should be removed.
2. As a result of the previous point, the [assets directory](https://github.com/MikaelFangel/elixir/tree/main/assets) should be deleted. 
3. You have a typo in the filename: https://github.com/MikaelFangel/elixir/blob/main/lib/catppuccin/catppucin.ex (there's a missing `c` in the `.ex` file. Please update this to be `catppuccin.ex`.
4. We're starting to use [Renovate](https://docs.renovatebot.com/) across the organisation so I would remove the [dependabot configuration file](https://github.com/MikaelFangel/elixir/blob/main/.github/dependabot.yml)
5. We're starting to use [release-please](https://github.com/googleapis/release-please) across the repositories in the organisation, would you be interested in adopting this workflow? I can only assume that you are manually publishing tags from looking at the releases.

I'm happy to approve after `3.` is carried out, the other things can be implemented and/or discussed at a later point in time :+1:

**Comment by MikaelFangel** [comment]
No worries!

I've addressed all points except 5 but yes I would be interested in adopting the workflow.

**Comment by backwardspy** [comment]
@MikaelFangel thank you for doing all of that! i have invited you to join the organisation. once you have accepted the invitation, feel free to transfer the repository over as `catppuccin/elixir`.

please see [transferring a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) if you're unsure about this process.

**we'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**. you can find an example of this in https://github.com/catppuccin/catppuccin/pull/2164

**Comment by backwardspy** [comment]
great work!
