### ISSUE TITLE
Newsboat (help needed)

### ISSUE THREAD

**Issue by ignamartinoli** [catppuccin/catppuccin#243]
**Are you available to help in the creation of this port? 😄**

Yes

**Additional context 📷**

Sometime ago [this issue](https://github.com/catppuccin/catppuccin/issues/143) was created. I fell in love with it. Unfortunately the creator vanished. This is what it looked like.

![164674640-fa1c248f-9d41-4644-9310-b5991c93cb1a](https://user-images.githubusercontent.com/103866722/188364955-24422d5e-4d02-4005-ba76-d42786e0027e.png)

![164674731-736cc41f-f9eb-4e86-bb39-6b72cb263fb4](https://user-images.githubusercontent.com/103866722/188363293-4c25bba6-d6bb-41b5-b3e5-7dbc86556a65.png)

As you can see, I was able to get quite close.

![20220905015750](https://user-images.githubusercontent.com/103866722/188363579-301bd8ad-212a-4be8-b9e8-a10de46e4f01.png)

![20220905015754](https://user-images.githubusercontent.com/103866722/188363588-7c3fe56c-8ad9-4307-997e-3fb0be5c341f.png)

I understand how it was configured, but I still can't get right the background color and some other shades of colors.
**Newsboat** only accepts `256-xterm` ([for reference](http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html)).

To approximate the color codes I use [this script](https://github.com/soarpenguin/python-scripts/blob/master/colortrans.py).
I suck at recognizing colors, so if somebody can tell me what are the hex codes, I can finish this up and pull for this to get merged.

Any help is appreciated :D

**Comment by nekowinston** [comment]
Hey there :wave:
I use newsboat myself, but haven't themed it yet.
Depending on how busy I am in the coming days, I'd be open to take a look at it.

**Comment by ignamartinoli** [comment]
Hey Felix ahah :D,

that's great to hear! I was trying to put side-by-side the `xterm-256` color chart, and the themed **Newsboat** but I can't get which color the original creator is using, so for now I use the default background.

Tell me when you're available and we can test this out

**Comment by xor** [comment]
+1 I also use newsboat, and I've searched catppuccin theme for newsboat.

**Comment by ignamartinoli** [comment]
In the last few days I got the hang of how ricing **Newsboat** works and I made some progress, if someone just tells me the hex codes (I don't have a color picker on **Wayland** and I suck at colors) I can convert them to `xterm-256` and push it.

I got something close to the original already

**Comment by iamlambda** [comment]
Hi @ignamartinoli, thanks for your work (:
You can find the hex codes for each flavour of catppuccin here : https://github.com/catppuccin/catppuccin#-palettes

**Comment by ignamartinoli** [comment]
Thanks @iamlambda, I'm working on it. I'm still wrapping my head around the background color used. I tried some combinations but it doesn't look like a color from the palette, is more something between **Base** and **Lavender**

**Comment by nekowinston** [comment]
Seems like the screenshots in the terminal are off, because the terminal didn't render `base` properly - `#1e1f2e`.
Please follow the style guide and use `base` as the main background color for the official port draft.

**Comment by ignamartinoli** [comment]
Update, for now I worked using the **Mocha** flavour as reference. I improved all the colors and they look good now, the only exception is the background.

**Base** is used for that, so I put the hex code into the converter to get a `xterm-256` equivalent.

```
sicro@sicro ~ $ python colortrans.py #1e1e2e
RGB #1e1e2e -> xterm color approx 16 (000000)
```

After using that color, I don't know if it's me, but it just looks too dark. This is a side-by-side comparison with the **Neovim** theme.
Maybe the script I'm using is approximating wrong.

![20220911190417](https://user-images.githubusercontent.com/103866722/189550754-0091bed1-2dd9-426b-b68a-a3546b233fbf.png)

**Comment by nekowinston** [comment]
Are you using Catppuccin for your terminal? `base0` should be exactly `#1e1e2e`. 🤔 

Could you share your current progress as a simple gist? I'd love to take a look at it.

**Comment by ignamartinoli** [comment]
This is what I have so far: https://gist.github.com/ignamartinoli/ee6dd255bcd44c504720e16f633c4a52

I use **Catppuccin** official theme for **Kitty** and **Neovim**, I also use it for my **Waybar** modules

**Comment by nekowinston** [comment]
@ignamartinoli tried a little something
https://gist.github.com/nekowinston/b386f803d9772231abe683ed43781f51

**Comment by ignamartinoli** [comment]
@nekowinston really love the idea of the green color for unread items

> just edited it, I missed the `[1]` link selectors, sorry about that

what do you mean?

**Comment by nekowinston** [comment]
> what do you mean?
Edited it 60 seconds after posting that comment, apologies.

What's your take on the current state of it, I can't see anything I missed on my end.

Pink for the header is a matter of the user's taste of course - I just like it.

**Comment by ignamartinoli** [comment]
I am tweaking with it.
Another thing I like is using `color0` as the focused background. It looks like `vim.opt.cursorline = true` and adds a lot to the user experience.
One thing we could improve on that is adding the `bold` modifier to focused items.

For link selectors I used _Blue_, which is the color assigned for tags (I guess that could be the best approximation).
For links the specifications suggest _Rosewater_.
These are all only suggestions from a generalized specification, but they don't look that bad. Check it and tell me your review on that, I'm really open on this.

I updated [the code](https://gist.github.com/ignamartinoli/ee6dd255bcd44c504720e16f633c4a52) merging things from both our configurations.
It's still work in progress so any feedback can help to improve this to some final form :D

**Comment by nekowinston** [comment]
Just made some tweaks on my end, and created a basic repo for it:
https://github.com/catppuccin/newsboat

Please let me know how I can properly add you as a co-author for it.

**Comment by ignamartinoli** [comment]
Wow, this is beginning to take shape.

What documentation are you using? I am using [this](https://newsboat.org/releases/2.13/docs/newsboat.html#color) and I couldn't find an `<element>` list.

> Please let me know how I can properly add you as a co-author for it.

I'm really not that skilled with GitHub but I think you have to add me as a _Contributor_, not entirely sure how that can be done tho, I'm investigating on it.

Also I really like the direction the theme is going, I'm experimenting to see if some red can be added to have a more complete color range

**Comment by nekowinston** [comment]
I've had to rebase the repository to add you as a co-author, but you show up now; I've also invited you with write access.

Could we possibly have a chat? We have our [discord](https://discord.catppuccin.com/), but I'm up for Matrix as well. I feel like we could cooperate faster that way.

**Comment by nekowinston** [comment]
Repo is up at https://github.com/catppuccin/newsboat, it's marked as WIP for now, dark theme works reasonably well, Latte is soon to follow.

You can follow the `#newsboat` [thread](https://discord.com/channels/907385605422448742/1018732168895287326) on the [Discord](https://discord.catppuccin.com/) if you're interested.
