### ISSUE TITLE
Unarchive `catppuccin/oldtwitter`

### ISSUE THREAD

**Issue by muffinV136** [catppuccin/catppuccin#2430]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### What is your concern?

It appears that the catppuccin/oldtwitter repository has been archived. I believe it shouldn't as the Old Twitter extension simply requires a load without the extension on and then can be used from there on. Sorry if I am bugging anybody here.

**Comment by sgoudham** [comment]
Thanks for raising this issue, it made me realise that I haven't properly documented that `catppuccin/oldtwitter` is archived in the [ports.yml](https://github.com/catppuccin/catppuccin/blob/800212e92a62fda2133c8a54353136844ae96d7e/resources/ports.yml#L1343).

I believe @isabelincorp was the one to archive it so I'd like to get her thoughts on if it can be unarchived.

**Comment by isabelincorp** [comment]
Thanks for raising the issue @muffinV136 ! Unfortunately, Oldtwitter is just too dangerous to use and a nice catppuccin rice shouldn't be what gets you suspended on X/Twitter. For that reason, we are keeping this port archived.

See https://github.com/dimdenGD/OldTwitter/issues/828

**Comment by sgoudham** [comment]
Thanks @isabelincorp for clarifying. I updated the README to reflect this comment and will be closing this issue as I don't think we'll unarchive it.

**Comment by muffinV136** [comment]
I had no clue this was suspending people on Twitter, and now respect the decision that has been made here. If it has been banning and suspending people I personally think it should be archived too. Your welcome for the accidental notification of the undocumented archived repo.
-muffin
