### ISSUE TITLE
zsh

### ISSUE THREAD

**Issue by JannoTjarks** [catppuccin/catppuccin#2434]
### Link to repository

https://github.com/JannoTjarks/zsh

### Screenshots

![image](https://github.com/catppuccin/catppuccin/assets/33316737/af7aafc7-b5b2-4a66-87bc-25c2e66a9f50)

### Any additional comments?

Theme for the ZSH Prompt. Includes decorators for current directory, exit status of last command and git status.

Would like to continue supporting this project after submission. I have some ideas, e.g, a second line to the prompt or different time formats.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave: 

While we appreciate your work, I don't believe we'll be merging this into the organisation. 

`oh-my-zsh` has been brought up before in #145 and #2007 and rejected largely for the same reasons. The _theme_ for such an application is effectively a personalised prompt configuration, which we've moved away from adopting. Our main concern for zsh is the syntax highlighting which we already have ports for in https://github.com/catppuccin/zsh-syntax-highlighting and  https://github.com/catppuccin/zsh-fsh.

We do have a port for https://github.com/catppuccin/starship but that is implemented in such a way to be a "copy/paste" configuration of the palette and avoid any opinionated config, best described in https://github.com/catppuccin/starship/pull/4#issuecomment-1973724028.

I hope that makes sense on why we might reject this repository. Thank you again for taking the time to create this repository but I will be closing this issue as not planned. 

P.S. Make use of https://github.com/catppuccin/whiskers if you're creating themes for Catppuccin, it can make developing a port like this super easy!
