### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by waldirborbajr** [catppuccin/catppuccin#245]
I'm facing a weird message every time that I open NVim, I've just removed catppucin folder and reinstalled it but the same annoying message.

POP/OS : Linux heimdall 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux

NVIM v0.8.0-dev-701-g2a9c9371b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Plugins installed...
Error detected while processing /home/borba/.local/share/nvim/site/pack/packer/start/**catppuccin**/colors/catp
puccin.lua:
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name
W18: Invalid character in group name

**Comment by nekowinston** [comment]
Please see the relevant issue on https://github.com/catppuccin/nvim: https://github.com/catppuccin/nvim/issues/262

Essentially: please update your NeoVim Nightly.
