### ISSUE TITLE
Aliucord

### ISSUE THREAD

**Issue by myumichi** [catppuccin/catppuccin#2453]
### Link to repository

https://github.com/myumichi/aliucord.git

### Screenshots

![latte-preview](https://github.com/catppuccin/catppuccin/assets/156945548/d3063d4a-faa3-4c14-b8fd-13f94621fd6f)
![frappe-preview](https://github.com/catppuccin/catppuccin/assets/156945548/14a3f9f6-4a29-412e-948e-b3287714609e)
![macchiato-preview](https://github.com/catppuccin/catppuccin/assets/156945548/51b3c4af-5043-42f0-9b92-8c32f6b9132a)
![mocha-preview](https://github.com/catppuccin/catppuccin/assets/156945548/571bb9d5-1d48-4c78-94e7-d47063667679)

### Any additional comments?

- This is a _revamp_ of the original Aliucord port, everything was done from scratch and was improved upon immensely. 
- This will be actively maintained, as strings are still being discovered in Aliucord. I also plan to add other accents.
- Due to the nature of Aliucord's theming, Latte's blue in the `accent` string had to be changed to `#437ff7` to improve readability. I can go more in depth if needed.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave: 

Thanks for taking the time to revamp the theme, I've unarchived the [catppuccin/aliucord](https://github.com/catppuccin/aliucord) repository and I'm happy to accept your changes in a Pull Request!

I'll invite you to the organisation afterwards so that you can gain maintain permissions on the repository.

**Comment by sgoudham** [comment]
Merged your PR! I'll invite you to the organisation now so that you can be added as a maintainer of the repository. Thanks again for your work in revamping it all!

I'll close this issue once aliucord has been marked as unarchived in our `ports.yml` file.
