### ISSUE TITLE
Fnott

### ISSUE THREAD

**Issue by tranzystorekk** [catppuccin/catppuccin#2454]
### Link to repository

https://github.com/tranzystorekk/catppuccin-fnott

### Screenshots

![latte](https://github.com/catppuccin/catppuccin/assets/5671049/6d663bd0-462e-48e6-af95-6d64ba1c9ccb)
![frappe](https://github.com/catppuccin/catppuccin/assets/5671049/e84fcd36-ba74-4816-863d-c59baf82f3d2)
![macchiato](https://github.com/catppuccin/catppuccin/assets/5671049/d3dacfea-4019-464f-95f5-6c50cd81cd52)
![mocha](https://github.com/catppuccin/catppuccin/assets/5671049/7a47c535-032b-40cb-858e-f5d8e8da2c0f)

### Any additional comments?

Haven't added any CI yet, but I used whiskers and added a standard `just` config, so it should be straightforward.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave: 
Thanks for submitting this (and thank you for using whiskers!)

With regards to CI, we are planning to have an official whiskers action implemented for the organisation to use soon :tm: 

Just some minor things about the codebase:

1. Please convert all the assets to `.webp`
2. You can easily generate all of the accent variations with whiskers by also specifying `- accent` in the matrix. To see an example of this, see [catppuccin/ueli](https://github.com/catppuccin/ueli/blob/72d0e5e74a75006aff5b0826a9ebc00f2e7b9832/ueli.tera#L4-L7).

In any case, I'm happy to approve it for transfer into the organisation and the comments above can be implemented at a later stage. Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
