### ISSUE TITLE
Error detected while processing /root/.local/share/nvim/site/pack/packer/start/nvim/colors/catppuccin.lua

### ISSUE THREAD

**Issue by zhanglin2018** [catppuccin/catppuccin#247]
W18: Invalid character in group name

**Comment by zhanglin2018** [comment]
could you please help fix this issue

**Comment by nullchilly** [comment]
Please update your neovim nightly before opening an issue

**Comment by nekowinston** [comment]
Please see https://github.com/catppuccin/nvim/issues/262
