### ISSUE TITLE
CSS variables

### ISSUE THREAD

**Issue by he3als** [catppuccin/catppuccin#248]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
It would be nice to have a bunch of HTML variables for each Catppuccin pallet for use on websites.

**Comment by nekowinston** [comment]
Hi there :wave:
Have you had a look at our [palette](https://github.com/catppuccin/palette/tree/main/css) repo? It might help, it has css variables.

**Comment by he3als** [comment]
Ah sorry, I couldn't find it anywhere. Thank you

**Comment by nekowinston** [comment]
No worries, we were discussing a better way of pointing out those repositories, that help *you* with implementing the theme elsewhere. We'll likely change the current README soon to highlight those better, and explicitly mention NPM, CSS, SASS.
