### ISSUE TITLE
Yatline

### ISSUE THREAD

**Issue by imsi32** [catppuccin/catppuccin#2480]
### Link to repository

https://github.com/imsi32/yatline-catppuccin.yazi.git

### Screenshots

![latte](https://github.com/user-attachments/assets/56fad556-7398-4d4a-bc22-205ba7a77d7b)
![frappe](https://github.com/user-attachments/assets/695f8d63-6a5b-4014-86a0-7d54e2ccf104)
![macchiato](https://github.com/user-attachments/assets/5ca5ff64-3d85-4387-b3de-a3c2825709ad)
![mocha](https://github.com/user-attachments/assets/6562468c-625a-44df-a027-9daef39a737e)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey :wave:,
Thanks for raising this issue and your work!

We already have a [catppuccin/yazi](https://github.com/catppuccin/yazi) port and I believe this work would be better integrated into that existing repository via PR? I believe @uncenter was thinking along the same lines.

**Comment by uncenter** [comment]
I'm thinking a `plugins/` directory in your catppuccin/yazi port would be ideal, and we can drop your plugin in there almost as is - keeping the directions with the plugin makes sense to me, and we can link to the available plugins and what they do in the main README. Feel free to open a PR to the repo!

**Comment by imsi32** [comment]
Alright I will try making it.

**Comment by uncenter** [comment]
Awesome! We have a channel for our Yazi port in the Catppuccin Discord server, if you have questions asking me there would probably be best for both of us :)
