### ISSUE TITLE
MySQL Workbench

### ISSUE THREAD

**Issue by andreasgrafen** [catppuccin/catppuccin#250]
Kinda sad that there's little to none themes for MySQL Workbench. It would be nice if there's a catpuccin "code_editor.xml" for MySQL Workbench.

<sup>Originally posted by **alexxShandsome** September 14, 2022 in https://github.com/catppuccin/catppuccin/discussions/249</sup>

**Comment by ReKylee** [comment]
+1

**Comment by jairmedeiros** [comment]
@ghostx31 why this was closed?
