### ISSUE TITLE
The Archive

### ISSUE THREAD

**Issue by rogeruiz** [catppuccin/catppuccin#2519]
### Link to repository

https://github.com/rogeruiz/the-archive

### Screenshots

<details>
<summary>Original screenshots are in here.</summary>

<img width="1310" alt="latte" src="https://github.com/user-attachments/assets/48c31f10-68b5-4884-8bda-ca3ed48cebe3">
<img width="1310" alt="frappe" src="https://github.com/user-attachments/assets/658913de-5946-45f3-b64b-5fcc9f78569e">
<img width="1310" alt="macchiato" src="https://github.com/user-attachments/assets/9575b17b-9819-42dc-b690-11642ade139c">
<img width="1310" alt="mocha" src="https://github.com/user-attachments/assets/92378bca-7964-44ce-a08b-e9771145d170">

</details>

![stacked](https://github.com/user-attachments/assets/2ff348c0-97cb-4302-a824-da429b67ff05)

### Any additional comments?

I still have some work to do like running `catwalk` on the screenshots. But I wanted to submit this for review to start so I can get feedback. I'd like the most scrutiny in the screenshots and the `syntax.tera` file. I believe I have followed the style guide and the theme looks good in my day-to-day usage of The Archive.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by uncenter** [comment]
Not seeing any files in that repository besides the default template files by the way. Perhaps you forgot to push your latest changes?

**Comment by rogeruiz** [comment]
thanks @uncenter I did forget. But they're pushed now.

**Comment by uncenter** [comment]
- The naming pattern of the Whiskers/Tera template file we have been using is `<port>.tera`. So I would change `syntax.tera` to `the-archive.tera`.
- Seeing as the name of each theme is in the JSON itself, I would simplify the filename in the Whiskers template:
```diff
-  filename: "Catppuccin {{ flavor.name }}.theme.json"
+  filename: "catppuccin-{{ flavor.identifier }}.theme.json"
```
- Instead of `flavor.colors.base`, you can do just `base`. This applies to all colors of course! You can do a find and replace to get rid of it (replace "flavor.colors." with "").

On the syntax itself:
- [Comments](https://github.com/rogeruiz/the-archive/blob/227dc42f9850ec12ca43626cf1c82be09dcf7ca2/syntax.tera#L169-L174) should be `overlay0` (see https://github.com/catppuccin/vscode/blob/2d7388ffe7321f588b2f54e2ffaab9fb7c9dde14/packages/catppuccin-vsc/src/theme/tokens/index.ts#L50-L57).

**Comment by rogeruiz** [comment]
Thanks for the feedback @uncenter. I've updated the source of the files and
generated JSON.

I'll tackle the rest of the documentation as well. Since these themes are going
to be submitted upstream to the `Zettelkasten-Method/The-Archive-Themes`
repository once it lands in the Catppuccin organization, should I write the
documentation with the assumption that it's in the main application? I'll write
a fallback for now where it'll assume that it's a manual installation so people
have options. I suspect it'll get added quickly to that repository but I have no
idea.

**Comment by sgoudham** [comment]
Quick comment from me is that whiskers needs to be updated to 2.4.0 in order removed the `flavor.colors` prefix from each key. 

Our bad for not updating the versions / examples 👍

**Comment by rogeruiz** [comment]
I also realize that I need to re-create the composite screenshot to not have a
shadow because it looks bad. 🤮

**Comment by rogeruiz** [comment]
> Quick comment from me is that whiskers needs to be updated to 2.4.0 in order to remove the `flavor.colors` prefix from each key.
> 
> Our bad for not updating the versions / examples 👍

I've updated the `whiskers` version to `2.4.0`. 🚀

**Comment by rogeruiz** [comment]
Okay, @uncenter. I've updated the repository with documentation and better
looking screenshots. Let me know if there's anything else I need to do before I
go submitting the theme upstream to `Zettelkasten-Method/The-Archive-Themes`. 

Also, the `catppuccin/whiskers` and `catppuccin/catwalk` CLI tools are amazing.
They were a pleasure to work with @sgoudham!

**Comment by uncenter** [comment]
Looks great! This is what you can put it in the `justfile`:

```
_default:
  @just --list

build:
  whiskers the-archive.tera
```

**Comment by rogeruiz** [comment]
@sgoudham I've updated the screenshots here and in the repository to use Mauve as the highlight/carat color rather than Rosewater. 👍🏽

**Comment by sgoudham** [comment]
Hey :wave:,

I had a look over the repository and didn't anything to comment on, think we ticked off everything in the comments above! Great work on this! I'm happy for it to be transferred over to the organisation! 

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.

**Comment by sgoudham** [comment]
It's probably worth editing the README to mention that Catppuccin will only be included by default once https://github.com/Zettelkasten-Method/The-Archive-Themes/pull/19 lands.

**Comment by rogeruiz** [comment]
Good catch @sgoudham. I'll get started on the transfer process now.
