### ISSUE TITLE
Chroma (Syntax Highlighter)

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/catppuccin#252]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Talking about https://github.com/alecthomas/chroma

**Comment by sgoudham** [comment]
Some additional context for those interested ;)

https://twitter.com/caarlos0/status/1570246272287907841?t=9n9fhVvj982IUeXK_EAbNQ&s=19

**Comment by caarlos0** [comment]
Yes! This is uses by Hugo (the static site generator), so having catppuccin on chroma would mean being able to use it on Hugo as well (after hugo updates to latest chroma).

**Comment by jolheiser** [comment]
I have opened https://github.com/alecthomas/chroma/pull/685, however currently it's just the mocha variant. 
Let me know if there is interest in generating all four variants. 

I'll probably generate them all over at https://github.com/jolheiser/chroma-catppuccin regardless, but I'm not sure if all of them would make sense directly in chroma.

**Comment by jolheiser** [comment]
The PR has been merged, so this issue can likely be closed. 🙂
