### ISSUE TITLE
Libre Office

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [catppuccin/catppuccin#2527]
### Link to repository

https://github.com/NeonGamerBot-QK/catppuccin-libre-office

### Screenshots

<img src="https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/master/assets/preview.webp?raw=1"/>

### Any additional comments?

Closes https://github.com/catppuccin/catppuccin/discussions/2350

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by shadow-absorber** [comment]
nice seems to be working fine

**Comment by NeonGamerBot-QK** [comment]
any updates on this?

**Comment by sgoudham** [comment]
Not a full review but just from skimming the codebase:

1. Please remove the `INSTALLATION.md`
2. If overwriting the Appliation Colours are only supported on macos and linux, is there a reason to check for a Windows path in the [bash script](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/87669beee6a42290ff74405ad356ba2dcf2c5c2d/scripts/install_theme.sh#L7-L9)?

**Comment by NeonGamerBot-QK** [comment]
> Not a full review but just from skimming the codebase:
> 
>     1. Please remove the `INSTALLATION.md`
> 
>     2. If overwriting the Appliation Colours are only supported on macos and linux, is there a reason to check for a Windows path in the [bash script](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/87669beee6a42290ff74405ad356ba2dcf2c5c2d/scripts/install_theme.sh#L7-L9)?

fixed!

**Comment by sgoudham** [comment]
Hey :wave:,
Sorry for the wait, finally got around to trying out the theme and I've got a few comments:

1. I still think the README can be clearer, I'd appreciate it if you could update it to like below:

	```md
	## Usage

	### Color Palette

	Replace the variables `<flavor>` and `<accent>` with the values that you want to use from the [themes](./themes) folder. E.g. (flavor as `mocha` and accent as `mauve`)

	Copy the `.soc` file (`themes/<flavor>/<accent>/catppuccin-<flavor>-<accent>.soc`) to the correct path for your operating system:

	- **Linux**: `${XDG_CONFIG_HOME:-$HOME/.config}"/libreoffice/*/user/config/`
	- **macOS**: `$HOME/Library/Application Support/LibreOffice"/*/user/config/`
	- **Windows**: `$HOME/AppData/Roaming/LibreOffice"/*/user/config/`

	### Application Colors

	> [!IMPORTANT]  
	> Application Colors can only be modified on macOS and Linux.

	> [!WARNING]  
	> This will backup and overwrite the `registrymodifications.xcu` configuration file. 

	Run the [scripts/install_theme.sh](./scripts/install_theme.sh) script.

	E.g. `./scripts/install_theme.sh themes/mocha/mauve/catppuccin-mocha-mauve.xcu`
	```

2. I wasn't able to get the Application Colors working on my Linux machine (LibreOffice v7.3.7.2) even after following the instructions so I'm not sure if it's that reliable even on macOS/Linux. Maybe we want a warning that it doesn't always work?

4. I'd update your [shebang](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L1) to be `#!/usr/bin/env bash`. ([SO Post](https://stackoverflow.com/questions/16365130/what-is-the-difference-between-usr-bin-env-bash-and-usr-bin-bash))

5. There isn't any input validation on [`$1`](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L2) so someone might end up accidentally appending some random file into the configuration file. I'd update the script to take the flavour and accent as `$1` and `$2` to reduce the chance of that.

6. I'd append the datetime to this [backup](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L16-L17) in case the user wants to run the script again (which also begs the question, what happens if they want to change the flavour/accent that they've installed?) 

7. These [variables](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L28-L29) aren't being used as far as I can see so they should be removed.

All these comments are docs/script related which can be carried out after transfer. I'd just like to confirm that the Application Colors work for someone else on Linux. 

@shadow-absorber, @Airradda & @MacjaZival - Did you have any success applying the Application Colours?

**Comment by MacjaZival** [comment]
> Hey :wave:,
> Sorry for the wait, finally got around to trying out the theme and I've got a few comments:
> 
> 1. I still think the README can be clearer, I'd appreciate it if you could update it to like below:
> 
> 	```md
> 	## Usage
> 
> 	### Color Palette
> 
> 	Replace the variables `<flavor>` and `<accent>` with the values that you want to use from the [themes](./themes) folder. E.g. (flavor as `mocha` and accent as `mauve`)
> 
> 	Copy the `.soc` file (`themes/<flavor>/<accent>/catppuccin-<flavor>-<accent>.soc`) to the correct path for your operating system:
> 
> 	- **Linux**: `${XDG_CONFIG_HOME:-$HOME/.config}"/libreoffice/*/user/config/`
> 	- **macOS**: `$HOME/Library/Application Support/LibreOffice"/*/user/config/`
> 	- **Windows**: `$HOME/AppData/Roaming/LibreOffice"/*/user/config/`
> 
> 	### Application Colors
> 
> 	> [!IMPORTANT]  
> 	> Application Colors can only be modified on macOS and Linux.
> 
> 	> [!WARNING]  
> 	> This will backup and overwrite the `registrymodifications.xcu` configuration file. 
> 
> 	Run the [scripts/install_theme.sh](./scripts/install_theme.sh) script.
> 
> 	E.g. `./scripts/install_theme.sh themes/mocha/mauve/catppuccin-mocha-mauve.xcu`
> 	```
> 
> 2. I wasn't able to get the Application Colors working on my Linux machine (LibreOffice v7.3.7.2) even after following the instructions so I'm not sure if it's that reliable even on macOS/Linux. Maybe we want a warning that it doesn't always work?
> 
> 4. I'd update your [shebang](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L1) to be `#!/usr/bin/env bash`. ([SO Post](https://stackoverflow.com/questions/16365130/what-is-the-difference-between-usr-bin-env-bash-and-usr-bin-bash))
> 
> 5. There isn't any input validation on [`$1`](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L2) so someone might end up accidentally appending some random file into the configuration file. I'd update the script to take the flavour and accent as `$1` and `$2` to reduce the chance of that.
> 
> 6. I'd append the datetime to this [backup](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L16-L17) in case the user wants to run the script again (which also begs the question, what happens if they want to change the flavour/accent that they've installed?) 
> 
> 7. These [variables](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L28-L29) aren't being used as far as I can see so they should be removed.
> 
> All these comments are docs/script related which can be carried out after transfer. I'd just like to confirm that the Application Colors work for someone else on Linux/macOS. 
> 
> @shadow-absorber, @Airradda & @MacjaZival - Did you have any success applying the Application Colours?

No, for me it did not work.

**Comment by NeonGamerBot-QK** [comment]
> > Hey 👋,
> > Sorry for the wait, finally got around to trying out the theme and I've got a few comments:
> > 
> > 1. I still think the README can be clearer, I'd appreciate it if you could update it to like below:
> > 
> > ```
> >  ## Usage
> > 
> >  ### Color Palette
> > 
> >  Replace the variables `<flavor>` and `<accent>` with the values that you want to use from the [themes](./themes) folder. E.g. (flavor as `mocha` and accent as `mauve`)
> > 
> >  Copy the `.soc` file (`themes/<flavor>/<accent>/catppuccin-<flavor>-<accent>.soc`) to the correct path for your operating system:
> > 
> >  - **Linux**: `${XDG_CONFIG_HOME:-$HOME/.config}"/libreoffice/*/user/config/`
> >  - **macOS**: `$HOME/Library/Application Support/LibreOffice"/*/user/config/`
> >  - **Windows**: `$HOME/AppData/Roaming/LibreOffice"/*/user/config/`
> > 
> >  ### Application Colors
> > 
> >  > [!IMPORTANT]  
> >  > Application Colors can only be modified on macOS and Linux.
> > 
> >  > [!WARNING]  
> >  > This will backup and overwrite the `registrymodifications.xcu` configuration file. 
> > 
> >  Run the [scripts/install_theme.sh](./scripts/install_theme.sh) script.
> > 
> >  E.g. `./scripts/install_theme.sh themes/mocha/mauve/catppuccin-mocha-mauve.xcu`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. I wasn't able to get the Application Colors working on my Linux machine (LibreOffice v7.3.7.2) even after following the instructions so I'm not sure if it's that reliable even on macOS/Linux. Maybe we want a warning that it doesn't always work?
> > 3. I'd update your [shebang](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L1) to be `#!/usr/bin/env bash`. ([SO Post](https://stackoverflow.com/questions/16365130/what-is-the-difference-between-usr-bin-env-bash-and-usr-bin-bash))
> > 4. There isn't any input validation on [`$1`](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L2) so someone might end up accidentally appending some random file into the configuration file. I'd update the script to take the flavour and accent as `$1` and `$2` to reduce the chance of that.
> > 5. I'd append the datetime to this [backup](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L16-L17) in case the user wants to run the script again (which also begs the question, what happens if they want to change the flavour/accent that they've installed?)
> > 6. These [variables](https://github.com/NeonGamerBot-QK/catppuccin-libre-office/blob/e5dbbad06ba7f0534c1da9e959f33ee12f037f55/scripts/install_theme.sh#L28-L29) aren't being used as far as I can see so they should be removed.
> > 
> > All these comments are docs/script related which can be carried out after transfer. I'd just like to confirm that the Application Colors work for someone else on Linux/macOS.
> > @shadow-absorber, @Airradda & @MacjaZival - Did you have any success applying the Application Colours?
> 
> No, for me it did not work.

Thank you for your response @MacjaZival . could you please open an issue with the device info (`uname -a` works ) and steps to recreate!

**Comment by sgoudham** [comment]
Thanks for your patience on this issue @NeonGamerBot-QK.

I'm personally happy to approve the port for transfer given that it does seem to be working and issues can be raised later if people have problems with applying the application colours.

Please read, ["Transferring a repository owned by your personal account"](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account), if you are unsure about the process of transferring the repository to Catppuccin.

**We'll close this issue once the port has been added to our [ports.yml](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml)**.
