### ISSUE TITLE
Prism.js

### ISSUE THREAD

**Issue by uncenter** [catppuccin/catppuccin#2529]
### Link to repository

https://github.com/uncenter/ctp-prismjs

### Screenshots

![image](https://github.com/user-attachments/assets/0200274c-1bac-429f-af4a-d162cc29177a)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by sgoudham** [comment]
Hey 👋,

Happy to approve after testing out it out on our samples, great work!
(sidenote, given how many highlights we seem to be theming - probably adding a separate category for it)

Feel free to transfer it 👍

**Comment by uncenter** [comment]
Transfered and PR made. Could you set up the Catppuccin CNAME and you or I can update the links in the README?

**Comment by sgoudham** [comment]
Can do
