### ISSUE TITLE
Zipline

### ISSUE THREAD

**Issue by cswimr** [catppuccin/catppuccin#2543]
### Link to repository

https://github.com/diced/zipline

### Screenshots

![337776286-a3231878-2121-4f27-95d5-a560412a80a9](https://github.com/user-attachments/assets/72fca8f7-1e1c-450e-820f-2422a5c0cc05)
![337776299-eb55e01b-e4af-45ff-8f1c-47b3d61b32df](https://github.com/user-attachments/assets/79435385-6b01-4afc-8495-fb942ef336a0)
![337776304-1d99136e-fa41-4a63-b1d4-585cb5e3bb46](https://github.com/user-attachments/assets/14179a53-aa6d-4a05-9316-03223841aba2)
![337776309-c66dc18d-ccb9-471e-a4e5-6db9005d41fa](https://github.com/user-attachments/assets/da2b4114-f526-40d6-9ae0-7db74445f4e8)

### Any additional comments?

So, this isn't a traditional port. But, I am the person who added Catppuccin themes to Zipline. Someone said on my pr that I should make an issue here, so here we go! Here's the merged pr: https://github.com/diced/zipline/pull/560

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by cswimr** [comment]
I think that light mode screenshot is wrong actually, but I'm not able to take a new screenshot atm.

**Comment by sgoudham** [comment]
Hey :wave:,

Thanks for your work and getting it included by default. Somewhat unfortunately, this leaves us in a bit of a weird position as I don't believe there's anything for the organisation to do here? 

As far as I can tell, Zipline doesn't have any way of providing a custom theme file so it doesn't make much sense to me to create a repository based under the organisation at the moment.

**Comment by cswimr** [comment]
Could it not be added to the website still as a port? Or does that require a repository within the Catppuccin org?

**Comment by sgoudham** [comment]
At the moment, we expect that every port has a related GitHub repository so it's currently unable to be added to the website.

However, this may act as a kickstarter on the discussion on how we want to link to upstream implementations of Catppuccin that don't have a repository in our organisation. My personal question is actually _if we want to do this_ because I'm not exactly fond of that idea.

**Comment by sgoudham** [comment]
Going to close this as not planned for the moment as I think it's a slippery slope for us as an organisation to currently try and track every upstream implementation of Catppuccin without any backlinks/reference to anything in the organisation.

As I've said above, we might revisit this decision. In any case, thanks for your work in upstreaming the palette and I hope this is okay!
