### ISSUE TITLE
Catppuccin - KDE Plasma (all features available only on 5, 6 is 99.9% cause it does not have tiling.)

### ISSUE THREAD

**Issue by enessmr** [catppuccin/catppuccin#2585]
### Link to repository

https://github.com/Jas-SinghFSU/Catppuccin-Plasma

### Screenshots

In the link, it's already there.

I did not test it.

### Any additional comments?

No.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by enessmr** [comment]
For integrating with website.

**Comment by backwardspy** [comment]
hi @enessmr! could you clarify for me your intention with opening this issue? i'm unsure whether you're submitting it as a port, a showcase item, or something else.

if you're submitting it as a port, i would like to refer you to our existing KDE port over at [catppuccin/kde](https://github.com/catppuccin/kde).
if this is your own project and you'd like it showcased, you can PR it into [the showcase section of our ports file](https://github.com/catppuccin/catppuccin/blob/main/resources/ports.yml#L2441-L2477).

thanks!

**Comment by enessmr** [comment]
you can add Unofficial-Plasma to your website.

**Comment by sgoudham** [comment]
Hey 👋,
Thanks for letting us know about this repository, looks nice!

Unfortunately, I will be closing this issue as not planned for the reasons @backwardspy mentioned above. We are not currently looking to link to "unofficial" repositories from our website.

Hope that makes sense, thanks!
