### ISSUE TITLE
Hyprlauncher

### ISSUE THREAD

**Issue by adamperkowski** [catppuccin/catppuccin#2605]
### Link to repository

https://github.com/adamperkowski/hyprlauncher.git

### Screenshots

<img src="https://raw.githubusercontent.com/adamperkowski/hyprlauncher/main/assets/previews/preview.webp"/><br>
<details>
<summary>🌻 Latte</summary>
<img src="https://raw.githubusercontent.com/adamperkowski/hyprlauncher/main/assets/previews/latte.webp"/>
</details>
<details>
<summary>🪴 Frappé</summary>
<img src="https://raw.githubusercontent.com/adamperkowski/hyprlauncher/main/assets/previews/frappe.webp"/>
</details>
<details>
<summary>🌺 Macchiato</summary>
<img src="https://raw.githubusercontent.com/adamperkowski/hyprlauncher/main/assets/previews/macchiato.webp"/>
</details>
<details>
<summary>🌿 Mocha</summary>
<img src="https://raw.githubusercontent.com/adamperkowski/hyprlauncher/main/assets/previews/mocha.webp"/>
</details>

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by arminius-smh** [comment]
I think you would want to use whiskers to generate the colors/config file: https://github.com/catppuccin/whiskers

This would help to easily modify new variables and edit the config in one place instead of editing every theme individually, risking any mistakes or typos and ensuring consistancy

**Comment by adamperkowski** [comment]
@arminius-smh @sgoudham Done in [v0.1.2](https://github.com/adamperkowski/hyprlauncher/releases/tag/v0.1.2)

**Comment by adamperkowski** [comment]
![2024-12-27_11-49](https://github.com/user-attachments/assets/37bf348c-eea4-4d9d-8035-cd5712f916b8)
and he did...
