### ISSUE TITLE
unpkg.com : Cannot find package @catppuccin/palette@latest

### ISSUE THREAD

**Issue by ijsbol** [catppuccin/catppuccin#2627]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your concern?

The NPM page is 404ing 😅
<img width="737" alt="Screenshot 2024-12-08 at 18 49 49" src="https://github.com/user-attachments/assets/6ec3d35d-f407-480e-b641-fbcf321cfb0d">

**Comment by sgoudham** [comment]
I thought Renovate was the reason for PRs closing around the org but this makes sense now...

https://github.com/renovatebot/renovate/discussions/32976#discussioncomment-11501304

**Comment by ijsbol** [comment]
seems npm has resolved this :)
