### ISSUE TITLE
Rofi

### ISSUE THREAD

**Issue by l3gacyb3ta** [catppuccin/catppuccin#28]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
![screenshot](https://user-images.githubusercontent.com/58434499/149577980-92412569-342a-48c8-a4e0-153c8a02f2ff.png)
Tada!

**Comment by Yoliani** [comment]
![unknown-1.png](https://user-images.githubusercontent.com/70610879/149647660-de3c34de-8905-4d55-874a-a7aadf26aa63.png)

**Comment by latipun7** [comment]
Does catppuccin already has Rofi?
Here: https://github.com/catppuccin/rofi

**Comment by latipun7** [comment]
I mean, this issue should be closed, right?

**Comment by AlphaTechnolog** [comment]
> I mean, this issue should be closed, right?

Yes, but I can't, @l3gacyb3ta you can close this?

**Comment by l3gacyb3ta** [comment]
Oops! I didn't get even see that! Thanks y'all so much.
