### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by CelestialN3ko** [catppuccin/catppuccin#29]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
![image](https://user-images.githubusercontent.com/63929325/149678983-32532c57-2841-4217-b12b-25452d37689f.png)

**Comment by andreasgrafen** [comment]
Duplicate of #19 
Nice looking port tho! c:

**Comment by Felice-Neko** [comment]
Yea, I only noticed it when I wanted to submit this request. It's different tho.

**Comment by andreasgrafen** [comment]
Well, it's a port request, I guess? No worries tho, I'm sure it's fine.
Don't you have a repo for the ports too? Might be nice to link that, no? o:

**Comment by CelestialN3ko** [comment]
[https://github.com/CelestialN3ko/catppuccin-firefox](url)

**Comment by Pocco81** [comment]
@CelestialN3ko before it's added to the org and the theme pushed to Firefox's official theme website, could you add instructions on how to use the theme to the README?

**Comment by CelestialN3ko** [comment]
I made some changes to my repo and now the readme is also done. Also the themes are on firefox's add-ons, I would appreciate it if some people can try them and give me feedback.

**Comment by CelestialN3ko** [comment]
I fixed some things, everything should be done now.

**Comment by Pocco81** [comment]
Closing this issue because the port is ready: https://github.com/catppuccin/firefox
