### ISSUE TITLE
GTK port

### ISSUE THREAD

**Issue by Pocco81** [catppuccin/catppuccin#3]
Initially requested here: https://www.reddit.com/r/unixporn/comments/rc33mf/oc_catppuccin_a_new_soft_and_warm_theme_for_your/hntyo7s?utm_medium=android_app&utm_source=share&context=3

**Comment by broccoli5** [comment]
I decided that I will look in to it over the weekend 😅. I just need to know if you want to modify some existing theme (and if so which one) or if we should make one from scratch

**Comment by Pocco81** [comment]
I started looking into this today too. We should most definitely make fork one instead of making it from scratch, because that'd be a lot of working. I've been lurking around some gtk themes and they seem to be kind of complex. So yeah, we'd be better off doing that :+1:

**Comment by artilate** [comment]
If you want a simple yet good looking theme to fork, Adwaita dark will be great.

**Comment by broccoli5** [comment]
@artilate that was my initial idea too, but Adwaita is licensed under LGPL-2.1+, not MIT.

I'm also not sure how customizable it is because these days it's actually not really a theme, but part of GTK and is packaged as `libadwaita`

**Comment by broccoli5** [comment]
Also from what I have seen most GTK themes are licensed as GPL-3/2, which means no sublicensing.

So this theme will probably have to be a exception and be licensed as GPL-*.

Or we make one from scratch to license it as MIT (/s)

As for themes, I was looking at ARC (dark), Adapta and the Dracula theme

**Comment by di-effe** [comment]
Hi there, big fan of the project :)
Any updates on this port or need help for testing?

**Comment by artilate** [comment]
@di-effe If you want more active updates for this project, I highly recommend joining the discord. Someone on the discord made a gtk theme that got completed yesterday. Here is the [link](https://github.com/sadrach-cl/catppuccin-gtk). Not sure if it will be added to the official organization.

**Comment by Pocco81** [comment]
As @artilate mentioned, I too recommend you join the Discord server. Most of the discussions are carried there regarding the development of new ports and ideas. The developer of the GTK port finished it yesterday, which means that we'll be moving it to the org very soon. In the mean time, you can find it [here](https://github.com/sadrach-cl/catppuccin-gtk).

And btw @di-effe, I loved your LeftWM rice!! I found it yesterday and it looks really pretty. Also liked the fact that you left very detailed instructions in the README. Congrats on that :+1: we also have a dedicated channel for rices on the server, so if you want you can post it there and other users will give you feedback ;)

**Comment by di-effe** [comment]
Thanks guys, both for the info and about my LeftWM theme :)
It is still a work in progress but it already feels like home

**Comment by broccoli5** [comment]
@Pocco81 Sorry for not communicating better, I was really busy over the holidays. Nice to see that someone made the theme already.

Also I will be moving to NixOS, probably today or tomorrow, so IDK when I will be able to help out with more ports. But at least it will give a opportunity to properly test the Gnome Terminal port.

And while you are guys talking about the Discord, can you send me a new invite link the one in the readme doesn't work for me, thank you.

**Comment by Pocco81** [comment]
> And while you are guys talking about the Discord, can you send me a new invite link the one in the readme doesn't work for me, thank you.

huh, that's weird. What exactly is not working?

**Comment by broccoli5** [comment]
Sorry for the late reply 😅 when I try to accept the invite I just get a "Whoops... Unable to accept invite". I tried it few times and I'm logged in

**Comment by Deottive** [comment]
Can you change the corner radius its just too much and makes windows look bad if they have a active hint which one uses in Pop! shell aur maybe release 2 versions one with less borders or something ??

**Comment by Pocco81** [comment]
Closing because the port is ready and further discussions can be carried out there: https://github.com/catppuccin/gtk

![ss](https://user-images.githubusercontent.com/58336662/149874664-a9a6eeaf-8621-4eb6-9fba-735be0843ab7.png)
