### ISSUE TITLE
Contour

### ISSUE THREAD

**Issue by TarunDaCoder** [catppuccin/catppuccin#31]
**Are you available to help in the creation of this port? 😄**
Yes

**Additional context 📷**
Screenshot:
![image](https://user-images.githubusercontent.com/77536695/149898493-53fd19a7-5eba-450e-9d0a-c7f0b2d88d10.png)
*sorry for the weird icons in my neofetch config

**Comment by Pocco81** [comment]
Awesome! Do you have it in a repo already?

**Comment by TarunDaCoder** [comment]
> Awesome! Do you have it in a repo already?

Yup, https://github.com/TarunDaCoder/catpuccin_contour
