### ISSUE TITLE
Emacs

### ISSUE THREAD

**Issue by gdnand** [catppuccin/catppuccin#33]
An Emacs port would be very cool to have and I am down to help!

**Comment by pspiagicw** [comment]
@gdnand have you started working ? I would like to help , already have a partial working theme file.

**Comment by pspiagicw** [comment]
I have a working theme. Still needs work but is a good staring point - https://github.com/pspiagicw/catppuccin-emacs

**Comment by pacbru1260** [comment]
There's this theme as well: https://github.com/konrad1977/emacs/blob/main/themes/catppuccin-theme.el

**Comment by pspiagicw** [comment]
The port https://github.com/pspiagicw/catppuccin-emacs is uploaded to MELPA. I think we can transfer it to official `catppuccin` organisation. Any suggestions are welcome!

**Comment by WitherCubes** [comment]
> The port https://github.com/pspiagicw/catppuccin-emacs is uploaded to MELPA. I think we can transfer it to official `catppuccin` organisation. Any suggestions are welcome!

Please change the repo's name from `catppuccin-emacs` to `emacs`. After that I will tell @Pocco81 to add you to the org and you can move this to the org.

**Comment by pspiagicw** [comment]
> > The port https://github.com/pspiagicw/catppuccin-emacs is uploaded to MELPA. I think we can transfer it to official `catppuccin` organisation. Any suggestions are welcome!
> 
> Please change the repo's name from `catppuccin-emacs` to `emacs`. After that I will tell @Pocco81 to add you to the org and you can move this to the org.
Repository renamed

**Comment by pspiagicw** [comment]
Now that the theme's been merged , you can close the issue
