### ISSUE TITLE
JetBrains

### ISSUE THREAD

**Issue by tiepp** [catppuccin/catppuccin#35]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

https://github.com/tiepp/catppuccin-idea

**Additional context 📷 (optional)**
I generated this from the VSCode port for my own and hopefully someone else's wellbeing :)

**Comment by Pocco81** [comment]
Hey! That's truly awesome. Sadly we haven't standardized syntax in the official style-guide. So, would it be possible for you to join our [Discord server](https://discord.gg/r6Mdz5dpFc) to further discuss the realization of this port and the possible limitations in JetBrain's IDEs?

**Comment by tiepp** [comment]
I moved work to the following repo: https://github.com/tiepp/catppuccin-jetbrains

**Comment by tiepp** [comment]
Hey, I've been happily driving this for some days. I'd love to see this in the org. Let me know what you think.

**Comment by Pocco81** [comment]
Looks lovely! I'll try to tweak it here and there to make syntax match the other IDE/DE ports (like the one for NeoVim). Apart from that, I guess it's ready to be moved, innit? I just sent you an invitation to the Org, after accepting it you should be able to move it in :+1:

**Comment by tiepp** [comment]
In case you didn't know: There's a handy UI for that. Open the Catppuccin.theme.json and click on the button "Edit Editor Color Scheme". Changes you make in the UI are applied to the Catppuccin.xml in place, you don't necessarily have to edit the file. 

![edit_color_scheme](https://user-images.githubusercontent.com/7456980/152675634-966fe8db-7bd7-4cb3-a277-9a79586c0850.png)

**Comment by Pocco81** [comment]
OH! that's sweet, didn't know about that. Thanks for the tip ;)
