### ISSUE TITLE
Fcitx5

### ISSUE THREAD

**Issue by ayamir** [catppuccin/catppuccin#38]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
![image](https://user-images.githubusercontent.com/61657399/151201222-d882321d-8c65-4d28-9d79-790e8d541eb4.png)
repo link: https://github.com/ayamir/Fcitx5-Catppuccin/tree/main

**Comment by Pocco81** [comment]
Awesome! let's move it into the org, shall we? I just sent you an invitation to the org. After accepting it, you should be able to go to your repo's settings >> scroll down to the "Danger Zone" >> click Transfer and type `catppuccin`.

**Comment by Pocco81** [comment]
Ok I just saw you moved it to the org. Since you didn't set the repo up following the style-guide's [instructions](https://github.com/catppuccin/style-guide#creation) I'm going to be fixing those things now, hope you don't mind :+1:

**Comment by ayamir** [comment]
OK
