### ISSUE TITLE
Spotify (Spicetify-CLI)

### ISSUE THREAD

**Issue by davidbgonz** [catppuccin/catppuccin#44]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Created a port of Spicetify for theming Spotify: https://github.com/davidbgonz/spicetify

The color schemes work similar to the Firefox port where there is a separate color scheme for each accent color.

**Comment by andreasgrafen** [comment]
Looking good! You might want to update the readme to include proper attributions. ;)
The theme itself works quite nicely. :3

**Comment by Pocco81** [comment]
@davidbgonz ready to move it into th org?

**Comment by Pocco81** [comment]
I just sent you an invitation to the org. After accepting it you should be able to move it into the org.

**Comment by davidbgonz** [comment]
Thanks, there's a PR on current repo. Once I review that and update the attributions I'll move it to org.

**Comment by Pocco81** [comment]
Before closing the issue I just wanna say that WOW... that screenshot looks stunning 🤩
