### ISSUE TITLE
Grub

### ISSUE THREAD

**Issue by elkrien** [catppuccin/catppuccin#45]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
I created Grub theme: [https://github.com/elkrien/catppuccin-grub](https://github.com/elkrien/catppuccin-grub)

**Comment by Pocco81** [comment]
Nice port! I just sent you an invitation to the org. After accepting it, you should be able to move the repo into the org.

**Comment by andreasgrafen** [comment]
Looking good! Sadly I don't use GRUB anywhere. Might have to change that, so I can enjoy this beauty. :'D

There are two opinionated suggestions I wanna make:
* Possibly tweak the Screenshot a little bit – probably nieche, but when one is using the Github custom CSS the preview gets lost because it doesn't accentuate from the background at all.
* I personally wouldn't put dracula into the »Thanks« section, but rather mention that it's based on their GRUB port in the description further up?

**Comment by elkrien** [comment]
> * Possibly tweak the Screenshot a little bit – probably nieche, but when one is using the Github custom CSS the preview gets lost because it doesn't accentuate from the background at all.

Thx for suggestions. I have tried to do something with the screenshot and I have created something like this. When You click on it then You see only grub printscreen. 
![image](https://user-images.githubusercontent.com/78103450/152203741-05cfa1e3-bee4-45f4-9dc8-24263c1da0c6.png)

> * I personally wouldn't put dracula into the »Thanks« section, but rather mention that it's based on their GRUB port in the description further up?

I have removed it. In theme.txt there is a description that theme is based and inspired by dracula and vimix themes. I think it is enough.

**Comment by elkrien** [comment]
> Nice port! I just sent you an invitation to the org. After accepting it, you should be able to move the repo into the org.

Thx. I have accepted invitation. I will move my themes to the org, just want to make sure that I'm doing it in a proper way so let me educate myself and read all the rules again. Or maybe You have some advices? Don't want to mess anything and to be honest I'm not professional git user. Should I create new repo and push files to it and then make PR to main catppuccin adding a link to it or in a different way?

**Comment by andreasgrafen** [comment]
In the settings for your existing Repo you can transfer the ownershi to the org. It will then be listed unter `catpuccin` and you'll get maintainer access so that you can keep working on it. It basically stays the same repo, just the namespace will change. c:

**Comment by elkrien** [comment]
Done. The only thing I didn't do is to set a proper description of repo before transfer. Please correct it (I'm not able to to id now). PR submitted to dev branch
