### ISSUE TITLE
Nova by Panic

### ISSUE THREAD

**Issue by mimishahzad** [catppuccin/catppuccin#48]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
https://nova.app/

**Comment by andreasgrafen** [comment]
Damn, that hits nostalgia! I've been starting out with Coda2 ages ago when I switched to Mac. I don't know much about Nova, but it might be necessary to own a license to fully test a potential port? That would make things a little mor difficult. o:

**Comment by daveyholler** [comment]
I've got an [unofficial port](https://github.com/daveyholler/Catppuccin-Nova) in the [Nova extension library](https://extensions.panic.com/extensions/holler/holler.CatppuccinTheme/). Contributions and improvements are welcomed.

**Comment by nekowinston** [comment]
Hey @daveyholler thanks for moving the issue over here 🙂 

If you want to get your port moved to `catppuccin/nova`, you'd please have to check the following things first:
- Repo description (e.g. `🌟 Soothing pastel theme for Nova`, or any emoji you might want to choose) 
- Add an [MIT License](https://github.com/catppuccin/template/blob/main/LICENSE)
- "Thanks to"  section where you add yourself, and the rest of the footer from https://github.com/catppuccin/template#-thanks-to

The port looks slick, and we'd be happy to get it moved to the org 🎉

**Comment by daveyholler** [comment]
@nekowinston Thanks! Handled!

**Comment by daveyholler** [comment]
Rock and roll! https://github.com/catppuccin/nova

**Comment by nekowinston** [comment]
Many thanks! 🙌 

I've added it to the main README just now, and updated your permissions to full maintainer access on `catppuccin/nova`.

**Comment by nekowinston** [comment]
One minor thing which I've just noticed, the README in Nova still points to the old URL:
https://github.com/catppuccin/nova/blob/f9cd797908f886990ed3027fda60556cb9ce39ee/README.md?plain=1#L8-L12

**Comment by daveyholler** [comment]
Ah! Nice catch. I'll update that.
