### ISSUE TITLE
KDE

### ISSUE THREAD

**Issue by Pocco81** [catppuccin/catppuccin#5]
Initially requested here: https://www.reddit.com/r/unixporn/comments/rc33mf/oc_catppuccin_a_new_soft_and_warm_theme_for_your/hntikce?utm_medium=android_app&utm_source=share&context=3

**Comment by Prayag2** [comment]
Hi, I'm [u/haxguru](u/haxguru) from Reddit. I'll do it soon in my free time!

**Comment by Prayag2** [comment]
I wanted to ask, what should be the background colour? Should it be black 1,2,3 or 4?

**Comment by Prayag2** [comment]
Hi, it's looking like this as of now:
![image](https://user-images.githubusercontent.com/39525869/145411574-83ec1bfb-0c0d-4c54-b181-bbea70044ab5.png)
Please let me know if this needs any improvements.

**Comment by Pocco81** [comment]
> I wanted to ask, what should be the background colour? Should it be black 1,2,3 or 4?

Good question lol. I haven't standardized that yet but for all the ports I used Black 3 as the "main background". Feel free to choose whichever ever you see that fits better :)


Talking about port, it looks very well put together! But to give some more contrast and to make it stand out more I'd recommend:

+ A wallpaper like [this one](https://github.com/catppuccin/wallpapers/blob/main/minimalistic/peach_unicat.png) or [this one](https://github.com/catppuccin/wallpapers/blob/main/minimalistic/flamingo_unicat.png)
+ Use a terminal currently supported by Catppuccin (do you want a Konsole port tho? :) My personal favorite is Kitty ❤️ 
+ Use [Rxfetch](https://github.com/Mangeshrex/rxfetch)
+ An icon pack like "La Capitaine" or "Flat Remix". I found a top 10 for you to choose from: https://linuxiac.com/10-best-and-most-popular-icon-themes-for-linux/
+ Could you use Latte Dock? I've seen many rices using it and it's really pretty! I'm not a KDE user myself, but when I tried it 

But now, talking about the theme itself and not just the screenshot:

+ It's really good, I don't have any recommendations. Good job :)

**Comment by Prayag2** [comment]
> Use a terminal currently supported by Catppuccin (do you want a Konsole port tho? :) My personal favorite is Kitty heart

I already made a Konsole port with this one (took 5 mins lol). I'll use Kitty for the promo screenshot.

> Could you use Latte Dock? I've seen many rices using it and it's really pretty! I'm not a KDE user myself, but when I tried it

Okay! I'll use it but I'll have to install it. I'll install it after the colour scheme is complete only for the promo. For the time being, I'll share the screenshots of my current setup.
Thanks!

**Comment by Prayag2** [comment]
> An icon pack like "La Capitaine" or "Flat Remix". I found a top 10 for you to choose from: https://linuxiac.com/10-best-and-most-popular-icon-themes-for-linux/

There's a problem. These icon packs don't follow the colour scheme.  They'll look weird:
![image](https://user-images.githubusercontent.com/39525869/145423960-d4411058-ad43-430b-a9f3-ee5f8b0f3a2a.png)

**Comment by Pocco81** [comment]
Have you uploaded the theme a repo or something?

**Comment by Pocco81** [comment]
> For the time being, I'll share the screenshots of my current setup

Oh don't worry about that now, first we gotta finish the theme lol

> These icon packs don't follow the colour scheme. They'll look weird.

Damn you are right, we gotta find better ones.

**Comment by Prayag2** [comment]
> Have you uploaded the theme to a repo or something?

No. I think I'll share the zip file to you so you can upload it in your repo. It's your colour scheme after all.

**Comment by Prayag2** [comment]
Or you can just create a new repo and I'll submit a pull request :)

**Comment by Prayag2** [comment]
Hi, my exams are over now. I'll make a pull request soon!

**Comment by Prayag2** [comment]
![image](https://user-images.githubusercontent.com/39525869/147102742-711b7a39-be69-46b4-b6ce-75b2e95705b7.png)
How's this?
I found another icon pack which follows the colour-scheme and looks good! Please let me know if any changes are necessary.

**Comment by Prayag2** [comment]
Oh I'm so sorry I forgot about this. I'll create a repo today or tomorrow!

**Comment by Prayag2** [comment]
Hi @Pocco81. Please create a KDE repo so I can submit a pull request. After merging that PR, I'll add it to the KDE Store so that people will be able to download easily!

**Comment by Pocco81** [comment]
@Prayag2 to make things easy for everyone, you can create a repo on your account and then we can move it into the org. It's way faster than "creating a PR" 👍

**Comment by Prayag2** [comment]
Oh, okay! I'll do that!

**Comment by Prayag2** [comment]
Hi! The theme is ready!! Here's the link to my github repo: https://github.com/Prayag2/catppuccin_kde
I've uploaded it to the KDE Store too! Here's the link: https://store.kde.org/p/1690443

**Comment by Prayag2** [comment]
Hi, @Pocco81. Sorry to bother you again but when are you going to move this repo in the org?

**Comment by Pocco81** [comment]
oh no I'm not going to move it, first and foremost because I can't lol. I just sent you an invitation to the org. After accepting it you should be able to transfer the repo :+1: Let me know when you are done with that so that I can finish setting up a couple of things on my end.

**Comment by Prayag2** [comment]
Hi @Pocco81, I have created the repository. Here's the link: https://github.com/catppuccin/kde
It is private at the moment and I've made you the admin. Please make any changes that you would like to make. Thank you!

**Comment by Pocco81** [comment]
I did the changes. Should be good to go :)
