### ISSUE TITLE
Joplin

### ISSUE THREAD

**Issue by ghostx31** [catppuccin/catppuccin#56]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
I have created a port for Joplin, an open-source note taking app. The port is present at [ghostx31/joplin](https://github.com/ghostx31/joplin)

Here are some screenshots:
![joplin-1](https://user-images.githubusercontent.com/68803793/152511758-9316a476-75b9-4c02-a34a-b1e8be995a18.png)

![joplin-2](https://user-images.githubusercontent.com/68803793/152511778-1c48a332-7bb8-49eb-8a5e-9bd3472b1cd9.png)

**Comment by andreasgrafen** [comment]
Uhh, I like that! Might actually get me back to using Joplin. :D

While I personally like using lavender as the colour for main text, it may be hard on the eyes for some people. Maybe it should just be the regular white? The grey on the sidebars is also a little low in contrast, I think.

**Comment by ghostx31** [comment]
> Maybe it should just be the regular white?

I kept it blue since I wanted some kind of colour distinction between the normal text and text in the code block but it can be made white if needed. 

> The grey on the sidebars is also a little low in contrast, I think. 

What I've done is that the text gets white when hovered over but I'll try to make it white completely and then just darker the background when hovered over.

**Comment by andreasgrafen** [comment]
> I kept it blue since I wanted some kind of colour distinction between the normal text and text in the code block but it can be made white if needed.

Yeah, I can see that. Maybe grey-2 could work for regular text as well? That would still keep a difference in colour while being not too heavy on the eyes?
It also might just be me that has some concerns because of that. :D
<br> 

> What I've done is that the text gets white when hovered over but I'll try to make it white completely and then just darker the background when hovered over.

What colour is it using right now? I wanna say it's Black-4? So Grey-0 or -1 might work just as well. I don't dislike the fact that it's not in full white, it's just a little too low in contrast. I didn't check with any contrast checker tho, so I might as well be wrong here.

**Comment by ghostx31** [comment]
![Screenshot from 2022-02-04 18-44-51](https://user-images.githubusercontent.com/68803793/152535256-3f86b040-2f27-4e0f-9f67-bceb07790597.png)
Does this look better? I made all the side panel text white, added the darker background on hover and focus, and the text turns blue when focused. 
I also changed the colour of text in code block to grey-2 and changed the colour of the normal text to white.

There's one thing that I haven't been able to work out. When selecting text from the markdown editor, if performing selection in a code block, the selection does not appear on the code block.  I've searched joplin forums and have been looking into the css but I cannot figure what's not working. I came across a post that its due to the CodeMirror's internal working so IDK. If anyone else can make it work, it'd be helpful. 
![Screenshot from 2022-02-04 18-47-33](https://user-images.githubusercontent.com/68803793/152535644-a4ad738d-76d7-4d81-8fcc-258bc8872b75.png)

**Comment by andreasgrafen** [comment]
Oh, yeah! I think that works really well this way too. c:
While it's def. less stylised I think that it's a lot easier on the eyes, which is something that is a good thing for a productivity app?

The selection issue seems like a little bit of a bummer, but I'd assume that this would happen without a theme too?

**Comment by ghostx31** [comment]
> While it's def. less stylised I think that it's a lot easier on the eyes, which is something that is a good thing for a productivity app?

Haha you're right lol.

The selection issue does not happen when Joplin uses its internal style sheets. It also doesn't happen if the background colour of the code block is not changed in a theme but happens once the colour is changed, it stops showing the selection. I didn't want to leave the block colour the default way since it breaks the continuity of the theme and I'd rather have no visible selection than have the weird colour bug me when I'm writing. I'll still try to see if it can be fixed.

**Comment by andreasgrafen** [comment]
Huh.. even weirder. o:
Since it's just CSS would it be possible to just force this by doing something like `codeblock::selection { ... }`?

**Comment by ghostx31** [comment]
That's what I've been trying to do as well. 
```
pre.cm-jn-code-block.CodeMirror-line {
	background-color:⋅var(--darkest) !important;
}
 pre.cm-jn-code-block.CodeMirror-line::selection {
	background-color:⋅var(--lighter-grey) !important;
}
```
but it doesn't work. Its something related to how CodeMirror (Joplin's internal editor) works with its own stylesheets according to posts on their forum but since there's no documentation for that, I cannot be sure.

**Comment by andreasgrafen** [comment]
nyeh.. That's annoying! ,_,
Well if it's not possible to fix this as of rn it will just be this way.

**Comment by ghostx31** [comment]
![Screenshot from 2022-02-05 11-32-11](https://user-images.githubusercontent.com/68803793/152630714-df6546fd-6443-4102-9977-d69a2b441917.png)

I found out a hacky way around the problem but still cannot make it seamless like the rendered markdown :(
I extracted the CodeMirror internal css and checked and the class for selected text is `.CodeMirror-selected {...}` but even if I do 
``
.CodeMirror-selected {
	background: var(--blue) !important;
}
``
it doesn't work so I had to resort to this hacky way.

**Comment by andreasgrafen** [comment]
Heya @ghostx31, is there any progress by chance? o:

**Comment by ghostx31** [comment]
Hey @andreasgrafen so sorry I have been busy with my University exams and stuff. 
And no, I've read all of their internal CodeMirror CSS and I couldn't find any selector to handle this so I'm obviously stuck here. And there was no reply to my query on the Joplin forums so yeah, that's a dead end as well.

**Comment by ghostx31** [comment]
Hello again! Sorry I am kinda new to contributing to open-source. Is there anything else I am supposed to do right now? Or do I have to close this issue? 😅

**Comment by elkrien** [comment]
I think You should update it to 0.2.0 palette and then You will be invited to organization so you will be able to add theme to it.

**Comment by ghostx31** [comment]
Oh right okay. I'll do that asap. Thank you!
