### ISSUE TITLE
Plank

### ISSUE THREAD

**Issue by elkrien** [catppuccin/catppuccin#58]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
OK, so I have created one more theme - for Plank: https://github.com/elkrien/plank
It is completed so just let me know and I will do a PR - there are two themes (solid and with some transparency) :
![image](https://user-images.githubusercontent.com/78103450/152656007-2189fdf8-a160-4537-91b3-ff4fdf65de37.png)

**Comment by Pocco81** [comment]
Looks good! feel free to move into the org whenever you can :+1: (also a PR to put it in the readme (`dev` branch of course) would be nice if it's not too much to ask for)

**Comment by elkrien** [comment]
OK, submitted PR. I wasn't sure in which category should I insert it - I listed Plank in System.
