### ISSUE TITLE
Gnome terminal

### ISSUE THREAD

**Issue by Pocco81** [catppuccin/catppuccin#6]
Initially requested here: https://www.reddit.com/r/unixporn/comments/rc33mf/oc_catppuccin_a_new_soft_and_warm_theme_for_your/hnufabf?utm_medium=android_app&utm_source=share&context=3

**Comment by broccoli5** [comment]
I might do this port myself today. If I don't the Dracula guys have nice install script for Gnome Terminal which could be used: https://github.com/dracula/gnome-terminal

**Comment by Pocco81** [comment]
> Dracula guys have nice install script for Gnome Terminal which could be used

Good idea! I'm on Gnome so I'll try it out.

**Comment by broccoli5** [comment]
So, I basically have it. I dissected the script from the Dracula guys and made it a *lot* simpler. The only thing that's missing is a screenshot, but I will leave that to you.

Also I never contributed anything like this, so can you please guide me through what to do?

**Comment by Pocco81** [comment]
Awe thanks! I really appreciate your help :)

So I made the repo: https://github.com/catppuccin/gnome-terminal

You just have submit a PR. To do that fork the project, clone your fork locally, add the theme file(s) + some instructions for installling it in the README, commit them, push to your fork, and then make the actual pull request on the original repo. If you wanna learn about how to make pull requests I'd recommend you [this video](https://www.youtube.com/watch?v=rgbCcBNZcdQ).

Let me know if you need help/have any questions :+1:

**Comment by Pocco81** [comment]
Done: https://github.com/catppuccin/gnome-terminal

![preview](https://user-images.githubusercontent.com/58336662/149874501-f47a16c4-f545-4d51-a260-e57b9b952fd8.png)
