### ISSUE TITLE
Geany

### ISSUE THREAD

**Issue by Waxxx333** [catppuccin/catppuccin#61]
I noticed there's no theme for Geany(cross-platform IDE) yet and would love to contribute. 

[Repo](https://github.com/Waxxx333/Catppuccin_Geany)

SS ↓
![catppuccin_geany](https://user-images.githubusercontent.com/59426207/152668080-2942e9ee-3f11-450c-9c00-90ecaf74ba47.png)
![catppuccin_geany2](https://user-images.githubusercontent.com/59426207/152668082-1f68489f-0f10-4c38-a41c-2b2dbdddd05f.png)

**Comment by Pocco81** [comment]
Do you have this in a repo already? if so, could you share the link here please :)

**Comment by Waxxx333** [comment]
> Do you have this in a repo already? if so, could you share the link here please :)

Yup, right [here](https://github.com/Waxxx333/Catppuccin_Geany).

**Comment by Waxxx333** [comment]
Updated the repo. Added an installer and changed one of the string colors.
