### ISSUE TITLE
Mailspring

### ISSUE THREAD

**Issue by elkrien** [catppuccin/catppuccin#63]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**

One more thing I'm working at - Mailspring. Trying to follow official theme guide. Done a little bit already but need more time. 
Anyone would like to help or suggest anything?
![image](https://user-images.githubusercontent.com/78103450/152702316-704d4fec-ae97-4304-a8e7-0077e174d47e.png)

**Comment by Pocco81** [comment]
I don't use Mailspring, but judging by the screenshot it looks pretty darn good!

**Comment by elkrien** [comment]
OK, repo added, PR submitted.
