### ISSUE TITLE
Monkeytype.com

### ISSUE THREAD

**Issue by andreasgrafen** [catppuccin/catppuccin#65]
[M O N K E H](https://monkeytype.com/) 🐒

**Are you available to help in the creation of this port?**
Absolutely! ♡

**Additional context**
> Monkeytype is a minimalistic typing test, featuring many test modes, an account system to save your typing speed history and user configurable features like themes, a smooth caret and more.

This really is just a super small thing, I've just been typing away and thought to myself "Huh, might be cool to have this in Catppuccin colours". I'm not even sure if it would get approved, as it requires a theme not to be similar to any of the existing ones.. and there are **a lot**, so there might be a conflict already?

**Comment by VictorTennekes** [comment]
I mean judging form their current theme list I'd say their "not similar" rule is quite broad.
Made a quick version here: [Catppuccin-MONKEH](https://monkeytype.com?customTheme=%231e1e2e%2C%23f8bd96%2C%23f8bd96%2C%236e6c7e%2C%23d9e0ee%2C%23e8a2af%2C%23f28fad%2C%23e8a2af%2C%23f28fad)

**Comment by andreasgrafen** [comment]
I guess it's mostly to get the name out there anyway. :'D
The rule seems to be quite lose, but we'll see if we ever do a proper "port". 
I like the quick thing you did. ♡

**Comment by VictorTennekes** [comment]
Just checked their [github page](https://github.com/Miodec/monkeytype). Adding a theme seems to be as straightforward as adding the name to a json list, adding a color codes css file and opening the pr :)

**Comment by andreasgrafen** [comment]
Yeh, I've read through that too. I'm just not at home rn, so I can't to that right away. So it will have to wait until later. :D

**Comment by VictorTennekes** [comment]
Ah fun fact, catppuccin is already in their theme list

**Comment by VictorTennekes** [comment]
Was added [here](https://github.com/Miodec/monkeytype/pull/2410).

**Comment by WitherCubes** [comment]
Guess you can just steal the css, add it to the org and credit the creator of the theme.

**Comment by andreasgrafen** [comment]
damn. I must be experiencing some major cache issues then.
![image](https://user-images.githubusercontent.com/35840154/152785860-1e4028b0-f94c-4753-b1cf-64ea8276830d.png)

**Comment by WitherCubes** [comment]
I have this problem all the time, so I just automatically clean my cache every time I close my browser.

**Comment by andreasgrafen** [comment]
Yeah.. I would do that, but I'm not allowed to change any settings on the PC I'm using here at werk. Can't even manually clear it.. xd

But hey, if it's already there, I'll close this issue for now. Thanks for letting me know. ^—^
