### ISSUE TITLE
Windows 10/11 Theme

### ISSUE THREAD

**Issue by itsmeboy0** [catppuccin/catppuccin#69]
**Are you available to help in the creation of this port? 😄 (optional)**
No

**Additional context 📷 (optional)**
Windows 10/11 theme via [SecureUxTheme](https://github.com/namazso/SecureUxTheme) patcher.

Here's the [Dracula](https://www.deviantart.com/niivu/art/Dracula-for-Windows-895311666) theme for reference:
![Dracula by niivu](https://user-images.githubusercontent.com/75471378/153406434-04109bbb-c8ea-486e-a0c4-0c3bcc4a01d6.png)

**Comment by itsmeboy0** [comment]
Looks like the author has created his own [Catppuccin theme](https://www.deviantart.com/niivu/art/Catppuccin-908397507).

Ping @niivu

**Comment by andreasgrafen** [comment]
Whith this existing (tho not on the org) I'll close this issue as it's most likely the best we'll ever going to get for windows. c:

**Comment by itsmeboy0** [comment]
Well, any plans to move it to this org for discoverability?

**Comment by andreasgrafen** [comment]
Doesn't look like this is planned – a decision on the other side..
