### ISSUE TITLE
iTerm2

### ISSUE THREAD

**Issue by VictorTennekes** [catppuccin/catppuccin#7]
I saw you're using different repositories for different applications, I have made a port for iTerm2 based on the already existing Alacritty config. I was wondering what the best way would be to contribute this :)

**Comment by Pocco81** [comment]
Awe thanks mate for helping out!

> I was wondering what the best way would be to contribute this :)

There is [this](https://github.com/catppuccin/template) public template with instructions.

**Comment by VictorTennekes** [comment]
Happy to help! Just opened the pr 😸

**Comment by Pocco81** [comment]
Merged! thank you for the help :)
