### ISSUE TITLE
⚠️ GitHub issues spam - Important

### ISSUE THREAD

**Issue by Pocco81** [catppuccin/catppuccin#727]
Less then 2 hours ago 400+ spam issues were opened here. Please note that those are not valid issues and the situation is being handled privately.

New issues (i.e. port requests) might get lost amidst the junk, so please abstain from opening new one while the situation gets sorted out.

All of Catppuccin core developers as well as GitHub themselves were notified about the spam. This will be back to normal soon (hopefully).

Thanks.

**Comment by nekowinston** [comment]
We since got hit by another batch of spam issues.

I've disabled creation of New Issues, PRs, etc. for the next 24h for the whole organization.

**Comment by nekowinston** [comment]
The situation has been resolved, and I've disabled interaction limits again.

**Comment by BlueFalconHD** [comment]
So does anybody know what actually happened?

**Comment by nekowinston** [comment]
Someone created ~400 new GitHub accounts, and spammed our repositories, among other orgs, with about 800-1000 issues.

**Comment by BlueFalconHD** [comment]
Thats been happening recently. I recently found a network of ~100 accounts with viruses disguised as video game hacks. There were 3-4 accounts hosting, and the rest just starred all of them.
