### ISSUE TITLE
Atom

### ISSUE THREAD

**Issue by GiraffeMan3125** [catppuccin/catppuccin#73]
**Are you available to help in the creation of this port? 😄 (optional)**
Yup

**Additional context 📷 (optional)**
You can download it at https://atom.io/.

**Comment by GiraffeMan3125** [comment]
Hey so I finished the theme, and I can upload the files if needed. Now what do I do?

**Comment by Spaxly** [comment]
> Hey so I finished the theme, and I can upload the files if needed. Now what do I do?

Hey, please join the catppuccin discord server (https://discord.gg/PrCRSWftUa) and we can help to transfer the repository to the catppuccin organization.

**Comment by andreasgrafen** [comment]
Due to the recent decision to discontinue Atom this most likely isn't needed anymore. :c
https://github.blog/2022-06-08-sunsetting-atom/

**Comment by andygeorge** [comment]
Hey @GiraffeMan3125 do you still have your catppuccin/Atom theme? I don't see it on the Atom themes site, but I would love to install it!

**Comment by Spaxly** [comment]
Atom is now discontinued so this 🕜 rt is now useless.

**Comment by khalangy** [comment]
Hello, atom has been forked by a team https://pulsar-edit.dev/
Is it possible to share the catpûcicn theme for it please :) ?

**Comment by Spaxly** [comment]
> Hello, atom has been forked by a team https://pulsar-edit.dev/
> Is it possible to share the catpûcicn theme for it please :) ? 

Wouldn't it work the same way it did for Atom?

**Comment by khalangy** [comment]
Yes it work the same it did for Atom so if @GiraffeMan3125  have still the file it would be nice to add it :)

**Comment by GiraffeMan3125** [comment]
i dont actually have the file anymore because i have started using nvim. i might try to move back to atom thoughOn Jan 20, 2023, at 9:08 AM, Khalangy ***@***.***> wrote:﻿
Yes it work the same it did for Atom so if @GiraffeMan3125  have still the file it would be nice to add it :)
