### ISSUE TITLE
Foot terminal

### ISSUE THREAD

**Issue by crdpa** [catppuccin/catppuccin#79]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes, already made

**Additional context 📷 (optional)**
So, i'm new to this whole contributing things. Can somebody guide my hand and give me a step-by-step in how to contirbute? I made the theme for foot terminal. It is relatively simple, but i want to put here.

**Comment by VictorTennekes** [comment]
Thank you for submitting the port! I'd suggest joining [the discord server](https://discord.com/invite/r6Mdz5dpFc). There's plenty of people in there that would love to help you in transferring the repository!

**Comment by crdpa** [comment]
Joined!

I made the repository. Here: https://github.com/crdpa/foot-catppuccin

**Comment by Pocco81** [comment]
@crdpa nice port! I just sent you an invitation to the org. After accepting it, you should be able to transfer the repository into the org.

**Comment by crdpa** [comment]
It is done. Just need to update the "Terminals" part of README.md to include Foot.

**Comment by VictorTennekes** [comment]
Pretty sure we can close this issue since we have https://github.com/catppuccin/foot now.
