### ISSUE TITLE
Visual Studio 2022

### ISSUE THREAD

**Issue by Cutwell** [catppuccin/catppuccin#80]
**Are you available to help in the creation of this port? 😄**
Yes

**Additional context 📷 (optional)**
I've ported the existing VSCode theme into Visual Studio 2022 using the [Microsoft theme-converter-for-vs](https://github.com/microsoft/theme-converter-for-vs), and packaged it into an appropriate extension for VS.
 
![example](https://user-images.githubusercontent.com/22395357/154729804-bdfed431-cd80-44fb-8d06-21cb50a1052c.png)
_A hello_world.cpp example script, with the Catppuccin theme._

The current project can be viewed at https://github.com/Cutwell/VS-catppuccin-theme.

**Comment by nekowinston** [comment]
Closed with a4a42d2cf657a15f148c80ac0da74582c68a7a18, tracked in issue #230.
