### ISSUE TITLE
Bpytop

### ISSUE THREAD

**Issue by latipun7** [catppuccin/catppuccin#81]
**Are you available to help in the creation of this port? 😄**
Maybe (currently didn't have time)

**Additional context 📷**
Bpytop is Linux/OSX/FreeBSD resource monitor. [Themes are managed in their repo](https://github.com/aristocratos/bpytop#themes) (I think). I don't know we should contribute the theme here or in the bpytop repo.

At a glance, I think the theming is quite simple, replace some color codes from the existing theme.

**Comment by andreasgrafen** [comment]
There is a port for [btop](https://github.com/catppuccin/btop) which werks perfectly fine with bpytop too. The demo screenshot actually is bpytop actually. :D

**Comment by latipun7** [comment]
oh my, I didn't know it that it share the same theme. I'm aware about that bptop theme, but didn't notice the screenshot as well.
Thank you.
