### ISSUE TITLE
Kvantum

### ISSUE THREAD

**Issue by etrigan63** [catppuccin/catppuccin#86]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
For those of us that use `kvantum-manager` to style our QT apps. I use Leftwm as my window manager and not full KDE.

**Comment by KaosBunny** [comment]
Seconding this! Kvantum just makes everything so much easier when dealing with QT5 on platforms other than KDE. There's a version of the Nord theme for kvantum that could work perfectly for this with just colour tweaks: https://store.kde.org/p/1533594/.

Installing themes via the qt5-styleplugins > gtk2 method is janky and the other method for qt5ct where you port a theme from oomox is confusing as all hell.

**Comment by Uiyx** [comment]
Are there any plans on porting to kvantum?

**Comment by andreasgrafen** [comment]
As of right now it doesn't seem like there is. If someone would be willing to start work on a port, that would be awesome! c:

**Comment by digitalwtf** [comment]
+1

**Comment by elkrien** [comment]
Started to do this theme - work in progress. Should be ready in few days.

**Comment by nekowinston** [comment]
added to the main README in 41a8b8710dbdc84b81ac5b27b697e0a54a2bf0f3
