### ISSUE TITLE
Insomnia

### ISSUE THREAD

**Issue by opakholis** [catppuccin/catppuccin#88]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
[Insomnia Plugin.](https://insomnia.rest/plugins/insomnia-plugin-theme-catppuccin)
[Repo](https://github.com/opxop/insomnia-catppuccin)

![image](https://user-images.githubusercontent.com/49778014/156957837-1900a633-2b6f-47af-954c-7920d8dcfd7a.png)

**Comment by andreasgrafen** [comment]
Heya, @opakholis. First up, sorry for the long delay.. The issue got lost somewhere and we totally forgot about it with the time passing.. With the release of [Version 2](https://github.com/catppuccin/catppuccin/#-palettes=) of the palette and the new flavours we're looking to get ever port updated. Would you be willing to work on this? c:

**Comment by opakholis** [comment]
of course i can, but maybe it will take a little longer because there is a lot to do IRL lol, is that ok?

**Comment by andreasgrafen** [comment]
Absolutely! No pressure whatsoever. c:

**Comment by opakholis** [comment]
heyo @andreasgrafen. sorry for the very very long delay, I've added a new palette🥳🥳
And sure, can you check it again? maybe I missed something..

**Comment by nekowinston** [comment]
Hi again 😅

The repo looks good, aside from one minor issue.

It still shows `generated from <template>` in the header; you'd have to:
- Make sure that your local repository is up to date with GH, or use a fresh `git clone`
- Delete the Repository on GitHub
- Re-create an empty one with the same name
- Push there again from your local repo

Once that is done, we can transfer it to the org 👍

**Comment by opakholis** [comment]
Thanks.. I've re-create the repository, and it looks like we've been able to transfer it to the Org🚀

**Comment by nekowinston** [comment]
Great! I've invited you to the org, please rename the repo to `insomnia` before transferring, and once it's transferred I'll give you maintainer access. 😄

**Comment by nekowinston** [comment]
I've updated the permissions - thanks for your work on the port! 🎉

**Comment by opakholis** [comment]
Thanks!
