### ISSUE TITLE
XFCE4-Terminal

### ISSUE THREAD

**Issue by pacbru1260** [catppuccin/catppuccin#92]
Hey! I've made a theme for xfce4-terminal which uses Catppuccin. I'd like to have it ported to this github account (I'm new on contributing w/ github so I have no idea on how to do this 😅) 
https://github.com/pacbru1260/xfce4-terminal

**Comment by elkrien** [comment]
Looks really nice - great job. 
If I may suggest something then try to set Catppuccin GTK theme in Your system and then make a screenshot. It will look more consistent and nice. 
Also You should follow [style-guide](https://github.com/catppuccin/style-guide) and [template](https://github.com/catppuccin/template) for Readme. 
Also see [this](https://github.com/catppuccin/catppuccin/blob/dev/CONTRIBUTING.md) to read how to contribute.

**Comment by pacbru1260** [comment]
Thank you! I'll do it

**Comment by pacbru1260** [comment]
Hey @elkrien sorry for bothering but the only thing I got confused is on how to contribute... btw I've finished styling the repo!

**Comment by elkrien** [comment]
The screenshot looks great now :)
But still Your Readme is not as it should be - look at [template](https://github.com/catppuccin/template).
For contributing I will try to guide You:
1. When Your repo is ready You wait for Pocco81 to add You to Catppuccin organization - You will receive invitation when Pocco81 will verify Your theme and will say that it is OK - he is a boss here :) 
2. Then You change Your repo ownership to Catppuccin organization (Open Settings of Your repository, scroll down and search for "Transfer Ownership") - when ownership has been transfered I usually change links to new url for stars, contributors and issues, i.e.: 
![image](https://user-images.githubusercontent.com/78103450/157327941-88fa8f19-498d-41b1-b46e-5b3e5a94c577.png)
3. Then fork catppuccin/catppuccin repository and make changes in forked repository in dev branch (add link to Your transferred repo in a proper category).
4. Then in forked repo You will have an option to merge it with original repository (open pull request - the easiest way to do it is by the github website).
Let me know if You have some problems or more questions - I will try to help.

**Comment by pacbru1260** [comment]
How I am going to know that Pocco81 is going to add me to the catppuccin org...?

**Comment by elkrien** [comment]
> How I am going to know that Pocco81 is going to add me to the catppuccin org...?
> 
> 

Don't worry. He will contact You when Your repo is ready to be merged. Just be patient ;)

**Comment by DonutDev** [comment]
Also consider joining the discord server if you aren't there :)
Nice port by the way

**Comment by pacbru1260** [comment]
@DonutDev hey donut, I wish I could, but I won't since I have some personal issues that don't allow me to go back onto discord.
(btw I'm the pac.conf user on the mint server)

**Comment by DonutDev** [comment]
It's fine, I told Pocco about it. You might recieve a request to join the organization ( it will be sent on the mail you signed on github with )

**Comment by pacbru1260** [comment]
Ah alright, gotcha

**Comment by pacbru1260** [comment]
Soooo, I'm still waiting but I'm also anxious to join the org tbh :P
