### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by elkrien** [catppuccin/catppuccin#93]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**

OK - so I tried to add catppuccin colors to YouTube-DeepDark but it was not merged so I forked this project and modified it by myself. "My" version includes only Catppuccin themes (it is a dark themes with different accent colors - can be changed in Stylus options). All description and installation guide is included in repo - https://github.com/elkrien/YouTube-Catppuccin
Let me know if it is OK to be merged in Catppuccin organization - if not I will live it like it is right now in my repos.
Screen with lavender accent: 
![image](https://user-images.githubusercontent.com/78103450/157301600-174b87a4-c38c-43d8-bbf8-997c64c095b2.png)

**Comment by KaosBunny** [comment]
You can achieve this through the YouTube enhancer extension. (I think this is available on Chromium browsers as well?)
There is a section for custom CSS or you can select the "YouTube-DeepDark (custom)" tick box and set the colours through the gui.

**Comment by elkrien** [comment]
Don't see any comments so I made PR to dev. Please close after merge.
